### ISSUE TITLE
Deployed example code doesn't accept requests from within a DigitalOcean VPC

### ISSUE THREAD

**Issue by willdavidc** [nanovms/ops#1009]
Hi, I've been investigating the possible use of ops in a production environment, on DigitalOcean (DO). I've been trying to get the minimal example from the README working properly.

I followed the instructions, created `hi.js`, built an image with `ops image create --package node_v14.2.0 -a hi.js`, uploaded to DO and spun up a droplet based on the image. This all worked great, and when I tried to access the public IP of the instance on port 8083, I got the expected `Hello World` response.

However, DO also assigns a private VPC IP to each host, in this case, `10.120.0.7`, and the image doesn't respond to requests there. This includes health checks from DO load balancers (which can only use the private IP address), and when I spun up a linux box within the VPC and `curl`ed the address:port from there.

<img width="503" alt="Screen Shot 2021-04-22 at 12 39 53 PM" src="https://user-images.githubusercontent.com/14321983/115752193-de366d80-a367-11eb-8502-39c96b752c82.png">

Some limitations of DO's system:
- No way to know in advance what the IP addresses of a new host will be (their "floating IPs" can't be assigned to droplets with custom images)
- Can't just use the public IPs, since we're dependent on DO's load balancers
- Droplets with custom images can't use IPv6

I ran `ifconfig` on the Linux host that I span up for testing, it looks like the private IP address is on an `eth1` network interface
<img width="556" alt="Screen Shot 2021-04-22 at 12 39 27 PM" src="https://user-images.githubusercontent.com/14321983/115752909-906e3500-a368-11eb-96ec-8879b4555aa9.png">

Here's the unikernel's output:
<img width="438" alt="Screen Shot 2021-04-22 at 12 46 08 PM" src="https://user-images.githubusercontent.com/14321983/115753039-b693d500-a368-11eb-811b-e766f521bc66.png">

I know responding to this might not be high on your priority list, but I'm excited to start using these if there's a solution. Thanks very much!

Edit: Modifying `hi.js` to return the results of Node's `os.networkInterfaces()` gives this:
<img width="279" alt="Screen Shot 2021-04-22 at 5 18 13 PM" src="https://user-images.githubusercontent.com/14321983/115786889-65e3a280-a38f-11eb-9094-d5430388693f.png">

**Comment by francescolavra** [comment]
Hi @willdavidc, as you can see the private IP address is not being assigned to the second network interface (called "en2"). That's because the internal DHCP client in the unikernel currently runs only on the first network interface ("en1").

**Comment by eyberg** [comment]
we can certainly look at adding support for extra interfaces

**Comment by eyberg** [comment]
@willdavidc looks like this is now working w/latest 0.1.34 release - can you confirm?

**Comment by wjhun** [comment]
Hello @willdavidc. Assignment of the private IP should now be addressed with the merging of https://github.com/nanovms/nanos/pull/1461. I just spun up a droplet running a Nanos image and am able to reach it over the private net from another Linux image.

This change has been added to nanos pre-release 0.1.34 this morning, so if you make a new image with ops it should get picked up.

**Comment by willdavidc** [comment]
That's amazing, thank you! Can confirm DO's private networking/load balancers work great now.

(This might be obvious, but if anyone else stumbles across this looking to do the same: `ops image create --nanos-version 0.1.34 --package node_v14.2.0 -a hi.js` was the command I used here)
