### ISSUE TITLE
pkg get is downloading to ~/.ops/local_packages ?

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1041]
i just tried a get, vs what I normally do w/load and it seems 'get' is downloading to local_packages instead of packages by default?

that should only happen if passed the '--local' flag like in ops pkg load

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/blob/master/cmd/cmd_pkg.go#L34
https://github.com/nanovms/ops/blob/master/cmd/cmd_pkg.go#L140

**Comment by arknable** [comment]
I can reproduce this
```
arknable@arknable-x1c:~/.../ops$ ./ops pkg get vault_1.7.1
 100% |████████████████████████████████████████|  [14s:0s]
arknable@arknable-x1c:~/.../ops$ ls ~/.ops/packages/
manifest.json  tomcat_9.0.19
arknable@arknable-x1c:~/.../ops$ ls ~/.ops/local_packages/
vault_1.7.1

```
