### ISSUE TITLE
pkg describe looks broke

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1042]
```ops pkg describe tomcat_9.0.19``` seems to work but not ```ops pkg describe vault_1.7.1```

**Comment by arknable** [comment]
@eyberg it looks fine in linux
```
arknable@arknable-x1c:~/Development/Project/nanovms/ops$ ./ops pkg describe vault_1.7.1
Information for vault_1.7.1 package:
This is a package of HashiCorp's Vault:

To try it out:
```
ops pkg load -c config.json -p 8200 vault_1.7.1
```

Don't forget to add some extra space to the disk via config.json:

```
{
  "BaseVolumeSz": "400m"
}
```

By default data is stored in /etc/vault/data and the config file is in
/etc/vault/config.hcl.
```

**Comment by arknable** [comment]
@eyberg is it still an issue on mac os ?

**Comment by eyberg** [comment]
can't repro - maybe it was related to the localpackage issue - closing
