### ISSUE TITLE
python package needed

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#105]
@erectcrested reported getting hello world working here - fill in details and turn into a pkg

**Comment by eyberg** [comment]
@mkhon reported 3.5 is now working as well so we'll want pkgs for both as the python community is still very much split between the two major versions

**Comment by skupr** [comment]
I was able to create packages for python 2.7 and 3.6 made by virtualenv.
Simple hello world  program works fine, but there are problems with imports - many of the standard modules, for example "json" are not included in virtualenv, so we get "ImportError: No module named json" error. So I think we need just copy the whole /usr/lib/python2.7 directory to sysroot,

@eyberg What do you think? Do you want me to upload these (interim. I believe) packages somewhere? Or should I fix import issues first?

**Comment by mkhon** [comment]
Stas,

Please create an issue about failed "import  json" and either you or me
will take a look.

Max

**Comment by eyberg** [comment]
@skupr - yes the /usr/lib/python2.7 needs to be pkg'd up in sysroot - if you unzip an existing pkg you can see the structure but it's basically modeled after deb pkgs - as for the missing imports this is why '-S' was being used earlier so it's def. an issue

if you want to email me the pkg i can take a look - thanks

**Comment by mkhon** [comment]
Ian,

-S was used earlier because read(2) was broken and Python was not able to
read .py files (well, most of them, except short hello.py).

This is now fixed.

I will look at the failing json import.

Max

**Comment by eyberg** [comment]
2.7 is now published - we can keep this open for 3.X if you want since that'll prob. be out tmo then close

**Comment by eyberg** [comment]
w00t w00t - @mkhon && @skupr taking it down

```
➜  tz  ops list
+------------------+-----------+------------+-------------+
|   PACKAGENAME    |  VERSION  |  LANGUAGE  | DESCRIPTION |
+------------------+-----------+------------+-------------+
| python_2.7.15rc1 | 2.7.15rc1 | python     | python      |
+------------------+-----------+------------+-------------+
| python_3.6.7     | 3.6.7     | python3    | python3     |
+------------------+-----------+------------+-------------+
| ruby_2.3.1       | 2.3.1     | ruby       | ruby        |
+------------------+-----------+------------+-------------+
| lua_5.2.4        | 5.2.4     | lua        | lua         |
+------------------+-----------+------------+-------------+
| node_v11.15.0    | 11.15.0   | javascript | node_v8     |
+------------------+-----------+------------+-------------+
| node_v11.5.0     | 11.5.0    | javascript | node_v8     |
+------------------+-----------+------------+-------------+
| perl_5.22.1      | 5.22.1    | perl       | perl        |
+------------------+-----------+------------+-------------+
| php_7.2.13       | 7.2.13    | php        | php         |
+------------------+-----------+------------+-------------+
➜  tz  ops load python_3.6.7 -p 8083 -f -a hi.py
Downloading.. /Users/eyberg/.ops/packages/python_3.6.7.tar.gz
 18.33 MiB / 18.33 MiB [=============================================================================================================================================================] 100.00% 3.52 MiB/s 5s
Extracting /Users/eyberg/.ops/packages/python_3.6.7.tar.gz...
Downloading.. .staging/mkfs
 168.34 KiB / 168.34 KiB [===========================================================================================================================================================] 100.00% 3.54 MiB/s 0s
Downloading.. .staging/boot.img
 23.50 KiB / 23.50 KiB [=============================================================================================================================================================] 100.00% 4.05 MiB/s 0s
Downloading.. .staging/stage3.img
 1.41 MiB / 1.41 MiB [===============================================================================================================================================================] 100.00% 3.61 MiB/s 0s
[python3 hi.py]
booting image ...
assigned: 10.0.2.15
hi
exit_group
exit status 1
➜  tz  cat hi.py
print("hi")
```
