### ISSUE TITLE
images list doesn't complain to user if zone or projectid is not found/set

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1054]
both zone && project-id are necessary (for gcp)

```ops image list -t gcp``` fails
```ops image list -t gcp  -g myproject``` fails
```ops image list -t gcp  -z us-west2-a -g myproject``` works

ops should complain to user if either of these are not set via flag or env var or .opsrc

**Comment by arknable** [comment]
Closed as mentioned here: https://github.com/nanovms/ops/pull/1065#issuecomment-855246521
