### ISSUE TITLE
Mount Points Flag Input Parsed Incorrectly

### ISSUE THREAD

**Issue by arknable** [nanovms/ops#1061]
I found this issue when working on vscode extension. `--mounts` works for single input but always fail for multiple input such as follows:

```
 $OPS run hello --mounts 88cbe53c-92cd-e189-3960-61bec6177b47:/home/arknable/Development/Project/nanovms/tmp/mounts/a,d2423e10-9466-0a82-43eb-4697db2e3bc2:/home/arknable/Development/Project/nanovms/tmp/mounts/b --show-errors
 100% |████████████████████████████████████████|  [0s:0s]
mount config invalid: missing parts: 88cbe53c-92cd-e189-3960-61bec6177b47:/home/arknable/Development/Project/nanovms/tmp/mounts/a,d2423e10-9466-0a82-43eb-4697db2e3bc2:/home/arknable/Development/Project/nanovms/tmp/mounts/b

```

single mount works fine:
```
$OPS run hello --mounts 88cbe53c-92cd-e189-3960-61bec6177b47:/home/arknable/Development/Project/nanovms/tmp/mounts/a --show-errors
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/arknable/.ops/images/hello.img ...
en1: assigned 10.0.2.15
Server running at http://127.0.0.1:8083/
en1: assigned FE80::28D2:41FF:FE39:9499

```

when I checked, the output of [this line](https://github.com/nanovms/ops/blob/master/cmd/flags_build_image.go#L139) is a single element which value is the entire input which indicates the input is not correctly splitted.

@eyberg could you please verify if this is a valid issue ?

**Comment by eyberg** [comment]
well you should definitely be able to pass multiple mounts by specifying the uuid or the mount name (more common)

```
~/.ops/0.1.34/dump ~/.ops/images/g.img
...*snip*...
 mounts:(bob:/bob
         gvol:/gvol)
 program:/g)
➜  g cat config.json
{
  "Mounts": {
    "bob": "/bob",
    "gvol": "/gvol"
  }
}
```

looks like it's working with config setting but not via cli flag

I would imagine to pass multiple ones though you would specify --mounts multiple times rather than string concat?

**Comment by eyberg** [comment]
yeh - that actually works for me fine ->

```
➜  g ops run g --mounts bob:/bob --mounts gvol:/gvol
```

so no, I don't think this is a valid issue

**Comment by arknable** [comment]
@eyberg ah ok, I thought the value should be comma-separated. ok I understand, I will close this as false alarm.
