### ISSUE TITLE
exitWithError looks hosed

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1064]
was looking into why I wasn't getting output for a pkg i made and it looks like exitWithError is being passed an error but doesn't show any output

maybe correlated with all of these issues i found in the past week:

https://github.com/nanovms/ops/issues/1062
https://github.com/nanovms/ops/issues/1055
https://github.com/nanovms/ops/issues/1054

**Comment by francescolavra** [comment]
All of these issues are due to the fact that errors are now shown only if ops is passed the `--show-errors` flag, according to https://github.com/nanovms/ops/issues/764#issuecomment-835714773.

**Comment by eyberg** [comment]
ah - I don't think all errors should be wiped out like that - it really kills the dev exp and makes ppl wonder why their stuff isn't working

the proposed debug flag is meant to show things like api output from the cloud providers that might be used for debugging why something isn't working vs showing a normal error msg

**Comment by arknable** [comment]
I think the problem now is all error objects are being logged via `log.Error` and that function will only display message if error flag set, i.e. when `--show-errors` issued.

So I think first we should let `log.Error` always display error messages then add additional function such as `log.ErrorDetail` for `--show-errors` and recheck all error objects to select which ones should be suppress by default.

**Comment by eyberg** [comment]
yeh - that's the intent - we wanted separate levels of error output - most errors that are human readable like bad syntax in a config.json or a cli flag missing or whatever should be showing to the end-user by default (without having to pass a flag)

the errors that we wanted to hide by default and enable via a flag are more like extensive debugging output that would only be used by someone to determine why a resource in AWS/GCP isn't being created for example

**Comment by arknable** [comment]
so I think `--show-errors` flag actually not needed right ? we can just display whatever detail error via `--show-debug` flag

**Comment by arknable** [comment]
@eyberg After the PR merged, please retest the issue mentioned above. I will create separated issue to recheck all errors and add support for error detail via `--show-debug` flag.

**Comment by fabioDMFerreira** [comment]
The intent of `log.Error` is to show error details that help users identify the problem. For example, if an AWS call fails we want to know exactly what the API is returning.

I understand some useful information may be hidden. I would change the error message to make it more clear, and probably give the instructions on how to get more details about the error. For example, `AWS failed to create an instance due to permissions. Append flag --show-errors to see more details about the problem`.

https://github.com/nanovms/ops/issues/779

**Comment by arknable** [comment]
I think we can modify that method to be like `log.Error(message, detailError)` with `message` always displayed and `detailError` only displayed when `--show-errors` issued.
