### ISSUE TITLE
ops image delete 'image being used' logic is flawed - observed on gcp

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1105]
imageDeleteHandler looks for the set of images with the name of the image to be deleted and and gives it's key the name and value a (local path presumably)

further down it collects the number of alive instances and compares a non-existent image name to a non-existent path

**Comment by arknable** [comment]
@eyberg I think the instance checking make sense because instances are being checked against the map which contains images that exists. However, the deletion process is based on the arguments and not the mapped images, so this is the flawed part I think. 

What is the expected behavior for multiple image deletion if one of request image is not exist ? should we stop entirely or continue with existing images and put error message about the non-existing ones ?

**Comment by arknable** [comment]
After some discussion the issue is an image in gcp cannot be deleted and no instance associated with that image. But I'm having problem reproducing this, the image was successfully deleted

```
arknable@arknable-x1c:~/.../hello$ ops image delete testian -c config.json -t gcp
googleapi: Error 403: Required 'compute.instances.list' permission for 'projects/nanovms-ops', forbidden
arknable@arknable-x1c:~/.../hello$ ops image delete testian -c config-ops.json -t gcp
You are about to delete the next images:
testian
Are you sure? (yes/no)
yes
.....
Operation operation-1625107842066-5c606e7a5e86c-a0ed3373-fcee850e completed successfully.
Image deletion succeeded testian.
arknable@arknable-x1c:~/.../hello$ ops image list -c config-ops.json -t gcp | grep testian
arknable@arknable-x1c:~/.../hello$
```

I also tried with new image and still deleted
```
arknable@arknable-x1c:~/.../hello$ ops image create hello -c config-ops.json -t gcp
 100% |████████████████████████████████████████|  [0s:0s]
Image creation started. Monitoring operation operation-1625108324913-5c607046d8faa-8b9b45bc-ed4389a6.
................
Operation operation-1625108324913-5c607046d8faa-8b9b45bc-ed4389a6 completed successfully.
Image creation succeeded hello.
gcp image 'hello' created...
arknable@arknable-x1c:~/.../hello$ ops image list -c config-ops.json -t gcp | grep hello
| hello                      | READY  | 1 minute ago |
arknable@arknable-x1c:~/.../hello$ ops image delete hello -c config-ops.json -t gcp
You are about to delete the next images:
hello
Are you sure? (yes/no)
yes
..
Operation operation-1625108408731-5c607096c8866-7dc344ff-7b374149 completed successfully.
Image deletion succeeded hello.
arknable@arknable-x1c:~/.../hello$ ops image list -c config-ops.json -t gcp | grep hello
arknable@arknable-x1c:~/.../hello$ 
```

**Comment by eyberg** [comment]
I think instead of checking imgPath it should comapre to imgName as there is no path for cloud images

https://github.com/nanovms/ops/blob/master/cmd/cmd_image.go#L213-L227
