### ISSUE TITLE
Generate a package from a Docker image

### ISSUE THREAD

**Issue by quantumsheep** [nanovms/ops#1111]
When generating packages for `ops`, I realized that to fetch executables and their shared libraries I was depending on Docker images a lot, using `ldd` to retrieve shared libraries and then copying the files out of the container.

This use case led to the current idea - automating the fetching process of those executables and their shared libraries from Docker images.

Here's an example:
```bash
$ ops pkg from-docker node:16.3.0-alpine
```
Because we didn't give the wanted executable, we can look at the `CMD` Docker instruction inside the image's `Dockerfile`.

If there isn't `CMD` instruction or the user want to get another executable than the one used in `CMD` we could do something like that:
```bash
$ ops pkg from-docker node:16.3.0-alpine -f /usr/local/bin/node
```

The result would be a generated package (we can think of a `--name` option and more).

If this idea is accepted I would like to make it.

**Comment by eyberg** [comment]
ppl have asked about this from time to time and I think looking at the cmd or passing in the name is fine; one of the differences that docker brings over what we are doing with manually created packages right now is that it provides a default filesystem which can be heavier-weight but but if the tradoff is that people don't have to guess/enumerate on what they need to include I think that's fine

**Comment by rrs45** [comment]
Getting the shared libraries with the right versions has been a pain point
for me. For example, libc.so and libm.so require specific glibc versions
which may not be available on the host OS. I had to build different glibc
versions from source to generate the right libs, same case with libffi. All
open source products have an official docker image which can be used to
build ops packages, providing consistent build experience. This would be
very helpful, thanks
