### ISSUE TITLE
pkg from-docker could use an option to cp the entire fs vs just the program in question and it's linked libs

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1116]
i kinda like the way it works now but typically many programs will have other files that are necessary in order to function like config files and such

maybe just have a switch to cp the fs into sysroot

**Comment by quantumsheep** [comment]
I though of a `--copy`/`-c` option, there are cases where I wanted to to that as well.

**Comment by girishramnani** [comment]
We can introduce the `-c` `--copy` option like mentioned by @quantumsheep and have a extra optional argument to configure the max depth of folders to copy which can be `2` level as defaults?

**Comment by eyberg** [comment]
i don't see a need for specifying the tree depth to copy; I think the default case is that people will want everything; it is just you can get by with very little by copying only the program; i'd maybe just add the copy for now and then we can play with it and change it later if need

**Comment by girishramnani** [comment]
so basically `--copy` will take a directory as an input? 
example - `ops pkg from-docker node:16.3.0 -f node -c ./` or should it also work when someone provides just a file like
`ops pkg from-docker node:16.3.0 -f node -c package.json` @eyberg ?

**Comment by eyberg** [comment]
no, no input.

right now using the node example it simply grabs the node binary and the libraries linked to it and that's it; this works for a lot of programs, however, there is typically quite a lot of other stuff in the docker image though (could be config files, locales, etc.) so the proposed copy should just export the entire docker image into the unikernel output

**Comment by girishramnani** [comment]
oh ok makes sense
So I should export the whole fs of the docker image to the unikernel? or just the working directory of the docker image @eyberg ?

**Comment by girishramnani** [comment]
seems like copying the whole fs is the way to go as per the issue description

**Comment by girishramnani** [comment]
Working on this task

**Comment by eyberg** [comment]
whole fs
