### ISSUE TITLE
user should be able to still forcibly delete images that are being used by instances

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1118]
some people want to keep the same image name when provisioning a new deploy

this doesn't really account for rollbacks but I think we should still allow for users to forcibly delete images that are being used - in all cases but locally, the instance itself doesn't care if the original image is there or not

i think this behavior changed with ->

https://github.com/nanovms/ops/pull/1057

for now maybe just put on a '--force' tag to skip the in-use check?

**Comment by arknable** [comment]
@eyberg agree, `force` tag should be enough

**Comment by eyberg** [comment]
idk if this was fixed or not but I just did this on a live instance and seems to not be a problem anymore at least for the image I tried
