### ISSUE TITLE
Enabled ENA for ami

### ISSUE THREAD

**Issue by kalyanGK1** [nanovms/ops#1124]
Hello folks,

Is anyone know, how to Enabled ENA for ami which is created by ops (cmd tool for nanovms).
for instance ena is enabled but for ami not enabled.

cmd:-

ops instance create server -c config.json -t aws -z ap-south-1 -i server-image --port 8080 --flavor t3.medium

 
Error:-

Could not create instance
%!(EXTRA *awserr.requestError=InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 't3.medium' instance type. Ensure that you are using an AMI that is enabled for ENA.
        status code: 400, request id: ffdb9e82-3f23-49e5-91bf-b5914c98d028)InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 't3.medium' instance type. Ensure that you are using an AMI that is enabled for ENA.
        status code: 400, request id: ffdb9e82-3f23-49e5-91bf-b5914c98d028

**Comment by francescolavra** [comment]
Ops creates an AMI with ENA support enabled when the machine flavor passed to the `ops image create` command is among the instance types that have an Elastic Network Adapter.
Most likely you specified a flavor without ENA (or didn't specify a flavor at all) in the `ops image create` command, and that causes the AMI to miss ENA support. You would have to re-create the image by specifying an ENA-enabled flavor (such as e.g. t3.medium), and then create an instance from that image.

**Comment by kalyanGK1** [comment]
Hi @francescolavra , How to specify instance type while creating an image ?

Allowed Options:-

Flags:
  -a, --args stringArray       command line arguments
  -e, --envs stringArray       env arguments
      --gateway string         network gateway
  -h, --help                   help for create
  -i, --imagename string       image name
      --ip-address string      static ip address
      --ipv6-address string    static ipv6 address
  -l, --local                  load local package
      --mounts stringArray     mount <volume_id:mount_path>
      --nanos-version string   uses nanos tools version
      --netmask string         network mask
  -n, --nightly                nightly build
      --package string         ops package name
  -r, --target-root string     target root
      --type string            image type (target platform-specific)

Global Flags:
  -c, --config string         ops config file
  -g, --projectid string      project-id for GCP or set env GOOGLE_CLOUD_PROJECT
      --show-debug            display debug messages
      --show-errors           display error messages
      --show-warnings         display warning messages
  -t, --target-cloud string   cloud platform [gcp, aws, onprem, vultr, vsphere, azure, openstack, upcloud, hyper-v, oci, vbox] (default "onprem")
  -z, --zone string           zone name for GCP or set env GOOGLE_CLOUD_ZONE

**Comment by francescolavra** [comment]
I thought the `--flavor` flag could be used in the `ops image create` command as well, but now I see this is not the case. In order to specify the instance type you have to use the "Flavor" JSON attribute in the config.json file, as exemplified in the documentation at https://nanovms.gitbook.io/ops/configuration#cloudconfig.flavor (the doc refers to the use case of creating an instance, but for some cloud providers such as AWS this attribute is relevant also when creating an image).

**Comment by kalyanGK1** [comment]
Hey @francescolavra , Its working fine🎈🎉
Now I'm able to launch instance on aws but not able serve the index page😕

**Comment by eyberg** [comment]
@kalyanGK1 - can you show your logs for the instance? (redact anything sensitive) - also, are the correct ports open? - by default ops doesn't open any ports unless specified https://nanovms.gitbook.io/ops/configuration#runconfig.ports - but when specified there it'll create the necessary rules

**Comment by kalyanGK1** [comment]
Hi @eyberg, As per my observation By default it is listening on port 80 which is a default port.

where i can specify the "RunConfig" inside the config.json or different json file?

Note: i'm providing the port while running the cmd to create an instance 

cmd:- ops instance create from-ops-instance1 -c config.json -t aws -z ap-south-1 -i server-image --port 8081
Instance log output:-

root@ip-10-47-4-41:/home/ubuntu/nanovms-testing# ops instance logs from-ops-instance1 -t aws -z ap-south-1
kvm_detect error: found signature but unrecognized features cpuid 0x40000010; check KVM version?en1: assigned 172.31.32.140
2021/07/27 04:56:46 Listening...on 80
en1: assigned FE80::435:20FF:FEEC:D21A

**Comment by francescolavra** [comment]
Yes, the RunConfig options can be specified in the config.json file. Alternatively, for specifying a port to be accessible from outside the instance, you can use `--port` in the ops command line, as you are already doing. But in your command line I see `--port 8081`, while your server listens on port 80. You should use `--port 80` instead.

**Comment by kalyanGK1** [comment]
Hi @francescolavra , can you share sample config file with RunConfig options

My config file giving below error

error:-

Error: failed converting configuration file: json: unknown field "RunConfig"

My config file:-

{
    "Dirs" : ["static"],
    "CloudConfig" :{
        "ProjectID" :"prod-project",
        "Zone": "ap-south-1",
        "BucketName":"s3://mytestbucket",
        "Flavor": "t3.medium",
        "Platform": "aws",
        "VPC": "vpc-b8548bd1",
        "RunConfig": {
        "Ports": [80, 8006]
        },
        "SecurityGroup": "sg-1589567a",
        "Subnet": "subnet-1c4a0974",
        "Tags": [
            {
                "key": "Instance Owner",
                "value": "kalyan.g@xyz.com"
            },
            {
                "key": "Function",
                "value": "DevOps"
            },
            {
                "key": "Name",
                "value": "from-ops-instance1"
            }
        ]
    },
    "RebootOnExit": true
}

**Comment by eyberg** [comment]
@kalyanGK1 - the RunConfig should live outside of CloudConfig ->

https://nanovms.gitbook.io/ops/configuration#runconfig.ports

```
{
	"Dirs": ["static"],
        "RunConfig": {
			"Ports": [80, 8006]
        },	
	"CloudConfig": {
		"ProjectID": "prod-project",
		"Zone": "ap-south-1",
		"BucketName": "s3://mytestbucket",
		"Flavor": "t3.medium",
		"Platform": "aws",
		"VPC": "vpc-b8548bd1",
		"SecurityGroup": "sg-1589567a",
		"Subnet": "subnet-1c4a0974",
		"Tags": [{
				"key": "Instance Owner",
				"value": "kalyan.g@xyz.com"
			},
			{
				"key": "Function",
				"value": "DevOps"
			},
			{
				"key": "Name",
				"value": "from-ops-instance1"
			}
		]
	},
	"RebootOnExit": true
}
```

**Comment by kalyanGK1** [comment]
Hi @eyberg, still it is serving to default port 80

any idea how to access my index page with different port instead of 80.

From the above config file i'm able to create image as well as instance but the problem is port.

one more thing i observed is if i create 2 instance with same name ops will able to launch but it is not able to delete two instances (it is deleting first launched instance & i manually deleting second one).

cmd i'm using will provide u below 

cmd:- 

ops instance create from-ops-instance2 -c config.json -t aws -z ap-south-1 -i server-image -p 8006

&

ops instance create from-ops-instance2 -c config.json -t aws -z ap-south-1 -i server-image

**Comment by eyberg** [comment]
are you saying it works for you on port 80 but not port 8006? can you paste your application code if it's small enough? can you verify that the security group rules are correct?

**Comment by kalyanGK1** [comment]
Yes @eyberg , even if i provide different port lets say 8081 or 8006 its still serveing on 80🤦‍♂️

I terminated the instances for now but still its showing the logs 😕

log output:-

root@ip-10-47-4-4:/home/ubuntu/nanovms-testing# ops instance logs from-ops-instance2 -t aws -z ap-south-1
kvm_detect error: found signature but unrecognized features cpuid 0x40000010; check KVM version?en1: assigned 10.47.3.67
2021/07/27 14:54:26 Listening...on 80
en1: assigned FE80::95:4DFF:FEBF:7912
kvm_detect error: found signature but unrecognized features cpuid 0x40000010; check KVM version?en1: assigned 10.47.3.67
2021/07/27 14:55:51 Listening...on 80
en1: assigned FE80::95:4DFF:FEBF:7912
root@ip-10-47-4-4:/home/ubuntu/nanovms-testing#

**Comment by eyberg** [comment]
can you paste your relevant application code? it sounds like your app itself is only listening on 80, you'll need it to refactor it to listen on a different port instead - ops will merely open the ports in the sg but you still need to bind in your app

**Comment by kalyanGK1** [comment]
Hi @eyberg , very sorry for delayed in response 😊

Note: if i change the port from 80 to any other i'm enable to access my website (i.e index.html)


please find my .go file


package main

import (
    "log"
    "net/http"
)

func main() {
    fs := http.FileServer(http.Dir("static"))
    http.Handle("/", fs)

    log.Println("Listening...on 80")
    http.ListenAndServe(":80", nil)
}

**Comment by francescolavra** [comment]
The port you supply to the `ops instance create` command via the `-p` flag (or via config.json) must be the same as the port the application you put in the `ops image create` command is listening on. If there is a mismatch between the two, it's normal that you can't access your website.
Since you seem to have created multiple images and instances (some of which perhaps with the same name), I would double-check that the port used by your image (in the Go file) is the same as the port opened in your instance (via the `-p` flag).

**Comment by kalyanGK1** [comment]
Hey @eyberg , @francescolavra you guys are amazing thanks for your help to resolve my issue.👏

Now i'm able to access my application with different port other than 80.

How s3 is comes into the picture here, as i can see the bucket is empty even after the image and instance created.

Note: sorry for asking multiple issues/questions in single issue.😶

**Comment by francescolavra** [comment]
In the current version of ops, the S3 bucket is not used for image and instance creation, it's only used for volume management (see https://nanovms.gitbook.io/ops/volumes).

**Comment by kalyanGK1** [comment]
Thanks @francescolavra , will check.
