### ISSUE TITLE
Keep documentation up to speed

### ISSUE THREAD

**Issue by rrs45** [nanovms/ops#1126]
Lot of config options are TODO for a while :) . None of the nightly build features like sysconfig and cloud configs are documented except in the PR's themselves. For someone starting new, it is confusing to find the right documentation. Please keep the documentation up to speed. Thanks!

**Comment by francescolavra** [comment]
Features and configuration options for klibs (including sysconfig and cloud_init) are documented at https://nanovms.gitbook.io/ops/klibs.
Source code for the documentation is hosted at https://github.com/nanovms/ops-documentation/, and PRs are welcome there if anyone wants to improve the docs.

**Comment by rrs45** [comment]
Thanks, i should've checked klibs section :) Will submit PR's for others.
