### ISSUE TITLE
Ports issues

### ISSUE THREAD

**Issue by imarsman** [nanovms/ops#1140]
I am working on a test instance locally and in GCP. The base of the test Go application is a small HTTP server. On Ops I can run locally and on GCP using the HTTP port. I have tried NATS as well using a server started in the application. It uses port 4222 but clients I believe set up random ports when doing message passing within the application. I am getting problems with NATS when running under ops but not as a compiled standalone app. I think my issue is with ports not being allowed. How would I allow arbitrary connections to localhost ports for a running instance under ops/nanos?

**Comment by eyberg** [comment]
@imarsman , sounds like there might be two questions here?

1) for opening ports on GCP:

are you passing in ports to the RunConfig when doing an 'instance create' on GCP?

https://nanovms.gitbook.io/ops/configuration#runconfig.ports

can you confirm the firewall rules are being created correctly for the instance for 4222?

2) if running locally and you aren't getting anything are you using the gnats package or are you embedding? you'll want to ensure that you are binding to the any-interface - if it is showing as 127.0.0.1 it won't work since it is inside it's own vm

```
 ops pkg load -p 4222 gnatsd_1.4.1
booting /Users/eyberg/.ops/images/gnatsd ...
en1: assigned 10.0.2.15
[2] 2021/08/05 17:22:36.166969 [INF] Starting nats-server version 1.4.1
[2] 2021/08/05 17:22:36.168447 [INF] Git commit [not set]
[2] 2021/08/05 17:22:36.170403 [INF] Listening for client connections on 0.0.0.0:4222
```

you can test w/telnet to confirm:

```
telnet 127.0.0.1 4222
```

**Comment by imarsman** [comment]
I apologize for asking about things that are likely not software problems but rather my network knowledge. I did try gnats and got 

telnet 127.0.0.1 4222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"TBfIE6FKBTKLBmLaxDne3A","version":"1.4.1","proto":1,"go":"go1.11.5","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":1}

When running my application usng port 4222 as an application (without ops) I get

telnet 0.0.0.0 4222
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
INFO {"server_id":"NBY57UFO7QM5OE4BCK3ZJDJFCNL2NHRKOY5FCD5WICP4AVSQXWQYDOBG","server_name":"NBY57UFO7QM5OE4BCK3ZJDJFCNL2NHRKOY5FCD5WICP4AVSQXWQYDOBG","version":"2.3.3","proto":1,"go":"go1.16.4","host":"0.0.0.0","port":4222,"headers":true,"max_payload":1048576,"client_id":3,"client_ip":"127.0.0.1"}

When running under ops I get

telnet 127.0.0.1 4222
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"NAKB2KJSPTFYLWQASZEPKES3CPY2R7G5ALKPX4GX2SJBBQE33Q2J7JQ6","server_name":"NAKB2KJSPTFYLWQASZEPKES3CPY2R7G5ALKPX4GX2SJBBQE33Q2J7JQ6","version":"2.3.3","proto":1,"go":"go1.16.4","host":"0.0.0.0","port":4222,"headers":true,"max_payload":1048576,"client_id":4,"client_ip":"10.0.2.2"}

I am assuming that setting the port to be open in the config is important. However, client connections are also opened in code in the applications and they use a random port number. 

I don't want to waste your time if this is a matter of me needing to fix how I handle networking. However, if a client connection port is being blocked by ops (since it is randomly selected) then that might be an issue.




telnet 0.0.0.0 4222
Trying 0.0.0.0...
Connected to 0.0.0.0.
Escape character is '^]'.
Connection closed by foreign host.

**Comment by imarsman** [comment]
Give me a bit of time to do some more checking. I don't want to waste your time.

**Comment by imarsman** [comment]
Not enough information available to follow up
