### ISSUE TITLE
Symlink in config to be resolved

### ISSUE THREAD

**Issue by am11** [nanovms/ops#1161]
Suppose we have this symlink chain:

```sh
libfoo.so -> libfoo.so.1 -> libfoo.so.1.2.3
# or
libfoo.so -> libfoo.so.1.2.3
libfoo.so.1 -> libfoo.so.1.2.3
```

libfoo.so.1.2.3 is the actual binary.

Currently, we need to figure out:
1. which exact file the app or its dependency is probing
2. if the file is symlink, then add all files in the symlink chain (until the actual binary)

It would be nice if the symlinks are followed and packaged automatically (with a diagnostic message on stdout "implicitly adding  x -> y"), so instead of:

```json
{
  "Files": [
    "/lib/x86_64-linux-gnu/libfoo.so.1.2.3",
    "/lib/x86_64-linux-gnu/libfoo.so.1",
    "/lib/x86_64-linux-gnu/libfoo.so",
```

we just do:

```json
{
  "Files": [
    "/lib/x86_64-linux-gnu/libfoo.so",
```

If there is downside, it can be made optional.

**Comment by eyberg** [comment]
hrm, right now I believe what happens is that the symlink *is* followed and while the name is kept the same as the symlink the lib that gets copied over is the actual target

for example w/libc in this example ->

```
eyberg@box:~/x$ ldd main
        linux-vdso.so.1 (0x00007ffd7ee15000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd12680b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd126a13000)
eyberg@box:~/x$ ls -lh /lib/x86_64-linux-gnu/libc.so.6
lrwxrwxrwx 1 root root 12 Sep 15  2020 /lib/x86_64-linux-gnu/libc.so.6 -> libc-2.32.so
eyberg@box:~/x$ ops run main
booting /home/eyberg/.ops/images/main.img ...
en1: assigned 10.0.2.15
yoexit status 1
eyberg@box:~/x$ ~/.ops/0.1.36/dump -t ~/.ops/images/main.img
detected filesystem at 0xc0f600                                                                                                                                                                             Label:
UUID: 4ef4f570-9281-61bf-eeb2-ca55dcd64d1c
/
|   proc
|   |   self
|   |   |   exe -> /main
|   |   sys
|   |   |   kernel
|   |   |   |   hostname
|   etc
|   |   passwd
|   |   ssl
|   |   |   certs
|   |   |   |   ca-certificates.crt
|   |   resolv.conf
|   lib
|   |   x86_64-linux-gnu
|   |   |   libnss_dns.so.2
|   |   |   libc.so.6
|   main
|   lib64
|   |   ld-linux-x86-64.so.2
eyberg@box:~/x$ ops image cp main lib/x86_64-linux-gnu/libc.so.6 .
eyberg@box:~/x$ file libc.so.6
libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7ec3e74da842ca3c6a9ba20b21303ce1bc7a45af, for GNU/Linux 3.2.0, stripped
```

i don't see any problem with what you are proposing but are you running into an issue of some kind?

**Comment by am11** [comment]
> I believe what happens is that the symlink _is_ followed

Ah, that's great! I didn't knew.

> `ldd main`

Yup, but when the app or one of its dependency is `dlopen`'ing a library at runtime, it gets trickier to figure out exact file it is looking for.

> i don't see any problem with what you are proposing but are you running into an issue of some kind?

I was mainly looking to minimize user-facing config size. When writing the [.NET example](https://github.com/nanovms/ops-examples/blob/4a32244b75c48830782afec54c5d434302237a3d/dotnet/config.json), I noticed that we have to explicitly specify variants for libnuma (which is optional dependency unless someone _really_ want numa-related features). To minimize the list, I proposed this change upstream: https://github.com/dotnet/runtime/pull/48133, which was frowned upon at the time but change was accepted. Lately, it came up again in: https://github.com/dotnet/runtime/pull/59526. @janvorli hashed it out the general preference here: https://github.com/dotnet/runtime/pull/59526#discussion_r714889517.

The idea for runtime is to not tie to the "final version" of a few "soft dependencies" -- libs which are either optional (like krb5 and numa) or the ones which support multiple versions (like ssl) -- but only to their minor version (which in case of libc.so.6 is the binary but in case of numa/krb5 etc. is still the symlink to the file with full symver).

Therefore, it would be nice if ops make the experience better by keeping the symlink chain for scenarios where visibility about "which file is exactly being probe" is unclear.

ps - even better if `ops pkg list` enlists .NET as a supported stack in nanos unikernel. 🙂

**Comment by eyberg** [comment]
I don't see an easy way for us to know in advance what lib an application is going to open at run-time so if it's not in the ldd output than the application needs to be told about it's existence

having said that we do have a 'missing-files' flag you can pass to 'ops run' which will print a list of items it finds that might need to be added to your config - for example following yours ->

```
ops run --missing-files -c config.json publish/myApp
...
booting /home/eyberg/.ops/images/myApp.img ...
en1: assigned 10.0.2.15
Hello World!
en1: assigned FE80::D020:E6FF:FEBD:3C3C
missing_files_begin
liblttng-ust.so.0
liblttng-ust-tracepoint.so.0
mountinfo
libicuuc.so.50
libicuuc.so.70
libicuuc.so.69
libicuuc.so.68
missing_files_end
exit status 1
```

one thing to note is that nanos && ops are version agnostic - we don't have one official library version/release or anything - it's totally up to your application/build env so while it is totally feasible to have a package built for .NET different users might need different builds of it depending on their application, if you want to take a stab at building an application for a particular environment I'm happy to put it into the official repository though

the big difference than this vs something like the JVM runtime is that the JVM is packaged separately from the jar that you might load whereas in this scenario the runtime is packaged with your dlls so it might not be as easy to re-use on different systems

**Comment by am11** [comment]
Thanks! `--missing-files` is a great option. The `libicuuc.so*` are just probing points, which globalization shim in runtime uses it doesn't break the app.

The scope of this issue is: for example, I know (by means of strace or the documentation or some stackoverflow post etc.) that what file the app is looking for `libnuma.so.1` at runtime, so I listed it in my `config.json`. Now I expect `ops <command> -c config.json` to consider adding both `libnuma.so.1` and (since `libnuma.so.1` is a symlink) also `libnuma.so.1.0.0` the real binary.

> if you want to take a stab at building an ops package for a particular environment I'm happy to put it into the official repository though

I need some cycles to digest the code to see how we can manage it, but sure will give it a crack. :)

> the big difference than this vs something like the JVM runtime is that the JVM is packaged separately from the jar that you might load whereas in this scenario the runtime is packaged with your dlls so it might not be as easy to re-use on different systems

Traditionally .NET Framework has worked that way. Today, .NET provides multiple deployment models: https://docs.microsoft.com/en-us/dotnet/core/deploying/. TL;DR, for `ops pkg`, I was thinking framework dependent deployment (FDD) which is similar to what JVM does. So essentially we ask user to just either:

* bring your .NET assembly (managed DLL files) and the environment will provide shared framework + runtime to execute it
  * slim code package, slim nanos environment
* OR bring your code (a .cs, .vb, .fs files) and environment will provide SDK + shared framework + runtime to compile and execute it.
  * slimmest cod package, fatter nanos environment (since SDK is bigger, not terribly, but still; some 300MBs...)

Aside from that, there are also these options:

* self-contained option: which doesn't require shared framework and runtime but package it with the app (lots of file in your 'publish' directory)
  * one huge package folder,  nothing .NET-y in the nanos environment
* single-file deployment: which bundles everything (.NET assemblies / compiled code +  runtime + dependencies) in one file (native executable) and at runtimes essentially uses mmap to find regions of stuff it needs to load (and sometimes partially extract stuff to /var/tmp etc. which can't be read from memory)
  * one huge file, nothing .NET-y in the nanos environment 
  * this one is also mentioned in ops-example

**Comment by eyberg** [comment]
i don't see any downsides to adding the symlinks but are you actually running into an issue as ops resolves the symlinks when it's adding them to the actual shared library

as for your second question regarding packaging - if you are wanting to compile something you'll want to look at utilizing the cross-building environment: https://nanovms.gitbook.io/ops/crossbuilding && https://nanovms.com/dev/tutorials/crossbuilding-unikernels-on-mac-without-vagrant-or-docker as nanos has no capability for executing other programs inside

**Comment by am11** [comment]
> are you actually running into an issue as ops resolves the symlinks when it's adding them to the actual shared library

With master branch, I don't see symlinks specified in config.json are being resolved? From the ops-example (https://github.com/nanovms/ops-examples/blob/4a32244b/dotnet/config.json) I changed `Program.cs` to:

```c#
using System;
using System.IO;

Console.WriteLine("Listing all files in nanos environment:");
foreach (string file in Directory.EnumerateFiles("/", "*.*", SearchOption.AllDirectories))
{
    Console.WriteLine(file);
}
```

This is what I get:
```
Listing all files in nanos environment:
/dev/null
/dev/urandom
/etc/passwd
/etc/resolv.conf
/etc/ssl/certs/ca-certificates.crt
/lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/libcom_err.so.2
/lib/x86_64-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
/lib/x86_64-linux-gnu/libk5crypto.so.3
/lib/x86_64-linux-gnu/libkeyutils.so.1
/lib/x86_64-linux-gnu/libkrb5.so.3
/lib/x86_64-linux-gnu/libkrb5support.so.0
/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libnss_dns.so.2
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libresolv.so.2
/lib/x86_64-linux-gnu/librt.so.1
/lib/x86_64-linux-gnu/libstdc++.so.6
/lib/x86_64-linux-gnu/libz.so.1
/lib64/ld-linux-x86-64.so.2
/myApp
/myApp.pdb
/proc/self/exe
/proc/self/maps
/proc/sys/kernel/hostname
/publish/myApp
/publish/myApp.pdb
/sys/devices/system/cpu/online
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
/usr/lib/x86_64-linux-gnu/libicudata.so.66
/usr/lib/x86_64-linux-gnu/libicui18n.so.66
/usr/lib/x86_64-linux-gnu/libicuuc.so.66
/usr/lib/x86_64-linux-gnu/libnuma.so.1
/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

Notice that both `libnuma.so.1` and `libnuma.so.1.0.0` are in config.json, and that's why they are present on the sandbox filesystem.

Also, I just realized that we added `librt.so.1` in config.json (which is a symlink) but missed the actual binary `librt-2.31.so`, so it is missing in the sandbox environment too.

Clearly, symlinks resolution of any kind is not working in this case (at least).

**Comment by francescolavra** [comment]
@am11 symlinks are being resolved, otherwise your .NET program wouldn't start at all when run on Nanos. For example, the /lib/x86_64-linux-gnu/librt.so.1 that's in your file list has the contents of the librt-2.31.so in your computer (i.e. in the Nanos image it's not a symlink but an actual file), that means ops resolved the librt.so.1 symlink to the librt-2.31.so file. And that's all programs usually need when loading dynamic libraries.
Also for the numa library, you can specify just libnuma.so.1.0 in the config.json file (specifying also libnuma.so.1.0.0 is not necessary), and it should work just fine, because ops when creating the Nanos image resolves the libnuma.so.1.0 symlink in your computer to the libnuma.so.1.0.0 file, and puts the contents of that file under the libnuma.so.1.0 name.

**Comment by am11** [comment]
@francescolavra, ah you are right, it is working as you have described and exactly what I was expecting out of this request. :)
For some reason I forgot to check the file sizes. :/

```diff
- Console.WriteLine(file);
+ Console.WriteLine("{0}: {1}", file, new System.IO.FileInfo(file).Length);
```

This issue is resolved. I will revert numa change I made in runtime as it's not necessary (should have opened this issue earlier .. 🤦‍♂️).
