### ISSUE TITLE
Problems with deployment to Digital Ocean

### ISSUE THREAD

**Issue by ynigun** [nanovms/ops#1166]
When I run `ops image create main -t do -c config.json`
i get the response:
```
POST https://api.digitalocean.com/v2/images: 400 {"id":"bad_request","message":"Your source URL is unreachable"}
{"image":{"created_at":"2021-10-02T21:12:24Z","description":"","distribution":"Unknown OS","error_message":"","id":92863202,"name":"main.img","regions":[],"status":"NEW","tags":["createdBy:ops"],"type":"custom","updated_at":"2021-10-02T21:12:24Z"}}
```

this is probably because the URL is private and not public.
so I downloaded and uploaded the file and added the tag `createdBy:ops`  manually.

Now when I run `ops instance create main.img -t do -c config.json`
I get the response:
```
POST https://api.digitalocean.com/v2/droplets: 422 02:14:c3:d2:cd:4a:67:8b:43:b3:49:83:99:49:6a:58 are invalid key identifiers for Droplet creation.
```

This is probably because of this variable:
https://github.com/nanovms/ops/blob/ba1f27f762efd31684e6170a3bb197ffd0bc9054/digitalocean/digital_ocean_instance.go#L16

Instead of changing it and recompiling ops
I created a droplet (a DO instance) from the DO control panel.

I compiled this code:
```
package main

import (
    "fmt"
    "log"
    "net/http"
)

func main() {

    http.HandleFunc("/", HelloHandler)
    fmt.Println("Server started at port 8080")
    log.Fatal(http.ListenAndServe("0.0.0.0:8080", nil))
}

func HelloHandler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, there\n")
}
```
So it's supposed to listen on port 8080 ,but I can not access it even from a VM that is in the same region
```
root@ubuntu-s-1vcpu-1gb-fra1-01:~# curl http://164.90.208.52:8080/
curl: (28) Failed to connect to 164.90.208.52 port 8080: Connection timed out
root@ubuntu-s-1vcpu-1gb-fra1-01:~# curl http://10.114.0.4:8080/
curl: (7) Failed to connect to 10.114.0.4 port 8080: No route to host
```
When I open the console there is a lot of output,I do not know if it's errors or something else.

**Comment by eyberg** [comment]
there are two issues here:

1) image upload was at least at one point a manual process - i don't know if that changed or not: https://github.com/nanovms/ops/issues/468 seems to suggest that it was set to use spaces but i had to manually upload the image as well

2) there is a recursive crash going on - this should be relatively straight-forward to fix 

the fake fingerprint notice shouldn't be an issue

**Comment by eyberg** [comment]
not sure what the status/situation with the old issue of image upload - it doesn't seem to like raw format but changing it to qcow2 seems to upload it fine - https://github.com/nanovms/ops/pull/1167

**Comment by sanderssj** [comment]
We've added some new drivers relatively recently and since Digital Ocean's vms can use the new drivers as well as have multiple NICs, we ran into an artificial limit of the number of interrupts we could allocate, causing a crash. The change nanovms/nanos#1592 lets nanos use the maximum number of interrupt vectors on x86. This change is now in master if you build nanos from scratch and will be available with the nightly flag in ops tomorrow. See if that resolves your crash issue.

**Comment by angristan** [comment]
Still having the issue as of ops 0.1.27:

```
devenv :: ~/lab » ops image create boringtun/target/release/boringtun -c config.json -t do                              1 ↵
 100% |████████████████████████████████████████|  [0s:0s]
POST https://api.digitalocean.com/v2/images: 400 {"id":"bad_request","message":"Your source URL is unreachable"}
{"image":{"created_at":"2021-11-14T21:22:48Z","description":"","distribution":"Unknown OS","error_message":"","id":95737254,"name":"boringtun.img","regions":[],"status":"NEW","tags":["createdBy:ops"],"type":"custom","updated_at":"2021-11-14T21:22:48Z"}}
```

**Comment by angristan** [comment]
After fixing ^ still having the fingerprint issue:

```
» ops instance create boringtun.img -t do -z ams3
POST https://api.digitalocean.com/v2/droplets: 422 02:14:c3:d2:cd:4a:67:8b:43:b3:49:83:99:49:6a:58 are invalid key identifiers for Droplet creation.
```
