### ISSUE TITLE
Bridge IP is hard coded to IP .66

### ISSUE THREAD

**Issue by andys** [nanovms/ops#1171]
https://github.com/nanovms/ops/blob/882d741c6db5ea41e99d1801adc31dea7790153f/network/setup_network_interfaces.go#L56

This should become an option, not hardcoded

**Comment by eyberg** [comment]
ties into https://github.com/nanovms/ops/issues/174

**Comment by eyberg** [comment]
adding this for now as it was brought up elsewhere again, it's probably time to and worth adding support for managing subnets in a wholly diff. command and then this would be obviated
