### ISSUE TITLE
Able to run locally, but not on AWS

### ISSUE THREAD

**Issue by joshuaquek** [nanovms/ops#1172]
Here is my code repo. Its a simple NodeJS server - https://github.com/joshuaquek/expressjs-ops-unikernel

I am able to run this locally on my laptop (mac) using the command:

```bash
npm install; ops pkg load node_v14.2.0 -p 80 -f -n -c config.json -a index.js
```
![image](https://user-images.githubusercontent.com/5335756/138231386-ed7efbd9-b12d-443f-9b2a-6a9b9a6a688c.png)

![image](https://user-images.githubusercontent.com/5335756/138231345-9a548a1d-f6e1-40a1-964b-0271b42d6131.png)

I have also set my config.json so that I can deploy it to AWS:

![image](https://user-images.githubusercontent.com/5335756/138231543-42009eaa-e914-4829-9b3a-4379b845ad05.png)

and by running `npm install; ops image create -t aws --imagename expressjs-ops -c config.json --package node_v14.2.0 -a index.js` it successfully deploys it as an image to AWS:

![image](https://user-images.githubusercontent.com/5335756/138231751-79a24fbd-e742-4ee5-9c6a-98414a6af077.png)

However when I try to launch an instance using the AWS web console, it just starts and runs...but I cant seem to reach it, even though its been configured to be on a public subnet and the app to be exposed on port 80:

![image](https://user-images.githubusercontent.com/5335756/138232020-48abd57f-ec52-4371-b1f7-a1f21a248597.png)

<img width="1155" alt="Screenshot 2021-10-21 at 3 33 31 PM" src="https://user-images.githubusercontent.com/5335756/138232217-996b799c-2372-4a36-a56f-9d734669f0ca.png">

Am I doing something wrong here?

**Comment by francescolavra** [comment]
@joshuaquek does it work if you launch the instance with the `ops instance create` command instead of using the AWS web console? You would need to add the following to your config.json passed to the `ops instance create` command, in order to allow TCP port 80 to be reached:
```
  "RunConfig": {
        "Ports": ["80"]
  }
```

**Comment by francescolavra** [comment]
The latest Nanos release v0.1.36 has a known issue on AWS, which has been fixed in https://github.com/nanovms/nanos/pull/1564.
You should be able to get it working if you use the nightly builds of the kernel, by adding the `-n` flag to the `ops image create` command.

**Comment by joshuaquek** [comment]
Sure, let me give that solution a shot and report back here again soon.
