### ISSUE TITLE
document min go version to build with

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1178]
go.mod says 1.12

**Comment by girishramnani** [comment]
where should this be documented? In readme.md? There is a section which already mentions Go 1.13 https://github.com/nanovms/ops/blob/master/README.md#build-and-install-from-source

**Comment by eyberg** [comment]
ah, i might've meant to put this on - https://github.com/nanovms/ops-documentation/issues - or just didn't see that in the readme https://docs.ops.city/ops/developer/source-installation
