### ISSUE TITLE
Running python's http-server on Ops

### ISSUE THREAD

**Issue by iamshreeram** [nanovms/ops#1181]
Hi, I'm trying to run a simple http-server (python) with below config.json
```
{
  "Args":["-m", "http.server"]
}
```
`>>> ops pkg load python_3.6.7 -p 8080 -c config.json`

I'm seeing below warning. But, the server is up. 
```
file "/Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so" is missing: stat /Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so: no such file or directory
file "/Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so" is missing: stat /Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so: no such file or directory
file "/Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/sitecustomize.py" is missing: stat /Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/python3.6/sitecustomize.py: no such file or directory
file "/Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/x86_64-linux-gnu/libsqlite3.so.0" is missing: stat /Users/rams/.ops/packages/python_3.6.7/sysroot/usr/lib/x86_64-linux-gnu/libsqlite3.so.0: no such file or directory
booting /Users/rams/.ops/images/python3 ...
```
When I run the same with python-3.8.6, I'm seeing below error. 

`>>> ops pkg load python_3.8.6 -p 8080 -c config.json`

Below is the stack trace -

```
booting /Users/rams/.ops/images/python3 ...
en1: assigned 10.0.2.15
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/http/server.py", line 92, in <module>
    import email.utils
  File "/usr/local/lib/python3.8/email/utils.py", line 40, in <module>
    from email.charset import Charset
  File "/usr/local/lib/python3.8/email/charset.py", line 14, in <module>
    import email.base64mime
  File "/usr/local/lib/python3.8/email/base64mime.py", line 37, in <module>
    from base64 import b64encode
  File "/usr/local/lib/python3.8/base64.py", line 11, in <module>
    import binascii
ImportError: libz.so.1: cannot open shared object file: No such file or directory
```

**Comment by eyberg** [comment]
using the 3.6.7 package on mac the example works for me - are you using sqlite by chance in your code?

i responded to that other issue here https://github.com/nanovms/ops-examples/issues/76 

you'll need libz for flask apparently, if you want we can make a flask package that has that?

**Comment by iamshreeram** [comment]
1. No. I'm not using any code. I just have a simple `index.html`, that this http-server serves. I just have below config.json
```config.json
{
  "Args":["-m", "http.server"]
}
```
and simple `index.html` that is being served by `python_3.6.7` and `python_3.8.6`. I'm seeing issue only with `python_3.8.6`.

2. Could you please share the details of adding libz and the location to put it on mac? Thanks!

**Comment by eyberg** [comment]
```
➜  ~ tree ~/.ops/packages/python_3.6.7 | grep libz
    │       └── libz.so.1
➜  ~ tree ~/.ops/packages/python_3.8.6 | grep libz
```

yeh it looks like libz is in the 3.6.7 pkg but the 3.8.6 package - we can add it there

**Comment by eyberg** [comment]
I updated the python_3.8.6 to include a few missing libs that'll make this work - if you nuke ~/.ops/packages/python_3.8.6 && ~/.ops/package/manifest.json it should work

**Comment by iamshreeram** [comment]
Thank you @eyberg , That fixed the issue. 

1. Could you please help in changing the default port? I tried to do it using `ops pkg load python_3.8.6 -p 8000 -c config.json`, but that doesn't help.
2. Could you please share the commit history for adding libs? That would help me/others, in raising the PR if any change is needed.

**Comment by eyberg** [comment]
1) using the built-in http server it's just the next argument like so:

```
➜  z ops pkg load python_3.8.6 -p 8081 -c config.json
booting /Users/eyberg/.ops/images/python3 ...
en1: assigned 10.0.2.15
Serving HTTP on :: port 8081 (http://[::]:8081/) ...
en1: assigned FE80::587D:C3FF:FEB2:8F0A
```

```
➜  z cat config.json
{
  "Args":["-m", "http.server", "8081"]
}
```

the '-p' opens up qemu or whatever cloud you are deploying to's port while the argument inside the config.json is for the python interpreter itself

2) there's no commit history as they are hand-built (mostly) right now; we have plans on opening up a hosted registry/hub so that people can upload and maintain their own packages if they want though; also it's not really expected that the vast majority of people would be crafting their own python packages - we'd like it to be as simple as apt-get
