### ISSUE TITLE
add proxmox target

### ISSUE THREAD

**Issue by dzonerzy** [nanovms/ops#1187]
As the title says, is it possible to convert the raw disk image to an ISO which can be imported on proxmox? I already know is possible to do it using raw disk image (ISO is not needed) but still wanted to experiment with a real iso

**Comment by eyberg** [comment]
afaik proxmox is going to use qemu/kvm so should be able to take the raw disk image and import it, although we don't have api integration with it yet, I don't know offhand how an iso would help as there is no 'install'; is there a reason why you wouldn't want to import via the raw disk image?

**Comment by dzonerzy** [comment]
I'm already able to import the .img file since it's a raw disk and thus can be run with kvm/qemu , anyway just wanted to know if there was an easy way to convert that img file to the CD-ROM iso format since this should be widely accepted by many hypervisor

**Comment by eyberg** [comment]
all the disk images we produce are meant to be ran as disk images and iso is inherently read-only, further we have a custom fs, TFS, if your goal is to just have easy support on any/all hypervisors we already support all the popular ones (happy to look at any we don't support), I don't know what the use-case would be for producing an iso though?

I guess it should be said that ops already inter-operates well with multiple hypervisors; locally when running we produce raw images that work w/kvm but then you can export those to run on AWS (xen) or Azure (hyper-v) or on ESX, etc. - you could also export them to run on virtualbox locally - we try to make this as seamless as possible so the end-user doesn't have to configure all the various formats

**Comment by eyberg** [comment]
if your goal is just to have better proxmox integration we most definitely could do that instead - make it be

```ops instance create -t proxmox```

I see plenty of api libraries https://pve.proxmox.com/wiki/Proxmox_VE_API  - this one suggests there is an api for creating vms: https://github.com/Saleh7/ProxmoxVE_PHP_API#create-vm 
would that work?

**Comment by dzonerzy** [comment]
Sure that would work and proxmox integration would be awesome!

**Comment by eyberg** [comment]
ok, we can look into doing that.

**Comment by eyberg** [comment]
initial support has been merged in but there are a few bits of extra work i left out of the initial merge

https://github.com/nanovms/ops/pull/1195
