### ISSUE TITLE
bug(docker): from-docker cannot use a local image

### ISSUE THREAD

**Issue by Guikingone** [nanovms/ops#1205]
Hi everyone 👋🏻 

Small question as I'm facing an issue here, I'm trying to build a package from a local docker image but it seems that this approach is not possible, here's the command that I use: 

```bash
ops pkg from-docker _local_image_ -n _package_name_ -f _executable_
```

Here's the error I'm receiving:

```bash
_DATE_ _HOUR_ Error response from daemon: pull access denied for _local_image_, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Even after using `docker login`, the error still the same.

Thanks for the help and have a great day 🙂

**Comment by eyberg** [comment]
you can get that message if it doesn't exist - for example:

```
ops pkg from-docker nats -n nats -f nats
latest: Pulling from library/nats
Digest: sha256:edfbb6f15ab27d0e8c13505b6d80cbba9b4e67d3469696d84b56cb0a2a74e60a
Status: Image is up to date for nats:latest
nats
```

works but 

```
➜  ~ ops pkg from-docker ababbaababbabbbab -n ababbabaabbaba -f abababababa
2021/12/13 13:51:06 Error response from daemon: pull access denied for ababbaababbabbbab, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

doesn't - can you verify the image you are trying to convert shows up in the image list?

```
docker image ls
```

**Comment by eyberg** [comment]
@Guikingone looks like the local was being immediately skipped - lmk if https://github.com/nanovms/ops/pull/1206 works for you

**Comment by Guikingone** [comment]
Hi @eyberg 👋🏻 

Thanks for the fast feedback, yes, #1206 works perfectly 🙂
