### ISSUE TITLE
ops fails to run on Apple Silicon

### ISSUE THREAD

**Issue by wyan** [nanovms/ops#1220]
Running macOS 12.1 on Macbook Air M1.

When trying to run the first example in the Getting Started guide I get the following error:
```
$ ops pkg load node_v14.2.0 -p 8083 -f -n -a hi.js
booting /Users/alice/.ops/images/node ...
qemu-system-x86_64: -accel hvf: invalid accelerator hvf
exit status 1
```

Is there a way to use ops on M1 CPUs?

**Comment by girishramnani** [comment]
Hardware acceleration is not available on M1 Macs - try adding `--accel=false` to this command to make it work. 
Related ticket https://github.com/nanovms/ops/issues/1210

**Comment by eyberg** [comment]
to clarify the m1s are arm basd so hardware accel will only work for arm builds which most people aren't actually going to deploy with; if you are using x86 builds on arm than you can't have accel on - https://github.com/nanovms/ops/issues/1210 should be in the nightly branch ('ops run -n') by latest tonight if not already; you can do the '--accel=false' manually for now and you won't need that once that pr rolls into nightly

**Comment by wyan** [comment]
Thanks!

**Comment by eyberg** [comment]
closing for now

**Comment by armenr** [comment]
Hey folks - This just bit me today. Had it not been for the instinct to go searching inside Git Issues, I wouldn't have known what to do, and would have abandoned the tool before ever getting a chance to try it/use it.

Could I suggest maybe adding something in the docs that says "For now, if you're on Apple Silicon, use the `--accel=false` switch".

**Comment by armenr** [comment]
```
❯ ops version
Ops version: 0.1.30
Nanos version: 0.1.38
```
