### ISSUE TITLE
Ports not being exposed 

### ISSUE THREAD

**Issue by s1ntaxe770r** [nanovms/ops#1232]
I am trying to run [this](https://github.com/s1ntaxe770r/pong-server/blob/master/main.go) binary which exposes port`8080`, but i am unable to access it on my host machine 

### System Info 
Operating system: macOS monetery 12.0 intel 
Ops version: 0.1.28
Nanos version: 0.0
Qemu version: 5.2.0
Arch: darwin
Virtualized: false

### `ps aux | grep qemu` output
```shell
jubril           38532   1.5  0.0 34123820    828 s001  S+   10:20PM   0:00.01 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox qemu
jubril           38489   0.7  0.9 37491820  76896 s000  S+   10:20PM   0:00.91 qemu-system-x86_64 -machine q35 -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x3 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x3.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x3.0x2 -device virtio-scsi-pci,bus=pci.2,addr=0x0,id=scsi0 -device scsi-hd,bus=scsi0.0,drive=hd0 -vga none -smp 1 -device isa-debug-exit -m 2G -no-reboot -cpu max,-rdtscp -drive file=/Users/jubril/.ops/images/pong.img,format=raw,if=none,id=hd0 -device virtio-net,bus=pci.3,addr=0x0,netdev=n0,mac=12:cb:18:1a:2c:b1 -netdev user,id=n0,hostfwd=tcp::8080-:8080 -display none -serial stdio
```
### Uname -a output 
```shell
Darwin Jubrils-MacBook-Air.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
```
output of  `ops run -p 8080 pong`
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/53065463/150213514-1abdf54a-4d15-4bc4-aa7b-09c1d99baaad.png">

**Comment by eyberg** [comment]
i'm not exactly sure why but this appears to be a qemu issue - the one in install.sh is 5.2 (not sure what the changes are if any that we made - need to look into that)

but if you do a simple ```brew install qemu``` you should get bumped to version 6.2.0 which at least for me gets rid of both the hvf issue (accel=false) and the port issue (which I wasn't able to repro)

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/1202

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/1247

**Comment by s1ntaxe770r** [comment]
hey @eyberg, running `brew install qemu` fixed all the issues

**Comment by eyberg** [comment]
excellent, yeh - we went ahead and bumped the qemu release to the official one which is much laster - we had tied it to 5.2 earlier last year since the old official release was at something like 2 or 3.x, going to close this
