### ISSUE TITLE
ops gets 

### ISSUE THREAD

**Issue by dpreilan** [nanovms/ops#125]
I am seeing the same error using ops that nanos saw and fixed with:
https://github.com/nanovms/nanos/issues/31

qemu-system-x86_64 --version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.9)

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

**Comment by mkhon** [comment]
@cbarraford documentation fix is not correct: the problem exists in qemu 2.11 which is >= 2.5

**Comment by mkhon** [comment]
-drive file=image,format=raw,if=none,id=drive-virtio-disk0 -device virtio-blk-pci,drive=drive-virtio-disk0

**Comment by eyberg** [comment]
@mkhon what do you think of the suggestion that we should just grab the version of qemu in ops and use one setting vs the other? that to me sounds like the better option cause ubuntu 16.04 installs 2.5 - i think brew installs 3.0 - espc. since this is different from version to version

**Comment by mkhon** [comment]
@eyberg this was initially my thinking (to differentiate on qemu version).

However I found out how KVM runs virtio with one drive (see command line above) - I think we should use this one - it works on all qemu versions.

@skupr will implement this

**Comment by mkhon** [comment]
nanos boot2 will use BIOS after nanovms/nanos#480 is merged

**Comment by eyberg** [comment]
once this is done (since it's in master nanos) we should prob. bump ops version && cut a release (or can wait until gce integration)
