### ISSUE TITLE
package is missing name field

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1257]
https://github.com/nanovms/ops/blob/master/lepton/package.go#L34

this is probably just from the legacy fact that we never really explicitly had it to begin with (just using the ProgramName from manifest) - def worth having now espc after the next build gets cut

**Comment by girish-nanovms** [comment]
what should be done here @eyberg ?

**Comment by girish-nanovms** [comment]
should we add the `name` to `package.manifest` of all packages present in pkghub

**Comment by eyberg** [comment]
I think https://github.com/nanovms/ops/commit/f7cc685704e7f92a8ac68d552fbd15b81a636214 closes this
