### ISSUE TITLE
ops image create missing arm switch

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1259]
it appears 'ops run' is intelligent enough to run (prob based on underlying arch) but need the ability to do images as well

I don't think there are any outstanding blockers to do cross-arch builds via flag (eg: x86 to arm) as native mkfs support was added to ops

**Comment by girishramnani** [comment]
should we consider adding a `--arch` flag to ops image create command?

**Comment by eyberg** [comment]
I think the default should be whatever underlying architecture the user is on currently but yeh I'd be in favor of having an arch flag; just not sure how many people would actually take advantage of that since the underlying binary still needs to be tied to the arch of choice

**Comment by olegpono** [comment]
PR #1265 auto get architecture based on "CloudConfig.Flavor"

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/1380 adds support for downloading and using arm builds for arm related targets - also allows just grabbing latest arm release
