### ISSUE TITLE
Documentation still refers to NameServer, it should be now NameServers

### ISSUE THREAD

**Issue by Littlelies** [nanovms/ops#1267]
With an array of DNS ip addresses.

**Comment by francescolavra** [comment]
We have s separate repo (https://github.com/nanovms/ops-documentation) for the documentation. The task of updating the docs for this particular feature is being tracked at https://github.com/nanovms/ops-documentation/issues/277.

**Comment by francescolavra** [comment]
Fixed by https://github.com/nanovms/ops-documentation/pull/284
