### ISSUE TITLE
Add a new flag for selecting nightly build vs release

### ISSUE THREAD

**Issue by tijoytom** [nanovms/ops#131]
The force false now serves two purpose, it use the nightly build and download the latest nightly build. There is no way update a release build

**Comment by ExternalReality** [comment]
1. When images are downloaded, if the target image already exists, ops will not download the image unless the force flag is specified (the 'force' flag allows a user to 'refesh/update' images).
2. If the force flag is used, the user is also specifying whether she want to download the `dev` image or `release` image.

Naturally, as @tijoytom states above, this leads to a situation where the path to update a `release` image cannot execute.
 
Here is code to add a new "nightly" flag which fixes the situation: https://github.com/ExternalReality/ops/commit/def6f909c925a0789eb9ff89a6b3f6bc85051b7e

**Comment by tijoytom** [comment]
@ExternalReality thanks. Can you please PR it?
