### ISSUE TITLE
Update and versioning story

### ISSUE THREAD

**Issue by tijoytom** [nanovms/ops#132]
How to update ops,nanos and packages? Pull vs Push, LTS vs Nightly
Check for updates when ops starts?

**Comment by eyberg** [comment]
yeh - just noticed that I needed to manually blow away the old packages manifest to get the new list so that should rope into whatever is planned out

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/178

**Comment by eyberg** [comment]
ops update now seems to work fine
