### ISSUE TITLE
Centos, "ho hypervisor found"

### ISSUE THREAD

**Issue by cbarraford** [nanovms/ops#133]
While setting up a centos7 box with ops, i ran into the following error. I believe i install qemu, is there another package that is required?

```
[vagrant@localhost ~]$ ops load node_v11.15.0 -a ex.js
Downloading.. /home/vagrant/.ops/bin/.packages/node_v11.15.0.tar.gz
 15.62 MiB / 15.62 MiB [==========================================] 100.00% 6.28 MiB/s 2s
Extracting /home/vagrant/.ops/bin/.packages/node_v11.15.0.tar.gz...
Downloading.. .staging/mkfs
 264.80 KiB / 264.80 KiB [========================================] 100.00% 7.46 MiB/s 0s
Downloading.. .staging/boot.img
 19.00 KiB / 19.00 KiB [==========================================] 100.00% 5.82 MiB/s 0s
Downloading.. .staging/stage3.img
 1.34 MiB / 1.34 MiB [============================================] 100.00% 6.39 MiB/s 0s
/tmp/resolv=>/etc/resolv.conf
/tmp/hostname=>/proc/sys/kernel/hostname
ex.js=>ex.js
.staging/node_v11.15.0/node=>node_v11.15.0/node
.staging/node_v11.15.0/package.manifest=>node_v11.15.0/package.manifest
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/libc.so.6=>lib/x86_64-linux-gnu/libc.so.6
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/libdl.so.2=>lib/x86_64-linux-gnu/libdl.so.2
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/libgcc_s.so.1=>lib/x86_64-linux-gnu/libgcc_s.so.1
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/libm.so.6=>lib/x86_64-linux-gnu/libm.so.6
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/libpthread.so.0=>lib/x86_64-linux-gnu/libpthread.so.0
.staging/node_v11.15.0/sysroot/lib/x86_64-linux-gnu/librt.so.1=>lib/x86_64-linux-gnu/librt.so.1
.staging/node_v11.15.0/sysroot/lib64/ld-linux-x86-64.so.2=>lib64/ld-linux-x86-64.so.2
.staging/node_v11.15.0/sysroot/usr/lib/x86_64-linux-gnu/libstdc++.so.6=>usr/lib/x86_64-linux-gnu/libstdc++.so.6
booting image ...
panic: No hypervisor found on $PATH

goroutine 1 [running]:
main.loadCommandHandler(0xc0000e1900, 0xc00008b410, 0x1, 0x3)
	/home/tijoy/go/src/github.com/nanovms/ops/ops.go:283 +0x144f
github.com/spf13/cobra.(*Command).execute(0xc0000e1900, 0xc00008b350, 0x3, 0x3, 0xc0000e1900, 0xc00008b350)
	/home/tijoy/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e1b80, 0x8, 0x0, 0xc0000e1900)
	/home/tijoy/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000e1b80, 0xc0000cff18, 0x1)
	/home/tijoy/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/tijoy/go/src/github.com/nanovms/ops/ops.go:470 +0xdaf
```

**Comment by ExternalReality** [comment]
Both the `load` command and the `run` command require that a virtualization provider be available (only `qemu`) is supported at the moment. Would it be sufficient to simply do the check before these commands two commands are run and handle appropriately (i.e. "the supported providers are... please installl...")?

**Comment by eyberg** [comment]
yeh I think that's fine although ideally this should just be done during install and then we don't have to check each time - we'd def. like the ability to have multiple virtualization options but for now if qemu is not there than it's basically worthless

**Comment by ExternalReality** [comment]
To handle this issue we: 

1. ensured that the install script installs `qemu` on CentOS (and other supported distributions)
https://github.com/nanovms/ops/pull/166
2. We moved the check up to the top of the relevant command handlers.
https://github.com/nanovms/ops/pull/171

**Comment by eyberg** [comment]
think this was fixed

**Comment by charlesmorris5** [comment]
I'm experiencing this issue on Ubuntu 20.04.
1. Installed qemu with [sudo apt install qemu] qemu version (1:4.2-3ubuntu6.1)
2. Installed ops with [curl https://ops.city/get.sh -sSfL | sh] ops version (0.1.10), nanos version (0.1.25)
Following the "getting started" guide results in "No hypervisor found on $PATH" error
I did note that my profile does not have a .bash_profile; it does have .bashrc
I also noted that additional installations of ops with curl add additional [#OPS config] entries in .bashrc; it looks like it's trying to update the path in the correct file for Ubuntu 20.20.
