### ISSUE TITLE
Error "No bootable device" when starting image via Proxmox

### ISSUE THREAD

**Issue by fl0wm0ti0n** [nanovms/ops#1335]
Hello Guys!

OPS: Latest
WSL2: Debian GNU/Linux 11 (bullseye)

**issue:**
I made following c++ example via VS
![image](https://user-images.githubusercontent.com/24993288/169710794-921bd50f-799a-4fc3-9575-03ddee219057.png)

i built it via WSL2 CMAKE
![image](https://user-images.githubusercontent.com/24993288/169710805-a25b284c-ba24-490f-9457-a4c3f118cce6.png)

then i successfully run "ops run CMake-WSL2-TestProjekt"
means i got my output i expected

after that i run 
ops build CMake-WSL2-TestProjekt
Output:
 Bootable image file:/home/flow/.ops/images/CMake-WSL2-TestProjekt.img

then i started a VM in proxmox with this Image and i get an error "no bootable device"
![image](https://user-images.githubusercontent.com/24993288/169711265-5c7b072e-9a4a-4e91-9967-f56ba5aa4b3f.png)

**VM Settings:**
![image](https://user-images.githubusercontent.com/24993288/169710953-9feeaaeb-3ed7-48c5-8139-d4a41444192a.png)
![image](https://user-images.githubusercontent.com/24993288/169710983-afed461f-29c3-4e32-badd-690a081ef5a8.png)

Thank you for any help!

**Comment by eyberg** [comment]
@fl0wm0ti0n were you using 'ops image create -t proxmox' and 'ops instance create' to boot this? there are a few things that happen such as setting this as a virtio disk and setting the boot order

this isn't supposed to be booted from cd - if you didn't use image/instance create commands before can you try and see if that fixes your issue?

**Comment by fl0wm0ti0n** [comment]
> @fl0wm0ti0n were you using 'ops image create -t proxmox' and 'ops instance create' to boot this? there are a few things that happen such as setting this as a virtio disk and setting the boot order
> 
> this isn't supposed to be booted from cd - if you didn't use image/instance create commands before can you try and see if that fixes your issue? you check out some examples here: https://docs.ops.city/ops/proxmox .

im sorry dont get it ... i didt do the Proxmox steps you asked about.

i develop on WSL2 debian i did built an image via "ops build CMake-WSL2-TestProjekt" and i got an image.

i dont get how these proxmox steps are made?

in proxmox i simply import an image from where i can boot a vm like from an USB-Key

for example where do i run this steps?:
export API_URL="https://172.16.41.133:8006"
export TOKEN_ID="myuser@pam!tokenid"
export SECRET="some-uuid-goes-here"
ops image create g -t proxmox -c config.json

im not on proxmox bash, im on WSL2 Debian.

What is in the "config.json"? this isnt well described.
and API Token Stuff i cant find under datacenter - there is no point for that in PROXMOX GUI.

Thanks alot

**Comment by fl0wm0ti0n** [comment]
isnt this api just to remotely work with proxmox?
but i just want to boot my image like with a normal bare metal.

**Comment by eyberg** [comment]
ops works fine under WSL2 so you can do that

the config.json is just a configuration file (if you need extra config) - it's not mandatory

what 'ops image create' does is create a disk for you to boot from - you're choosing a bootable cdrom and that's why it isn't working for you

if you want to do this manually (not advised) - you'll need to create a disk out of the image and set the boot to boot from that - not the cdrom https://github.com/nanovms/ops/blob/master/proxmox/proxmox_instance.go#L102-L103

you can create a token to access the API like so: https://pve.proxmox.com/wiki/Proxmox_VE_API

**Comment by eyberg** [comment]
No we only support virtual disks and have no plans on supporting different devices.

To clarify that page you are referencing (bare metal) that page is saying that you can run ops on a real machine (versus uploading images to a public cloud) but ops spins up virtual machines under qemu. There is never a case where we would flash an actual physical machine with the disk image. All Nanos workloads are meant to be ran virtualized - it is one of the key differences when compared to Linux which can be installed to actual metal.

**Comment by fl0wm0ti0n** [comment]
oh damn :(
then i miss understood the Wiki completely... 

i was searching a unikernel-solution where i can boot on bare metal.

maybe i can convert these VM image to a usable disk with some tools outhere

**Comment by eyberg** [comment]
to clarify we support many different filetypes and block devices but it's always going to run on a hypervisor/cloud of some kind - if your intention is that you want something to boot up on an actual real physical machine and overtake everything that's not a goal for this project - there are other projects like https://github.com/usbarmory/tamago though that do that

**Comment by fl0wm0ti0n** [comment]
okey, thank you very much for the informations, i search something for x86_64 and c++ but this project is a good hint
