### ISSUE TITLE
Python 3.10 package missing libz

### ISSUE THREAD

**Issue by paulreimer** [nanovms/ops#1365]
I'm excited to start using the `eyberg/python:3.10.6` image, but I noticed that I cannot `import base64`; I believe this is because `libz.so.1` is missing from the package image.

(`eyberg/python:3.9.7` has it:)
```
ops pkg contents eyberg/python:3.9.7 | grep libz
File :/sysroot/lib/x86_64-linux-gnu/libz.so.1
```

Personally I'd also like to see `librt.so.1` as well (a dependency I use needs it, but doesn't use it AFAICT); none of the existing `python` packages have that but I wish they did!

**Comment by paulreimer** [comment]
Thanks! -- that's helpful.

The next one needed seems to be `libssl.so.1.1`

**Comment by eyberg** [comment]
went ahead and added that as well, if you have a snippet of code or project you are trying to load that might iron out what all you need

**Comment by paulreimer** [comment]
Sure, and thanks! (the next one needed is `libcrypto.so.1.1`)

The list of `import`s I'm using is:
```
import asyncio
import base64
import dataclasses
import datetime
import hashlib
import hmac
import io
import json
import os
import random
import socket
import ssl
import string
import sys
import time
import traceback
import typing
```

(I'm also using `aiohttp` with a `venv`, but I don't think it needs any extra libs)

**Comment by eyberg** [comment]
ok - I don't get any error msgs w/these imports w/the latest pkg i uploaded

**Comment by paulreimer** [comment]
OK, I think there may be one more (needed by a private/confidential `.so` file I am `import`ing): `libpthread.so.0`.

Sorry for the hassle; I am excited for using 3.10 and that I'll be able to use it for many things in the future!

**Comment by eyberg** [comment]
I went ahead and included that, all of this that you've requested is fairly standard so I'm not surprised you're finding them

**Comment by paulreimer** [comment]
Working well now! Thanks so much!

I needed to add a `/etc/ssl/cert.pem` file for verifying certificates (I used the one from the `certifi` package, which is Mozilla's default CA root store IIUC); not sure if that would be a useful addition to the default package... (the previous python packages needed it as  `/usr/lib/ssl/cert.pem`)

**Comment by eyberg** [comment]
nah that makes sense, we auto-include /etc/ssl/certs in almost everything but i added this to the python pkg and this test seems to work now:

```
import urllib.request
r = urllib.request.urlopen("https://paypal.com")
print(r.read())
```

**Comment by paulreimer** [comment]
Confirmed -- working great over here!

**Comment by paulreimer** [comment]
FWIW, here are a couple other system libraries that I've found useful (when using Python libraries which use native Linux libraries):
- `libdl.so.2`
- `libffi.so.8`

**Comment by eyberg** [comment]
added those for you
