### ISSUE TITLE
intel hax should be installed by default for mac users

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#141]
there are pre-made verified builds by intel

one note - it looks like only osx 10.10 and above is supported so there can be a quick version check done to see if we can even install or not but if we can we should

**Comment by ExternalReality** [comment]
@eyberg can you point me at the pre-made builds. For some reason I am having trouble finding them.

**Comment by eyberg** [comment]
just copying some old notes -->

https://github.com/intel/haxm
https://software.intel.com/en-us/blogs/2014/10/20/how-to-ensure-you-are-using-intel-haxm-for-android-emulator


```
If you want to enable HAX (intel hardware acceleration) on Mac you have to options:

You can either roll your own kernel extension or you can download a dmg:

Roll Your Own Extension
boot into recovery mode (reboot && cmd-shift-R) and disable system integrity either of the two following methods:
csrutil enable --without kext
csrutil disable
git clone https://github.com/intel/haxm

build the kernel extension: (note: substitute the 10.13 for whatever is in sw_vers -productVersion)

xcodebuild -config Release -sdk macosx10.13

sudo chown -R root:wheel intelhaxm.kext

sudo kextutil intelhaxm.kext

Download a signed dmg
https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-mac-os-x

You should now be able to see that hax is working: qemu-system-x86_64 -accel hax
```

this task is actually composed of a few sub-tasks imo:

- [ ] enumerate osx version to determine what .dmg should be loaded 
- [ ] prompt but don't demand the user install hax
- [ ] need perms request in installer
- [ ] possibly create new signed dmgs 
- [ ] implement kexst check for osx (to see if there is hax enabled)
- [ ] re-eval perms issues to make this easy for end-users - i'm kinda thinking that if the installer script can be smart enough to detect vt-x and friends it should just go ahead and setup necessary permissions so that the user can run this stuff w/out sudo everytime - there's an implication here that most real deployments are going to be pushed through public clouds regardless so it's a bit of a mute issue for local

**Comment by eyberg** [comment]
just as a fyi - we should be disabling sip for end-users - that's just a debugging mechanism

**Comment by ExternalReality** [comment]
Some thoughs:

> enumerate osx version to determine what .dmg should be loaded

The the latest official .dmg as of writing is [7_4_1](https://github.com/intel/haxm/releases/tag/v7.4.1). This version supports macos versions as far back as Yosemite. I'm thinking this one .dmg could be good enough.

**Comment by eyberg** [comment]
oh I didn't know that - if that's the case awesome - if someone has something before that they can open a new issue on it -thanks

**Comment by eyberg** [comment]
closing this as old as we use hvf now
