### ISSUE TITLE
nanosVM built with latest op source terminates on VSphere deployed with Envoy 

### ISSUE THREAD

**Issue by robertsmol** [nanovms/ops#1454]
I am trying to get a sample application (an Envoy Filter) deployed in a Unikernel running on VSphere. My initial test for this deployment result in a Unikernel which eventually became unresponsive (it hung). After logging this issue the following fixes were made:

https://github.com/nanovms/lwip/commit/91c53301d6bf6ca4978a82f2cd6464c9ed18e7e4
https://github.com/nanovms/nanos/pull/1846

I tried out these fixes and the behavior has changed. The Unikernel now terminates. The following logs are produced:

[boost_asio.txt](https://github.com/nanovms/ops/files/11398554/boost_asio.txt)
[logs_envoy.txt](https://github.com/nanovms/ops/files/11398555/logs_envoy.txt)
[envoy_echo.txt](https://github.com/nanovms/ops/files/11398556/envoy_echo.txt)

**Comment by francescolavra** [comment]
We identified the issue causing the unikernel instance to terminate, and fixed it in https://github.com/nanovms/nanos/pull/1847.
When running an Envoy echo filter demo application on vSphere, I noticed that sometimes the server is abnormally slow to echo back the data it receives; I'm looking into why this is happening.
