### ISSUE TITLE
Clarification on Cloudwatch Klib

### ISSUE THREAD

**Issue by JonathonJulian** [nanovms/ops#1485]
hello,

reading the docs i see there is a cloudwatch klib available. my initial attempt to include it has failed, the VM just shutdown immediately (c6i.large) 

[the docs](https://docs.ops.city/ops/klibs) specify` Not all of these are available to be included in your config (cloud_azure, aws) . Only the ones found in your ~/.ops/release/klibs folder can be specified.`. only i dont have a releases folder

```
ls ~/.ops
crossbuild  images  instances  local_packages  manifests  nightly  packages  volumes
```
Im compiling from master in order to get c6i support. and have added `cloudwatch` to my klib config. Does this feature work with all supported instance types? do i need to copy over the klib from somewhere?

**Comment by JonathonJulian** [comment]
oh, or is it supposed to be included when you specify `-t aws` ?

**Comment by eyberg** [comment]
those docs need to be updated - the 'release' would be something like ~/.ops/0.1.45/klibs or ~/.ops/nightly/klib - cloudwatch should work on all instance types on aws, besides the klibs you need an IAM role specified as well

https://nanovms.com/dev/tutorials/introducing-console-drivers-to-stream-to-gcp-logging-aws-cloudwatch
