### ISSUE TITLE
Ops not working after update

### ISSUE THREAD

**Issue by joshua-quek-sonarsource** [nanovms/ops#1494]
Hello! I did an update `ops update` and after that after trying to run the basic command from the Docs: 

![Screenshot 2023-07-13 at 2 03 57 PM](https://github.com/nanovms/ops/assets/124841129/2658c17d-1eec-4ce8-8859-39fc9f6409d9)

![Screenshot 2023-07-13 at 2 04 05 PM](https://github.com/nanovms/ops/assets/124841129/419747c8-90be-4df3-ad06-6606618d12fa)

ops throws me a `package not found` error.

when I try to run `ops pkg get nanovms/elasticsearch:8.2.0`, also the same error shows:

![image](https://github.com/nanovms/ops/assets/124841129/ee410405-17ed-463f-a500-70403e9a52cf)

Just wondering if anyone else is experiencing the same thing.

**Comment by francescolavra** [comment]
I can't reproduce this issue, I just did an ops update and then typed your commands to download the node and elasticsearch packages, and both were downloaded successfully.

**Comment by joshua-quek-sonarsource** [comment]
Hmm, it could be a network issue on my end maybe.
No worries, thank you!
