### ISSUE TITLE
chore(volumes): warn when volume name/label length > nanos(VOLUME_LABEL_MAX_LEN - 1) 

### ISSUE THREAD

**Issue by rinor** [nanovms/ops#1517]
https://github.com/nanovms/nanos/blob/41c61e23db0d358383fdc8c95b1c046eceb4d147/src/runtime/storage.h#L23
```c
#define VOLUME_LABEL_MAX_LEN    32  /* null-terminated string */
```
when the `name/label length > 31` the kernel won't load/mount it.

**Comment by eyberg** [comment]
i'm fine w/a warning, although curious as to the use-case as to why more than 31 is needed

i took a look and GCP limit is 61 and AWS is 255 (for aws this is prob. the tag limit)

**Comment by rinor** [comment]
> although curious as to the use-case as to why more than 31 is needed

There is no need for that, but when you don't know that limit (or you forget about it, like I did) you may end up wasting a lot of time troubleshooting why the volume is not being mounted when the name is longer than that, for no specific reason other than being descriptive as much as possible.

**Comment by rinor** [comment]
closing this since nanos warns about this upon volume detection and that's good enough
