### ISSUE TITLE
feature request to deploy to Hivelocity.net provider

### ISSUE THREAD

**Issue by placrosse** [nanovms/ops#1522]
Add feature to OPS to support hivelocity API to create one or more dedicated servers booting directly to nanosvm images via iPXE

https://developers.hivelocity.net/reference/post_bare_metal_device_batch_resource

**Comment by eyberg** [comment]
ops really only targets providers that deploy vms, I didn't immediately see something in their api that would provide this although I saw mention of a vps; I do see proxmox which I know we have users that use that; ops itself could be provisioned on top as well

**Comment by placrosse** [comment]
For the "bare metal" / "dedicated server" use-case, how much difficulty do you anticipate Ian (@eyberg) in deploying a single nanovms image as the one and only runtime process on the physical server?  We have some possible uses where the physical machine would boot using the iPXE approach. ( https://ipxe.org ). But instead of an OS, we want to run a nanovms image containing our server process.  Or, would we have to deploy some hypervisor, even if we only want to have a dedicated single process under it?

**Comment by eyberg** [comment]
right now we don't have any plans to support bare metal installs like this as that would imply a bunch of other mgmt related tooling that would not be present (eg: start/stop the server, configure networking, deploy a new one, access rights, etc.) it also breaks the assumptions we have that it is only being deployed as a vm which means having to support a ton of random hardware drivers, nanos is intended to always be ran on top of a hypervisor of some kind - whether it's public cloud or something under your own control (eg: proxmox/vsphere/etc.)

**Comment by placrosse** [comment]
Thank you for the information Ian @eyberg .  I certainly understand not desiring to support a large number of drivers.  That said, I will close this request, and instead look for the smallest/simplest supported hypervisor layer that is currently supported, with the understanding we still want just one server process per physical machine.  Any comments or pointers you may have are welcomed.
