### ISSUE TITLE
GCP instance creation to an instance-group fails from non-default interface name

### ISSUE THREAD

**Issue by placrosse** [nanovms/ops#1533]
Output from GitHub Action below:

+ /home/runner/.ops/bin/ops instance create hydra-52a65f0 -c .private/config.json -t gcp -i hydra --instance-group hydra-group --show-debug
Instance template creation started...
Operation operation-1698369595983-608a87c774660-6594a19f-ae0f61d6 completed successfully.
googleapi: Error 400: Invalid value for field 'instanceTemplate': 'https://www.googleapis.com/compute/v1/projects/hydra-v0/global/instanceTemplates/hydra'. Stateful IPs are not allowed with non-default Network Interface names, like eth0 in template hydra., invalid
[cargo-make] ERROR - Error while executing command, exit code: 1

**Comment by eyberg** [comment]
commenting out https://github.com/nanovms/ops/blob/master/provider/gcp/gcp_network.go#L170 seems to resolve this issue for me, I need to look more to see if there is a reason why we have declared them all to be eth0 by default or not - I don't think there is a reason though and if so we should just yank that everywhere
