### ISSUE TITLE
include update command to check for ops {boot,mkfs,staging3} upates

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#154]
~~* mv {boot,mkfs,staging3} to https://github.com/nanovms/ops/issues/153~~

* add sha2  for these and throw into some sort of manifest

* update can consult latest manifest and if out of sync download

**Comment by anikitenko** [comment]
Regarding MD5, I have some ideas:
- Without having separate manifest for system images: problem here is that there is always need to download images and then compare MD5 sums.. so.. sounds not so good
- Having separate manifest (for example system.json) - avoids downloading files each time but.. having 2 manifests, as I can see, will require to always make sure that manifests are up to date (according to  logic that I see)
Probably "update" function should be extended to be able to update manifests too (as @eyberg already stated).
Please tell me if I'm on correct way of thinking.. :)

**Comment by eyberg** [comment]
right now there are 2 release channels - 'nightly' (which is whatever is found in master, eg: bleeding edge) and releases we cut manually which is what general population gets, as of right now we aren't keeping more than one of each - maybe in the future we will but not right now

I think right now it's prob. useful to zip these 3 things up into a tarball and md5 that and also host the md5 inside the bucket so that ppl can be assured their stuff wasn't tampered with

the original request was just to move the core stuff into a common area && implement light-weight versioning so it's not downloading the entire thing each time for a new project

**Comment by anikitenko** [comment]
Okay then, my PR covers first part "move the core stuff into a common area", will think about "implement light-weight versioning"..)

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/307

**Comment by eyberg** [comment]
we've had a update/version check for a while now - closing
