### ISSUE TITLE
GCP rate limit: one disk image create every 10 minutes

### ISSUE THREAD

**Issue by chk-n** [nanovms/ops#1569]
According to google cloud [docs](https://cloud.google.com/compute/docs/images/create-custom#create_image): "You can create a disk image once every 10 minutes. If you want to issue a burst of requests to create a disk image, you can issue at most 6 requests in 60 minutes". This seems like a problem especially in a development environment where many deployments could occur. How does `ops` handle this?

**Comment by eyberg** [comment]
have you actually ran into that limit? we have quite a few users on GCP and I've never seen that limit hit; we definitely have situations where we go past that limit quite a lot; if you click on the second link it seems to imply it's for snapshots which is not how we create images

**Comment by chk-n** [comment]
No, but I don't want to run into that limit haha. Yeah its not very clear what they are referring to.. thanks for the quick reply

**Comment by rinor** [comment]
@chk-n what you are interested in, when dealing with image operations (boot images and/or disk(volume) images), is the gcp api quota limit for main actions like:
- images.insert
- images.delete

and, atm, that should be smth like 375 requests/minute/project.
Check https://cloud.google.com/compute/api-quota and search for `GlobalResourceWriteRequestsPerMinutePerProject`

**Comment by chk-n** [comment]
@rinor Cool, thanks for the clarification :) That's more than enough for my use case
