### ISSUE TITLE
Incomplete documentation, no real world nodejs runner example

### ISSUE THREAD

**Issue by kyeno** [nanovms/ops#1575]
The documentation is both incomplete and incoherent.

There are at least two links leading to 404s:

![Screenshot_select-area_20240203142439](https://github.com/nanovms/ops/assets/1790957/7bce5591-dc3f-4799-aa44-93df65b38048)
![Screenshot_select-area_20240203143122](https://github.com/nanovms/ops/assets/1790957/cccb2c8f-ba60-430c-addd-da81a316bf33)

The first one (with nodejs examples) is rather IMPORTANT to work; otherwise the whole documentation treats that usecase rather poorly.

Undocumented configuration option:
![Screenshot_select-area_20240203142759](https://github.com/nanovms/ops/assets/1790957/881a6d9b-f085-442e-b4bb-b41871c9974e)

Generally it's very hard to "get started" with a real world node project here (something bigger than "hello world" one) and I believe that section should be vastly expanded.

**Comment by eyberg** [comment]
thanks for pointing it out - there are quite a few javascript examples here: https://github.com/nanovms/ops-examples/tree/master/javascript and we should probably rename the 'getting started' - there are some for just normal users and some for those working on nanos itself

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-documentation/commit/fa29ee1dcb95ed5b8d28ef2fc8169f37e712b5fe
https://github.com/nanovms/ops-documentation/commit/3bd054ee25f13a356f39d42fe742a2da47e75a63
