### ISSUE TITLE
Instance tags through config.json in DO

### ISSUE THREAD

**Issue by hnord-vdx** [nanovms/ops#1578]
I have added tags in `CloudConfig` (e.g. "function": "webserver") but they dont show on digital ocean. Is this not possible or am i doing something wrong?

**Comment by francescolavra** [comment]
Ops currently does not assign tags in `CloudConfig` to Digital Ocean instances, but this feature can definitely be added in the future.

**Comment by hnord-vdx** [comment]
Alright, thanks! This feature would be quite useful, especially when combined with DO load balancers, as it would seamlessly direct the load to the new instance.
