### ISSUE TITLE
Memory metric not showing for instance on digital ocean

### ISSUE THREAD

**Issue by hnord-vdx** [nanovms/ops#1583]
I am wondering why CPU, disk i/o and bandwidth is shown but there is no memory consumption metric. Is this a limitation of nanosvm?

**Comment by eyberg** [comment]
no, it's not a limitation - it's the fact that we need to have a custom klib export the metrics out cause that's not something the host can see itself (normally) - we have similar functionality for aws/gcp but not do yet

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/pull/2007 implements an agent running in the Nanos kernel which exports memory consumption metrics to the DigitalOcean monitoring server, so that instance memory usage data is displayed in the graphs of the DigitalOcean droplet control panel.
