### ISSUE TITLE
[Mac M1] ops pkg list (question / bug)

### ISSUE THREAD

**Issue by galuszkak** [nanovms/ops#1604]
Hey,

I tried to play with ops but it's unclear to me if it works correctly.

So I did look on https://repo.ops.city/ and search for all `python` packages. 

I did the same in shell (I've added API Key using `ops pkg login`) but when I do:
```bash
➜  ~ ops pkg list --search python

+-----------+-------------+---------+----------+---------+--------------------------------+
| NAMESPACE | PACKAGENAME | VERSION | LANGUAGE | RUNTIME |          DESCRIPTION           |
+-----------+-------------+---------+----------+---------+--------------------------------+
| eyberg    | python      | 3.10.6  | c        | 3.10.6  | The Python programming         |
|           |             |         |          |         | language.                      |
+-----------+-------------+---------+----------+---------+--------------------------------+
```

So it's only 1 package not 9 how I saw it on https://repo.ops.city. Am I'm doing something wrong here?
<img width="629" alt="Screenshot 2024-04-09 at 12 54 29" src="https://github.com/nanovms/ops/assets/759579/34d4be73-b508-4c58-9f88-0d729181b8ae">

**Comment by galuszkak** [comment]
OK I realized is because of the CPU architecture. Closing.

**Comment by eyberg** [comment]
yes - x86 pkgs vastly outnumber arm ones only because those are the ones that most commonly get deployed to prod envs; if you see something that you'd like to see on arm though feel free to open an issue and we can possibly take a look

also, you can always set the arch flag via to run cross-arch too:

```
ops pkg load eyberg/sabledb:0.0.1 -p 6379 --arch=amd64
```
