### ISSUE TITLE
OPS "hangs" when running go http server image locally..

### ISSUE THREAD

**Issue by zimdo** [nanovms/ops#1677]
Hi there,

I am trying to get a simple go image to run and it would just sit at:

```
[REDACTED]@[REDACTED] bla % GOOS=linux go build main.go
[REDACTED]@[REDACTED]bla % ops run -f -p 3000 main    
running local instance
booting /Users/[REDACTED]/.ops/images/main ...
[0.003213] en1: assigned 10.0.2.15
```

I can't use the IP-address / port combo to get any output from curl or browser.

It's basically a web-server running chi and some other stuff opening a port 3000, rendering HTML.

So I tried going through the examples.

The go-hello-world example worked and logged its output.

The go-hello-world-http server has the same issues as described above.

So I removed all code related to starting the HTTP server from my initial program and it started printing output.

I also tried changing the Arch of the go-build (using GOARCH) and ops (using --arch) but that gave me a core-dump.

Not really sure where to go from here. I am on an Apple M2 MAX. ops is freshly installed 

```
Ops version: 0.1.43
Nanos version: 0.1.53
```

Any idea what to do?

**Comment by eyberg** [comment]
there was an issue w/ go 1.23 on arm - what's your go version?

if it's 1.23 you can try specifying the nanos version like

```
ops run main --nanos-version=92df866
```

**Comment by eyberg** [comment]
whenever they get merged you'll be able to use the nightly build 'ops run -n'

the 'localhost' might need to be changed to '0.0.0.0' - idk cause I can't see your code, but if that is working locally we're unaware of any issues w/aws currently

did you build for x86 and deploy to an x86 instance? if you're on a mac by default it'll build arm

if not..

instance type? do you have logs of something failing? is it not starting? what's the command you used to build/deploy?

**Comment by eyberg** [comment]
i don't know what's in your config but if you aren't specifying the arch here then it could be creating an arm image and failing to boot

doing something like this will have it default to a t2.micro

```
ops image create server --nanos-version=92df866 --arch=amd64 -c aws.json -t aws
ops instance create server -p 8080 -c aws.json -t aws
```

you might try building with the latest ops - it has a check now that complains early on if it detects the wrong architecture being built with

**Comment by eyberg** [comment]
k, good to hear - closing this for now
