### ISSUE TITLE
Make all qemu parameters configurable, there some hard-coded

### ISSUE THREAD

**Issue by tijoytom** [nanovms/ops#173]
Better if the config can be generic ie not tied to a specific hyper visor

**Comment by ExternalReality** [comment]
How about  package dependencies using [gopkg.in](https://golang.github.io/dep/) and pulling in intels [qemu package](https://github.com/intel/govmml)? Its small its simple and its got all the types laid out quite nicely.

**Comment by tijoytom** [comment]
I am talking about the command line parameter passed to qemu not package dependency.  This link  qemu package is broken, so not sure what it means.

**Comment by tijoytom** [comment]
I see, i don't see any particular reason to use intel package, it just supports qemu and probably not maintained too. It's pretty straight forward to create our own wrapper, we already have the interfaces for it( ie the Hypervisor interface), just need to wire them up. And about deps, let's not introduce something unless we absolutely need it.Keep it simple as much as we can.

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/182/files
