### ISSUE TITLE
support for multiple bridges

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#174]
noticed there is no support currently for multiple bridges

https://github.com/nanovms/ops/blob/master/network.go#L40

**Comment by eyberg** [comment]
@chaitanya-baraskar i don't think tuntaposx is an option anymore && i don't know of any other solution that would work (perhaps some osx native api?) so this would be for local linux only

**Comment by fabioDMFerreira** [comment]
This is a feature that affects at least run and load commands.

I'm going to use this opportunity to refactor #459.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/1568 adds initial support for linux (vmnet-bridged is used on mac already)
