### ISSUE TITLE
ip forwarding for bridge on osx

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#175]
most macs don't come w/ethernet jacks anymore - unfort this causes problems cause the access point will reject the frames

solutions I've used in the past (which may or may not be great) work thusly:

https://gist.github.com/kujohn/7209628

https://github.com/deferpanic/virgo/blob/master/pkg/network/network.go#L22-L26
https://github.com/deferpanic/virgo/blob/94dc177c18076f539d468f068c937a9bff75ab73/cmd/virgo/main.go#L93-L109

this is a little bit of a mute issue though until [tap support for osx](https://github.com/nanovms/ops/issues/140) is in

**Comment by ExternalReality** [comment]
@tijoytom what do you think about storing these network scripts as plain `.sh` files and copying them to a conventional `~/.ops/network/macos` on install? Alternatively one could [embedded the scripts in the compiled executable with go:generate](https://stackoverflow.com/questions/17796043/how-to-embed-files-into-golang-binaries). Keeping them as separate scripts makes the test cycle and debugging. Using the scripts at run-time does not complicate the build while embedding in executable adds a step to the build.

**Comment by eyberg** [comment]
it'd be better if we can avoid shelling out for this stuff (if there's a go native way to achieve anything that'd be best) - also - it's a bit of a mute issue w/out having the tuntap extension (or something else) installed first although I just updated that tkt w/some details

**Comment by tijoytom** [comment]
Yup, we purposefully avoided shelling out in ops and we shouldn't for this either.
