### ISSUE TITLE
support for multiple taps

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#177]
for some reason I thought this had already been done but noticed it's isolated

* can potentially cache some of this info somewhere like in ~/.ops/ for persistence

* need to auto-gen the macs as well

**Comment by ExternalReality** [comment]
By multiple taps do you mean mulitple nic's with tap backends? Would this mean add the ability to add multiple nic's and automatically give them tap backends? Also what would the "-p" parameter in ops mean in the face of multiple nics?

```json
"RunConfig": {
        "Verbose": true,
        "Bridged": true,
        "Nics": [
          {
                 "Name": "Nic1",
                 "Ports": [8008],
                 "Mac": "xx:xx:xx...",
          }, {
                 "Name": "Nic2",
                  ...
           }]
        "Memory": "2G"
    }
```

**Comment by eyberg** [comment]
the tkt wasn't super clear - this is a tracking issue to enable multiple vms at the same time - right now it's locked to one tap device and thus one vm - while there's no reason why we couldn't have multiple network interfaces per vm in the future that's not currently supported and kinda low priority

**Comment by eyberg** [comment]
@chaitanya-baraskar i don't think tuntaposx is an option anymore && i don't know of any other solution that would work (perhaps some osx native api?) so this would be for local linux only
