### ISSUE TITLE
ops list needs a mechanism of updating the cached manifest

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#178]
packages are going to be updated on a fairly regular basis and new ones added - w/out blowing away the manifest each time it'd be nice to have the list command be a bit more smart about updating itself

* ops list needs to by default chk the etag header to look for new manifest for ops list command

* it should prob. silently fail though on the lack of internet presence

* if the etag is diff go ahead and grab the new manifest

**Comment by tijoytom** [comment]
https://github.com/nanovms/ops/pull/181
