### ISSUE TITLE
search functionality need for package manifest

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#180]
right now there's only 6 packages but we have a long tail of packages that we'll be adding in the very near future so doing a straight listing isn't really going to cut it and there's an assumption that most people will be using packages predominately rather than running straight binaries w/custom config.json - for now just something to search through that is sufficient in lieu of having a micro-app for this

**Comment by ExternalReality** [comment]
Is using `regexp` to make a simple search good enough? Is there yet a local package cache that can be search (like apt)?

For the CLI how about something like `ops list -s <regexp>`?

**Comment by eyberg** [comment]
i think that's fine for now and tying that to the local manifest in ~/.ops/packages/manifest.json - this is more of a tmp. hack for now cause as the feature list for packaging grows it's pretty clear we'll going to want to carve it off into it's own service

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/185
