### ISSUE TITLE
-bash: ops: command not found

### ISSUE THREAD

**Issue by Truemedia** [nanovms/ops#189]
Running install command provided from getting started on OS X (Homebrew already installed) runs fine, I get the following message after running:

`Successfully installed ops 0.2! Please open another terminal where the `ops` command will now be available`

But when I run the command `ops version` to check the installed version I get the following error:
`-bash: ops: command not found`

I can see the path has been exported to my .bashrc fine, but not found?

**Comment by ExternalReality** [comment]
> ...However, Terminal.app on macOS, does not follow this convention. When Terminal.app opens a new window, it will run .bash_profile. Not, as users familiar with other Unix systems would expect, .bashrc.
> [-scripting OS X](https://scriptingosx.com/2017/04/about-bash_profile-and-bashrc-on-macos/)

The install script should probably not generate the message you've encountered if it uses `.bashrc`. Perhaps on macOS the install script shouldn't report that it looked for `.bashrc`. 

If `.bashrc` is NOT being run then its likely that you have nothing else in that file. Perhaps you can just move the generated script to `.bash_profile` from `.bashrc`. `.profile` also works but it would require that you log out and log back in. Alternatively, (if you are not otherwise using `.bashrc` for anything) then you can simply `rm ~/.bashrc`  `touch ~/.bash_profile` and run the install script once more.

**Comment by Truemedia** [comment]
Sorry that doesn't work either. Whether i put the generated path export in .bash_profile or .profile (I already a .profile, .bash_profile, and .bashrc file on my machine before installing).

It does look like my .profile and .bash_profile have a different style of export though that could be conflicting with mine (I'm not an expert on bash profiles).

**~/.bash_profile**
`[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*`

**~/.profile**
`# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*`

**Comment by eyberg** [comment]
@Truemedia - you can actually just re-export PATH - in ~/.profile

by appending this right underneath that PATH line in .profile 

```
export PATH="$HOME/.ops/bin:$PATH""
```

or replace with:

```
export PATH="$HOME/.rvm/bin:$HOME/.ops/bin:$PATH""
```

it's best practice to always put the original $PATH var on rhs

if that doesn't work - I'm a zsh user - it looks like you are using bash? I just tried to install via that route and got this - what do you have for which output?

```
bash-3.2$ which ops
/Users/eyberg/.ops/bin/ops
bash-3.2$ ops
Usage:
  ops [command]
```

also - your output for =>

```
bash-3.2$ ls -lh .ops/bin/ops
```

**Comment by Truemedia** [comment]
@eyberg Sorry for taking so long to get back. So it actually worked after restarting and reinstalling a few pieces of software I already had on my machine.

Running the ops command works now thanks, but hopefully this will help anyone in future.

**Comment by eyberg** [comment]
ok - thanks!
