### ISSUE TITLE
ops load leaves artifacts from old version of the package

### ISSUE THREAD

**Issue by skupr** [nanovms/ops#193]
When I was creating new ops package, and testing it via 'ops load', I've encountered an issue that despite package is unpacked into .staging directory on each 'load', old package files are not deleted - it only adds new and updates existing files. In the case new package needs some old files deleted (in my case, I've had some files with space, which break mkfs), they still present in .staging/<package_name> directory, which may cause some confusion and incorrect work of the new version of the package.

**Comment by eyberg** [comment]
we have an aux tkt to md5 each pkg -> https://github.com/nanovms/ops/issues/169 - i think this is pretty important for a number of reasons

also - package should be downloaded to ~/.ops/packages - then base images can be created in project root ~/.staging but it makes no sense to download each time to ~/.staging

**Comment by tijoytom** [comment]
We don't download to .staging every-time, we once download to ./ops/packages and then extract to .staging every-time. You can add code to  delete the folder before extracting and it should be good. Reason we extract each time is to make sure that packages are clean. But we can avoid doing the extraction if required.

**Comment by tijoytom** [comment]
https://github.com/nanovms/ops/issues/193

**Comment by skupr** [comment]
Fixed by #200
