### ISSUE TITLE
auto-stub /etc/passwd

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#210]
like we do for /etc/hostname, /etc/resolv.conf go ahead and implement an auto-stub for fake user =>

```
root:x:0:0:root:/root:/bin/notreal
```

i'm not opposed to allowing end-user to change this if the need arises but for now I think this should allow most everything that calls this family of libc to work https://linux.die.net/man/3/getpwuid_r

**Comment by anikitenko** [comment]
As for me, good point.. can work on this..

**Comment by tijoytom** [comment]
@anikitenko you are most welcome to work on this, feel free to assign it yourself.

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/issues/351

**Comment by tijoytom** [comment]
#237
