### ISSUE TITLE
ingest_parse_int error: value missing allocated

### ISSUE THREAD

**Issue by ExternalReality** [nanovms/ops#213]
I received the following error during an `ops run -nf myexec`. The program is a small `c` program that just downloads a file and does some encoding that has been tested and works well on macOS, Debian Stretch, and Manajor 18.0. I can provide the source if needed.

```
booting image ...
ingest_parse_int error: value missing allocated
assertion ingest_parse_int(value, sym(allocated), &allocated) failed in /go/src/github.com/nanovms/nanos/src/tfs/tfs.c: ingest_extent() on line 444; halt
```

**Comment by eyberg** [comment]
spotted this yesterday to - there's a small regression in mkfs in the nightly release channel - normal doesn't appear to be affected at the moment - incoming fix

**Comment by tijoytom** [comment]
@ExternalReality is this on mac?

**Comment by ExternalReality** [comment]
@tijoytom I received the error on Debian 9 Stretch.

**Comment by tijoytom** [comment]
@ExternalReality This should be fixed now, you might want to do ``` ops update```

**Comment by ExternalReality** [comment]
@tijoytom Thank you.
