### ISSUE TITLE
Error "No bootable device" when starting image

### ISSUE THREAD

**Issue by fzaninotto** [nanovms/ops#232]
Hi, and thanks for this very promising tool.

I followed the installation instructions and got the php unikernel with phpInfo created as tempimage. I tried running the image with qemu, but the kernel fails to find the image.

I'm a qemu noob, so it may be my fault. I just typed:

```sh
$ qemu-system-i386 tempimage
```

![image](https://user-images.githubusercontent.com/99944/53403426-f0006e00-39b3-11e9-8474-a5dc7f7424cc.png)

**Comment by eyberg** [comment]
@fzaninotto - I wouldn't run w/qemu by itself - there's a bunch of stuff that needs to be configured for it - ops does this by default - so you can just do an 'ops load' or 'ops run' instead - also that tmpimage is going away

lastly -- qemu-i386 is the wrong tool to use even if you wanted to go down this route - qemu-system-x86_64 is what we use inside ops - that specifies the machine type and we have no plans of supporting 386s :) - we're 64bit only

here's a php example -> https://nanovms.gitbook.io/ops/basic_usage#running-php-hello-world

**Comment by fzaninotto** [comment]
Thanks. I had run that example but got no output. On second inspection I forgot the `-a` option in the following snippet:

`ops load php_7.2.13 -a ex.php`

My mistake, sorry for the noise and great work!
