### ISSUE TITLE
error gracefully on missing binary

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#233]
I stupidly pasted this into the shell and of course it blew up cause there isn't a binary named server here - instead of throwing a panic/calltrace we should just gracefully error out and tell the user what the problem is - there's actually quite a few of these in the codebase that could use a human readable error response

```
➜  ~   NANOS_UPDATE=1 ops run server

Downloading.. /Users/eyberg/.ops/1.0/nanos-release-darwin-1.0.tar.gz
 1.05 MiB / 1.05 MiB [===============================================================================================================================================================] 100.00% 3.48 MiB/s 0s
Finding dependent shared libs
*os.PathError server: lstat server: no such file or directory
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/elf.go:72 (0x12e8ac9)
        _getSharedLibs: return nil, errors.WrapPrefix(err, path, 0)
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/elf.go:134 (0x12e961d)
        getSharedLibs: libs, err := _getSharedLibs(targetRoot, path)
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/image.go:168 (0x12eae6b)
        BuildManifest: deps, err := getSharedLibs(c.TargetRoot, c.Program)
/Users/eyberg/go/src/github.com/nanovms/ops/lepton/image.go:24 (0x12e9d4f)
        BuildImage: m, err := BuildManifest(&c)
/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:220 (0x1354922)
        buildImages: err = api.BuildImage(*c)
/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:127 (0x1352cbb)
        runCommandHandler: buildImages(c)
/Users/eyberg/go/src/github.com/spf13/cobra/command.go:766 (0x1349d4c)
        (*Command).execute: c.Run(c, argWoFlags)
/Users/eyberg/go/src/github.com/spf13/cobra/command.go:852 (0x134a8ed)
        (*Command).ExecuteC: err = cmd.execute(flags)
/Users/eyberg/go/src/github.com/spf13/cobra/command.go:800 (0x134a5cb)
        (*Command).Execute: _, err := c.ExecuteC()
/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:667 (0x1359b5c)
        main: rootCmd.Execute()
/usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201 (0x102da97)
        main: fn()
/usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333 (0x1058de1)
        goexit: BYTE    $0x90   // NOP
```

**Comment by ExternalReality** [comment]
I can certainly go through and apply some error handling. Would it be fine to add an error handling package. How about logrus with a standard out format. Error messages would appear like

```
ERROR Image <filename> no such file or directory.
```
With logrus there would be the added flexibility of adding a logging formats with more detail for file and such which could be beneficial for more detailed debugging output.

**Comment by ExternalReality** [comment]
Also, for this particular issue, some input validation might be the appropriate route to take. What is happening here is the file path is being delivered way down into the build image code and when the error bubbles back up to a point where it could be handled it could be almost anything. It would be easier to provide the user with feedback if validation was done on input where errors can be easily identified and better human readable output can be produced.

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/239/commits

**Comment by tijoytom** [comment]
#235 already fixed this
