### ISSUE TITLE
disable spinner for pkg list

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#250]
this is just a small annoyance - it's good to have the spinner for large images but 1.4k json file we porb. don't need this..

![image](https://user-images.githubusercontent.com/22410/54560273-3592d400-497f-11e9-9b29-14e16de90dab.png)

**Comment by Regan-Koopmans** [comment]
@eyberg Am I correct in saying that this is now the command `ops manifest list`? Should this be timeout based, or download size based?

**Comment by eyberg** [comment]
this is kind of an old tkt

no, this is for the package repo list

```
➜  ~  rm .ops/packages/manifest.json
➜  ~  ops pkg list
Downloading.. https://storage.googleapis.com/packagehub/manifest.json
 100% |████████████████████████████████████████|  [0s:0s]
```

the manifest refers to the manifest each image has which contains the fs layout, env vars, etc.
