### ISSUE TITLE
need capability to download package but not immediately use it

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#251]
the 'package load' is a good exp to get going immediately but there are def. times when you want to just download a pkg and not immediately use it

**Comment by ExternalReality** [comment]
Just out of curiosity, what are those cases? Would it suffice to provide and option to `package list` that allows the user to view info on remote packages that may not yet be downloaded/cached.

**Comment by eyberg** [comment]
? maybe we'll talking about diff things here - this is simply a request to download a package but not immediately use it - right now the only option (that i'm aware of) is 'ops load' which downloads and immediately tries to run it but if i'm provisioning a box w/a handful of packages that I want available but have no need to run them there's no option right now other than to do 'ops load' and kill it after it downloads the pkg - if i'm deploying to a non-cloud env I might need a redis pkg, a python pkg and a few others - none of which i don't need to run immediately - i just want available

i personally run into this cause I was editing one - the only reason we have 'ops load' right now is cause it provides a one-command instant-experience

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/270

**Comment by eyberg** [comment]
excellent! thanks!
