### ISSUE TITLE
C/C++ package

### ISSUE THREAD

**Issue by beriberikix** [nanovms/ops#259]
Having a package with support for GCC and/or Clang would be great. Is that something y'all would consider?

**Comment by eyberg** [comment]
it kinda depends - for compiled languages the expectation is that we can load the raw binary itself but that's almost never the case cause it's going to be linked to a half dozen other libs that should be 'packaged' for portability - so in that case we look at on a case by case basis - if you have a particular application in mind we can def. look at creating a package for it

**Comment by eyberg** [comment]
closing this as we support any compiled c program - hope this answers the question?
