### ISSUE TITLE
fix .staging perms

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#263]
if we keep .staging (i don't see a reason too) it prob. needs diff. perms than the one I gave it as if you try to wipe the dir it complains cause of missing group perms

**Comment by eyberg** [comment]
@ssudake21 https://github.com/nanovms/nanos/pull/657

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/296/files

**Comment by ssudake21** [comment]
Closing issue as fixed by @eyberg
