### ISSUE TITLE
eval .staging use

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#265]
i don't see a strong use for this and prob needs to go away

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/263

**Comment by eyberg** [comment]
maybe can look into this and see why this is a thing and if we can get rid of it @fabioDMFerreira ?

**Comment by fabioDMFerreira** [comment]
.staging is used to store package content unzipped used on commands like `ops pkg describe`, `ops pkg contents`, `ops load` and `ops image create`.

I don't see any issue on extracting the package tarball directly to `~/.ops/local_packages` directory.
