### ISSUE TITLE
potential notes/usage section in package manifest

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#267]
there's been a few packages I've been playing with that had things like custom envs that we would not provide as default but the user would need to know to provide - i think it'd be useful to have some sort of notes section in the package format although we should be careful to distinguish between what would go in there vs what would go on the proposed packagehub microsite

**Comment by eyberg** [comment]
I just ran into this w/nginx - there are certain config options that would need to be put in to the nginx.conf file to make things work and since it's an expectation that the user is going to overwrite we need/want to give them an example

1) need an extra field in the manifest -- notes/description/readme - whatever you want to call it and I'd base64 or uuencode that cause there's guaranteed to be other shit inside of it that will screw w/the manifest

2) need a 'brew info' style command that can show information on the pkg

all in all - I'd view this as a temporary solution to whatever we turn the proposed pkghub into

**Comment by eyberg** [comment]
also as a note -- this should be a optional field for now

**Comment by eyberg** [comment]
actually I just thought @ssudake21 - another option here would be to just add a readme to the pkg root itself cause there's no reason why it needs to be in the manifest - the only thing that I would prob. do here is ensure that that readme doesn't end up on the resulting image which it shouldn't if it's outside of sysroot

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/288

**Comment by ssudake21** [comment]
@eyberg  should we close these with #308  checked in ?

**Comment by eyberg** [comment]
yes - thanks!
