### ISSUE TITLE
lifecycle mgmt policies

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#273]
for doing repeated image build/deploys (very common in many ci/cd circles) we'll need  a story for image lifecycle mgmt ala https://www.hashicorp.com/blog/zero-downtime-updates-with-terraform

this is slightly diff. than vanilla linux lifecycle mgmt since most operations ala apt-get happen after the instance is booted wheras if you change one line of code for existing cloud platforms you have to re-ul the image then create an instance from it

should address after https://github.com/nanovms/ops/pull/257 which is also blocked on an impending nanos fix

**Comment by eyberg** [comment]
i think a sane default here would be to just overwrite the image each time but as mentioned this is clearly a user definable format (just not something I think we care about in the near future)

**Comment by eyberg** [comment]
another lifecycle policy that would be good to have is retaining an elastic/static ip as instances roll in/out since a records will be pointing at those but most assuredly different images will be switched out

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/450

**Comment by fabioDMFerreira** [comment]
For the first version of ops lifecycles, we'll a new command to automate the required operations to deploy an instance with an updated image. 

The operations handled by the lifecycle command are:
- build an image;
- publish the image in a cloud provider (it may require to delete an image with the same name if it exists);
- start an instance using the image published;
- stop existing instances that are using the old version image (instances must be tagged with the image name, so we can identify the instances associated with the old image);
- optionally update a DNS record with the IP of the launched instance.

The command accepts next flags:
- config file path;
- target cloud provider;
- image name;
- program (binary executed inside nanos);
- domain (useful for single instances).
