### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mcandre** [nanovms/ops#282]
Given that Windows also features qemu support, could ops get a Windows port?

https://chocolatey.org/packages/Qemu

**Comment by eyberg** [comment]
hrm - there's prob. a little bit of windows specific file location stuff that needs to be worked out but I don't see anything that is too crazy

https://www.qemu.org/2017/11/22/haxm-usage-windows/

http://wiki.laptop.org/go/Talk:Using_QEMU_on_Windows

**Comment by eyberg** [comment]
now that we have initial hyper-v support - https://github.com/nanovms/ops/issues/547 - it makes a whole hell of lot more sense to add an official windows package

**Comment by eyberg** [comment]
as of master right now we need to add initial build support

```
# github.com/vishvananda/netns
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:27:13: undefined: syscall.Stat_t
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:28:12: undefined: syscall.Fstat
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:31:12: undefined: syscall.Fstat
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:39:8: undefined: syscall.Stat_t
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:43:12: undefined: syscall.Fstat
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:52:8: undefined: syscall.Stat_t
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:56:12: undefined: syscall.Fstat
..\go\pkg\mod\github.com\vishvananda\netns@v0.0.0-20190625233234-7109fa855b0f\netns.go:70:29: cannot use int(*ns) (type int) as type syscall.Handle in argument to syscall.Close
# github.com/nanovms/ops/lepton
lepton\image.go:268:15: undefined: getSharedLibs
lepton\onprem.go:213:8: undefined: syscall.Kill
lepton\qemu.go:413:13: undefined: hvSupport
```

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/601

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/issues/1274

**Comment by eyberg** [comment]
we originally were looking at mingw64 but I'm kinda thinking that we should just support WSL2 instead - i just built ops and it works fine, and if you start wsl w/permissions

```
Start-Process -Verb runas -FilePath wsl
```

you can easily interact with hyper-v from there..

```
powershell.exe Start-VM -name bob
```

**Comment by eyberg** [comment]
initial support for hyper-v was merged in and qemu's been working there forever
