### ISSUE TITLE
Support for more Linux flavors

### ISSUE THREAD

**Issue by mcandre** [nanovms/ops#284]
Very cool to see Debian/Ubuntu and Centos/Fedora supported! Any interest in testing, packaging for more Linux flavors? Alpine Linux, Void Linux, OpenSuSE, Arch, Gentoo?

**Comment by eyberg** [comment]
yes packages would be great to have - we can host them as well if needed

**Comment by ExternalReality** [comment]
I wouldn't mind maintaining an Arch and Manjaro package.

**Comment by eyberg** [comment]
- [ ] [arch](https://github.com/nanovms/ops/issues/1083)
- [ ] [rpm](https://github.com/nanovms/ops/issues/1082)
- [ ] [deb](https://github.com/nanovms/ops/issues/1081)

**Comment by eyberg** [comment]
debs && rpms now on gemfury: https://github.com/nanovms/ops/pull/1398
