### ISSUE TITLE
ability to list package contents

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#288]
you can simply untar it and tree the dir but it'd be nice to have this rolled up into a single command, some things to think about though:

* some interpreters like ruby/python have a lot of crap so a simple listing might not be best - maybe use paging? idk

* we have plans to hash everything inside the pkg at some point for integrity && verification - maybe that belongs in output as well

**Comment by ExternalReality** [comment]
`ops package show` and `ops package show | less` would cover both of the cases you mention (paging handled by less or some other Unix command).

One thing I notice is that `package` is becoming a theme so moving it to a sub command would be cool if that sort of thing is acceptable: `ops package list <pkg>`, `ops package show <pkg>`, `ops package get <pkg>`.

**Comment by eyberg** [comment]
i'm in favor of this although @ssudake21 is going to be doing work in this area in the coming days

**Comment by ssudake21** [comment]
@eyberg should we close these with #308 checked in ?
