### ISSUE TITLE
need ability to list local pkgs

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#314]
basically a command to see what is installed locally

there's ```ls ~/.ops/packages``` but we could do something like the installable list and make one for installed - maybe ```ops pkg list --local``` or something?

**Comment by skupr** [comment]
I'm not sure if I am talking about the same thing, but at least it's related. I'm having problems when I make packages - to test it via 'ops load', I need to copy it to packages/ and modify manifest.json
But when I do ops load, it loads manifest.json from cloud and overwrites the one I've created. To overcome that I've hacked ops locally.
It's most likely a separate issue, but something that I'ld like to be considered if we will be improving packages management in ops.

**Comment by eyberg** [comment]
yeh there's a small chk to see if the manifest is up to date but this is a diff issue - this is just a request to list what is locally installed - the assumption is that in the very near future ```ops list``` will be too large to make sense by itself

open to proposals on what you're working with as creating pkgs should be more democratic than it is right now
