### ISSUE TITLE
How create I need node version package?

### ISSUE THREAD

**Issue by xiaozitwo** [nanovms/ops#338]
The document use node version is node_v11.15.0,but i need v6.10.x to build projects. So how to create package?
thanks.

**Comment by prologic** [comment]
Just curious; why are you using NodeJS 6.x? It's ~3yrs old by now!

**Comment by eyberg** [comment]
creating a pkg is kind of an advanced power-user feature - there is some documentation here -> https://github.com/nanovms/ops/blob/master/PACKAGES.md - but basically you could in theory cp over one of the existing node pkgs && try replacing the binary && libs - if that works for you we'll be happy to add it to the registry for you as well (we have plans of making this self serve in the future)

in general we try to avoid supporting old releases (although if you really want/need it you can email us and we can discuss)

**Comment by leocavalcante** [comment]
I created a [small PHP script](https://github.com/leocavalcante/ops-packager/blob/master/pack) that packs PHP itself, the resulting folder is [this](https://github.com/leocavalcante/ops-packager/tree/master/php_7.3.5).

**But how could I load a local package?**

I tried to change the ~/.ops/packages/manifest.json adding:
```json
"php_7.3.5": {
    "language": "php",
    "runtime": "php",
    "version": "7.3.5",
    "md5": ""
  },
```
But it downloads the manifest file again and says that `package "php_7.3.5" does not exist`.

I tried to tricky ops by renaming my package to `php_7.2.13` and adding the `.tar.gz` at `~/.ops/packages/`, but then it halt with:
```
$ ops load php_7.2.13 -a test.php
[php test.php]
booting /mnt/c/Users/info/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
000000007f0006cc        (resolve_path + 0000000000000106/000000000000019d)
000000007f000d33        (startup + 00000000000004ac/0000000000000514)
000000007f0248b2        (_apply_startup + 0000000000000015/0000000000000017)
000000007f024aee        (runloop + 0000000000000034/000000000000004c)
000000007f024c65        (init_service + 0000000000000000/000000000000030a)
000000007f024f6f        (elf_symtable_add + 0000000000000000/00000000000001db)
000000007f00036a        (_start + 0000000000000005/0000000000000006)
assertion n failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/runtime/metadata.h: resolve_path() on line 44; halt
exit status 255
```

Am I missing something?

**Comment by eyberg** [comment]
@leocavalcante I think you are running into the same issue that @skupr ran into at https://github.com/nanovms/ops/issues/314 

i opened up https://github.com/nanovms/ops/issues/342 to help ease of use in building pkgs && https://github.com/nanovms/ops/issues/343 to look into this specific issue you are running into

in general - we should try to keep these issues sep. - i'm actually going to close this one as it was an informational request earlier

**Comment by leocavalcante** [comment]
Alright, thanks. I've subscribed to the new ones and I write to them on any news.
