### ISSUE TITLE
[Question]: Running NanoVM(s)

### ISSUE THREAD

**Issue by prologic** [nanovms/ops#341]
This is just a question; so feel free to close once answered. Let me know if this is not the appropriate medium.

---

I've been playing with `ops` (*the tool*) and NanoVM(s) (*mostly just simple Golang binaries so far on my Mac...*). So far works great!

What is the expectation around running NanoVMs in a production environment?
Is it expected that `ops` manage the VMs?
Are the requirements strictly bound to QEMU/KVM Hypervisors (*I think they are today?*)?
If NanoVMs were deployed to Cloud Providers such as DigitalOcean or AWS, would you be deploying one NanoVM per instnace or utilising `ops` to manage N NanoVMs per instance?

Thanks!

**Comment by eyberg** [comment]
eh not the best of place for questions like this but in general:

* nanovms - the product of the company is mostly for on-prem environments (eg: you have access to real servers under your control) and is built specifically for that - ops is more of the free/public-cloud side of things - that's the big difference

* very very little of ops is being utilized in nanovms today (although we are looking at ways of merging/opening more code) - ops will continue to be the preferred public cloud deploy tool

* other hypervisors - this is just a function of time/desire/money

* the preferred way of deploying to public clouds is 1vm=1instance and size it according to what you actually need (eg: t2.nano for simple go app vs quad-xlarge for a db)
