### ISSUE TITLE
add ability to use local dev-built pkgs

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#342]
right now when a user is trying to build a custom/new pkg or update an existing one they have to modify ops itself to use it cause there is a http request check to ensure that the manifest is up to date and then if an existing pkg exists it actually gets over-written

we need a way for devs to work on pkgs locally that are a) not present in the remote repo or b) differ

open to suggestions on this - maybe to start with a simple flag to disable the remote chk selectively??

@skupr @leocavalcante thoughts?

**Comment by leocavalcante** [comment]
Why does there is the [manifest changed check](https://github.com/nanovms/ops/blob/master/lepton/package.go#L52)?
Asking because the check [is only about the Content-Length](https://github.com/nanovms/ops/blob/master/lepton/package.go#L89), I changed the `php_7.2.13` to `php_7.3.13` then se length is the same, it doesn't re-downloads then:
```bash
packages> ops load php_7.2.13
package "php_7.2.13" does not exist
```

**Comment by eyberg** [comment]
it's supposed to be there to ensure that you always have the latest/greatest manifest since the intention is that we'll (not just us but everyone) will be continuously adding/removing/modifying pkgs

idk if the hack of changing the name is a sustainable method - for the record the lines that I changed briefly to look into this were the following ->

```
diff --git a/lepton/package.go b/lepton/package.go
index 5a3ad1c..15eee18 100644
--- a/lepton/package.go
+++ b/lepton/package.go
@@ -37,10 +37,10 @@ func DownloadPackage(name string) (string, error) {
        archivename := name + ".tar.gz"
        packagepath := path.Join(PackagesCache, archivename)
        if _, err := os.Stat(packagepath); os.IsNotExist(err) {
-               if err = DownloadFile(packagepath,
+       /*      if err = DownloadFile(packagepath,
                        fmt.Sprintf(PackageBaseURL, archivename), 600); err != nil {
                        return "", err
-               }
+               }*/
        }
        return packagepath, nil
 }
@@ -82,6 +82,7 @@ func GetPackageManifestFile() string {
 }

 func PackageManifestChanged(fino os.FileInfo, remoteUrl string) bool {
+    return false
        res, err := http.Head(remoteUrl)
        if err != nil {
                panic(err)
```

**Comment by leocavalcante** [comment]
What you think about a `--local` flag to the `load` command?
```bash
> ops load --local php_7.3.5 -a test.php
[php test.php]
booting /mnt/c/Users/info/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib/php/20180731/swoole (/usr/lib/php/20180731/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/swoole.so (/usr/lib/php/20180731/swoole.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
hello worldexit status 1
```

https://github.com/leocavalcante/ops/commit/3e77d2d10fa190bb88c06667bb0b851089748c56

Not sure if `local_packages` is a good name, but that's the idea that came up to my mind while trying to make my local php work.

**Comment by eyberg** [comment]
i think that would be fine for now - you could also call it 'dev' if the intention for it to be  uploaded/shared at a later time

**Comment by leocavalcante** [comment]
Cool! Tell me if you want a PR.

**Comment by eyberg** [comment]
go for it

**Comment by skupr** [comment]
I have few thoughts about packages management.
In general, I would do them closer to how OS package managers (rpm, deb) works:
- have one "remote" packages list (as is manifest.json now)
- also have "local" packages list - the same structure as remote, but managed separately, for ex. named manifest_local.json
Having this, we may add packages locally for dev purposes, not affecting main remote packages list.

Additional idea is that package.manifest should contain everything what is currently in manifest.json - it will simplify manifest.json management, as it can be then recreated from a set of packages.
This will help us later to manage multiple repositories, user-defined repostories etc.

These thoughts are more on internal side, for now, but after we agree on it, we may develop more consistent set of commands/flags to manage it.

**Comment by skupr** [comment]
A bit more explanation on having all data in package.manifest:
in particular, it will simplify installing development packages locally - we may have ops pkg subcommand like add or install which will place package and update manifest_local.json with info from package.manifest - then developer won't have to edit manifest.json manually, making development more straightforward

**Comment by leocavalcante** [comment]
Also, I was thinking, would be nice to load packages from whatever they are in the file system like:
```bash
$ ops load --local ~/projects/my_awesome_ops_pkg -a foo.bar
$ ops load --local /path/to/local_pkg -a foo.bar
$ ops load --local pkg_on_current_dir foo.bar
```
Will allow devs to place they working package development directory whatever they want.
