### ISSUE TITLE
tracking tkt for help w/ custom php 7.3.5

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#343]
I created a [small PHP script](https://github.com/leocavalcante/ops-packager/blob/master/pack) that packs PHP itself, the resulting folder is [this](https://github.com/leocavalcante/ops-packager/tree/master/php_7.3.5).

**But how could I load a local package?**

I tried to change the ~/.ops/packages/manifest.json adding:
```json
"php_7.3.5": {
    "language": "php",
    "runtime": "php",
    "version": "7.3.5",
    "md5": ""
  },
```
But it downloads the manifest file again and says that `package "php_7.3.5" does not exist`.

I tried to tricky ops by renaming my package to `php_7.2.13` and adding the `.tar.gz` at `~/.ops/packages/`, but then it halt with:
```
$ ops load php_7.2.13 -a test.php
[php test.php]
booting /mnt/c/Users/info/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
000000007f0006cc        (resolve_path + 0000000000000106/000000000000019d)
000000007f000d33        (startup + 00000000000004ac/0000000000000514)
000000007f0248b2        (_apply_startup + 0000000000000015/0000000000000017)
000000007f024aee        (runloop + 0000000000000034/000000000000004c)
000000007f024c65        (init_service + 0000000000000000/000000000000030a)
000000007f024f6f        (elf_symtable_add + 0000000000000000/00000000000001db)
000000007f00036a        (_start + 0000000000000005/0000000000000006)
assertion n failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/runtime/metadata.h: resolve_path() on line 44; halt
exit status 255
```

Am I missing something?

**Comment by eyberg** [comment]
@leocavalcante

i just tried out your pkg && while hw works it appears you need to include the 'swool' library in the location that it expects - not sure what that is used for or if it has other stuff beside the .so (it appears it might if so include the entire folder for it)

```
eyberg@s1:~/p$ ops load php_7.3.5 -a index.php
[php index.php]
booting /home/eyberg/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib/php/20180731/swoole (/usr/lib/php/20180731/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/swoole.so (/usr/lib/php/20180731/swoole.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
hello from php!exit status 1
```

```
eyberg@s1:~/php/ops-packager/php_7.3.5$ ldd php
        linux-vdso.so.1 (0x00007ffc821d3000)
        libargon2.so.0 => /usr/lib/x86_64-linux-gnu/libargon2.so.0 (0x00007fdc3e7d4000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fdc3e5b9000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdc3e39c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdc3e194000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdc3ddf6000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdc3dbf2000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fdc3d831000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fdc3d5c7000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fdc3d14f000)
        libpcre2-8.so.0 => /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007fdc3cecd000)
        libsodium.so.23 => not found
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdc3cadc000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdc3c8bd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdc3f070000)
        libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fdc3c506000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fdc3c2e0000)
        libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fdc3a737000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdc3a3a9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdc3a191000)
eyberg@s1:~/php/ops-packager/php_7.3.5$ grep -R swool *
sysroot/etc/php/7.3/cli/php.ini:extension=swoole
```

**Comment by leocavalcante** [comment]
Oh, yeah. I haven't included Swoole yet because I was trying to make it work with "raw" PHP first and I deliberately left it because, as you can see, PHP only warns about a missing extension, the "hello world" is printed out.
For me the output is completely different:
```bash
$ ops load php_7.2.13 -a test.php
[php test.php]
booting /mnt/c/Users/info/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
000000007f0006cc        (resolve_path + 0000000000000106/000000000000019d)
000000007f000d33        (startup + 00000000000004ac/0000000000000514)
000000007f0248b2        (_apply_startup + 0000000000000015/0000000000000017)
000000007f024aee        (runloop + 0000000000000034/000000000000004c)
000000007f024c65        (init_service + 0000000000000000/000000000000030a)
000000007f024f6f        (elf_symtable_add + 0000000000000000/00000000000001db)
000000007f00036a        (_start + 0000000000000005/0000000000000006)
assertion n failed in /home/eyberg/go/src/github.com/nanovms/nanos/src/runtime/metadata.h: resolve_path() on line 44; halt
exit status 255
```
I have only a `echo "hello world"` at `test.php`, not using Swoole yet.

I'm using Windows's WSL, maybe that?

**Comment by leocavalcante** [comment]
Also, you might find it interesting. I found about OPS after reading [this article](https://bootsity.com/php/running-php-unikernels-on-google-cloud), but it uses the PHP's built-in web server, while it works for demo purposes, it's not suitable for production environments, that's when [Swoole ](https://www.swoole.co.uk/) comes in, [it's really impressive](https://www.techempower.com/benchmarks/), maybe you find it interesting to package it for OPS officially.

**Comment by eyberg** [comment]
i don't think you can simply rename the pkg and it expect it to work - maybe you can try w/modifying ops to see if that works? - also - the error msg you are running into is a fs loading error - it's prob trying to load something that doesn't exist/not finding - i l doubt it's anything wsl related since it's during run-time and the vm has no notion of what the host is

i'm aware of the built-in webserver being hella slow - i'll throw swoole on the list to take a look at

**Comment by leocavalcante** [comment]
Ah! That's is the renaming hack isn't a thing indeed. I changed ops to use a local package then it works!

```bash
> ops load --local php_7.3.5 -a test.php
[php test.php]
booting /mnt/c/Users/info/.ops/images/php.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/lib/php/20180731/swoole (/usr/lib/php/20180731/swoole: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/swoole.so (/usr/lib/php/20180731/swoole.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
hello worldexit status 1
```

(I will present you the `--local` flag at #342)

**Comment by leocavalcante** [comment]
Endgame for Swoole, I guess.
```bash
[2019-05-18 18:03:01 @2.0]      ERROR   zm_deactivate_swoole (ERRNO 503):
Fatal error: Swoole\Server::start(): failed to start server.
Error: swPipeUnsock_create(:101): socketpair() failed,
Error: Function not implemented[38] in /swoole_hello_world.php on line 9
```
There is no Unix Domain Sockets, right?

**Comment by eyberg** [comment]
nightly release '-n' has some socketpair support - you should check that out - idk if that will get you further down the road or not - in general traditional ipc doesn't make a ton of sense for us, however, it doesn't mean that we can't support certain calls in certain form

**Comment by leocavalcante** [comment]
`-n` flag seams to make it go one step further, invoking `socketpair()`, but fails with `Socket type not supported`. Swoole uses `SOCK_DGRAM`.

**Comment by eyberg** [comment]
hello world is working w/latest nanos and I made a pkg here -> https://github.com/nanovms/ops-examples/tree/master/php/03-http-swoole (in all likelihood we'll rename this once we get naming schema more hashed out https://github.com/nanovms/ops/issues/351)  - there's a few other things I noticed that we can clean up in the nxt few wks as well

**Comment by leocavalcante** [comment]
Awesome! Thanks for this. I'll be studying more about unikernels to see how they can fit our stack, but I already liked the idea.

**Comment by eyberg** [comment]
closing this one for now cause original issue was solved
