### ISSUE TITLE
pkgs need maintainers attached them

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#345]
as we allow more user built packages there needs a way to link to state the maintainer - i'm not super keen on exposing emails but i'm not against it either - github usernames could be a crutch for now but again what if the user is a gitlab or non-git user? - also implications of whenever we front-end the bucket w/a micro-app

**Comment by prologic** [comment]
Why not take the same approach as Go did for packaging and imports? A package has a canonical URI. That URI *could* be a Github repository, Gitlab, Bitbucket, whatever. That points the user to whereever they need to go to find folks to talk to, get support or contribute to said package.

**Comment by eyberg** [comment]
well this is more about the maintainer vs the pkg, also - i wouldn't advocate putting these on github or gitlab or anything like that - they are largely composed of binary artifacts so if anything bintray would make more sense, lastly the concept of a pkg is not necessarily for end-user applications - it's more for software that is commonly used but you might not develop yourself - more along the lines of a deb/arch pkg

**Comment by eyberg** [comment]
new repo has taken care of this
