### ISSUE TITLE
ops recognizes there is a new nanos release but doesn't download

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#347]
ops seems smart enough to see that there is a new nanos version but doesn't download it - resulting in this error msg in which you have to blow away the entire dir to fix - kinda of a crappy exp

on that note - appears this is still not in -> https://github.com/nanovms/ops/issues/271

```
eyberg@s1:~/mc$ !1645
ops run -p 3333 -c config.json bob
error: /home/eyberg/.ops/0.1.14/stage3.img: stat /home/eyberg/.ops/0.1.14/stage3.img: no such file or directory
```

**Comment by eyberg** [comment]
on this note - i would imagine we don't want to force downloads upon people but it should at least prompt the user instead of failing like this

**Comment by eyberg** [comment]
i think the '-f' at one point used to force a download but that doesn't appear to be happening either 

```
➜  t  ops run -f t -p 8080
error: /Users/eyberg/.ops/0.1.16/stage3.img: stat /Users/eyberg/.ops/0.1.16/stage3.img: no such file or directory
```

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/271

**Comment by ssudake21** [comment]
Basically update behaviour changed now.

If user does not have any release of nanos we would download latest release of nanos.
After that,
if we have latest release than current version which user has we would just ask user to run `ops update`
`ops update` updates both ops cli and nanos to latest release
