### ISSUE TITLE
should not panic when service key is missing

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#362]
noticed that if you pass a service key that doesn't exist you just get a panic versus ops telling you the file doesn't exist

```
➜  itest  export GOOGLE_APPLICATION_CREDENTIALS=~/noexist.json
➜  itest   ops image create -c config.json -p mypkg
[packd]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x469ed20]

goroutine 1 [running]:
cloud.google.com/go/storage.(*Client).Close(0x0, 0x0, 0x0)
        /Users/eyberg/go/src/cloud.google.com/go/storage/storage.go:116 +0x20
```

it should tell the user the key doesn't exist if that's the case or at least say it doesn't have perms rather than crying about it

**Comment by eyberg** [comment]
we do have a check if the service key is not set - this is for inaccurate service keys (the user set it but the file doesn't exist)

```
error: GOOGLE_APPLICATION_CREDENTIALS not set.
Follow https://cloud.google.com/storage/docs/reference/libraries to set it up.
```

**Comment by francescolavra** [comment]
Actually, the check for the service key not being set works for "ops image list" but doesn't work for "ops image create": if I run ops image create without the GOOGLE_APPLICATION_CREDENTIALS environment variable, it panics in the same way as it does when the environment variable has an invalid value.
