### ISSUE TITLE
security groups && firewall rule for opening ports

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#364]
we should respect a config.json port setting when deploying by creating/modifying/updating/etc. a security-group/fw rule for said port - i don't believe either of these have recurring costs so you could conceivably add/remove as the instance is add/removed

right now we have a default of 80/443 cause it assumes web but if another port is specified in the config.json we should do the necessary sg/fw settings to pop the port open

I'd strongly prefer to keep this as simple as possible for now and then let the complexity grow as the needs arise - for now I think the idea is to allow non-http ports be popped w/out manual intervention

**Comment by eyberg** [comment]
i think it's also reasonable to pass optional port flags here to create sg's on the fly

**Comment by eyberg** [comment]
think we can close this one now @fabioDMFerreira ?

**Comment by fabioDMFerreira** [comment]
We are creating firewall rules on AWS, Azure and GCP.

We have this ticket https://github.com/nanovms/ops/issues/821 to add firewall rules in OpenStack and in VSphere. However, I think all ports are open in these cloud providers.

**Comment by eyberg** [comment]
closing
