### ISSUE TITLE
panic when passing an invalid flag argument

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#368]
this should just nicely error out and tell the user that it's incorrect

```
eyberg@box:~/loki$ ops run loki -p 9095 -p 3100 c config.json
Finding dependent shared libs
booting /home/eyberg/.ops/images/loki.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
panic: runtime error: index out of range

goroutine 1 [running]:
flag.init()
        /usr/local/go/src/flag/flag.go:964 +0x123
exit status 5
```

**Comment by fabioDMFerreira** [comment]
@arknable I think this error was caused because ops didn't find the program in the local machine.

Now, it isn't showing the output above but should show some message saying that the program doesn't exist.

**Comment by arknable** [comment]
@fabioDMFerreira ok

**Comment by arknable** [comment]
hmm actually it `ops` show stat error if `--show-errors` specified so probably not it.
```
arknable@arknable-x1c:~/.../issue_441$ $OPS run -c config.json main --show-errors
error: main: stat /home/arknable/.ops/main: no such file or directory
```

**Comment by arknable** [comment]
@eyberg could you please share that `loki` application for me to test ?

**Comment by arknable** [comment]
@eyberg oh sorry I understand now, the `c` argument is wrong

**Comment by arknable** [comment]
@eyberg hmm ... nope, I am having problem to reproduce this
```
arknable@arknable-x1c:~/.../issue_441$ $OPS run main -p 3120 -p 9999 c config.json
 100% |████████████████████████████████████████|  [1s:0s] 
booting /home/arknable/.ops/images/main.img ...
en1: assigned 10.0.2.15
Starting program...
/data: 0
Error writing data...
/data/out: 0
/data/out/test1.txt: 0
```
could you please share the `loki` program so I can have the same test case ?

**Comment by fabioDMFerreira** [comment]
@arknable It is important to provide feedback always. `--show-error` is supposed to show error details for debug purposes.

This is an old issue, prob. it was solved meanwhile. Currently, `ops run` seems to use only one argument and ignore the rest. The arguments in your example are `main, c and config.json`. In this case, I think it should show some warning message, so the user detects that the `c` and `config.json` flags are being ignored.

**Comment by arknable** [comment]
@fabioDMFerreira I see, ok I will add that and probably fix missing program error display in here also.
