### ISSUE TITLE
delete should use instanceid on gcp && aws

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#384]
right now gcp is using name cause name is unique on gcp but for aws tags are used for 'name' - both have the concept of instance id though so we should just show that in the instance listing as well

**Comment by fabioDMFerreira** [comment]
All other cloud providers are using the name instead of an ID. Although AWS allow having more than one instance/image with the same name we could use ops to prevent duplicated names.

Does it make sense to change the AWS implementation to use the name?
