### ISSUE TITLE
disk.raw Not found when creating image into AWS

### ISSUE THREAD

**Issue by francopeapea** [nanovms/ops#396]
I'm getting the following error when running the example with node js:

`.ops/images/disk.raw: no such file or directory`

I'm running the same command in the console with the basic hi.js provided

`ops image create -t aws -c config.json -p node_v11.5.0 -a hi.js`

and the same config.json changing my bucket name

**Comment by eyberg** [comment]
does https://github.com/nanovms/ops/pull/398 fix this for you?

**Comment by francopeapea** [comment]
No

`InvalidParameter: The sevice role <vmimport> does not exist or does not have sufficient permissions for the service to continue
	status code: 400, request id: 3bd4a51a-1237-4d1e-bbaa-bc93985b011e`

**Comment by eyberg** [comment]
i'm going to close this one and migrate this to a diff issue -> https://github.com/nanovms/ops/issues/399

seems like we didn't automate the addition of this policy for aws - gcloud is much less hassle
