### ISSUE TITLE
config.json not recognizing region for AWS image create

### ISSUE THREAD

**Issue by francopeapea** [nanovms/ops#397]
The following config.json is not recognizing the region change

`{
    "Files": ["hi.js"],
    "CloudConfig" :{
        "ProjectID" :"test-nanovm",
        "Zone": "us-east-1",
        "BucketName":"test-nanovm"
    }
}
`

`BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region at endpoint ''
	status code: 301, request id: , host id:`

**Comment by eyberg** [comment]
looks like at leas these two need to be read in from config

https://github.com/nanovms/ops/blob/master/lepton/s3.go#L21

https://github.com/nanovms/ops/blob/master/lepton/s3.go#L54

**Comment by eyberg** [comment]
this was fixed in #425
