### ISSUE TITLE
automate installation of vmimport role

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#399]
guess we left off vmimport role in the instructions/code

https://docs.aws.amazon.com/vm-import/latest/userguide/vmimport-troubleshooting.html

if we can automate this we should but at the very least there should be instructions for adding it if we detect that it's not there

trust relationship ->

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "vmie.amazonaws.com"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:Externalid": "vmimport"
        }
      }
    }
  ]
}
```

policy ->

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::my-bucket",
                "arn:aws:s3:::my-bucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:ModifySnapshotAttribute",
                "ec2:CopySnapshot",
                "ec2:RegisterImage",
                "ec2:Describe*"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by francopeapea** [comment]
You shouldn't be assuming the role, instead, you should use aws credentials of the current user, someone with limited permissions or with full permissions but IAM won't be able to run anything, because they should also be able to create a role in their policy and not all companies will have a user with:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:CreatePolicy",
                "iam:CreateRole",
                "iam:GetPolicy",
                "iam:GetRole",
               "iam:GetRolePolicy",
               "iam:ListPolicies",
               "iam:ListRoles",
               "iam:PutRolePolicy"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}

Also not every company will like a program that will be creating roles for them, which they are not tracking, instead, they have a certain amount of roles or they keep track of their roles and limit them to specific things/services/tags/etc

**Comment by eyberg** [comment]
this role is not attached to a given user - it's for an internal aws service - vmie.amazonaws.com

**Comment by eyberg** [comment]
I think the correct behavior here would be to try and create the role automatically for a given bucket if it's not found and if it can't then it should tell the user that they need to

**Comment by francopeapea** [comment]
this is because the service is creating it, not my user, just checked, thank you

**Comment by eyberg** [comment]
fixes https://github.com/nanovms/ops/pull/401 although there's a minor inconvenience that sometimes the role/policy creation happens too fast so the first time fails - might be worth throwing in a few seconds of sleep or maybe there is a waiter that we can use to verify it's propagated

**Comment by eyberg** [comment]
when looking into https://github.com/nanovms/ops/issues/397 i don't think it's possible to have multiple vmimport roles - so if one is already present it should just add the new bucket to it and update (if you are using multiple buckets which you will be if you are doing multiple regions)

**Comment by eyberg** [comment]
this was put in
