### ISSUE TITLE
optional debug loglevel

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#400]
there's lots of useful debug output that gets thrown away w/underscores - we might want to craft in a debugging output loglevel rather than trash the output of some of the requests

**Comment by eyberg** [comment]
there's also a lot of random debug output that is currently being cat out that probably doesn't belong unless a debug loglevel is shown

**Comment by eyberg** [comment]
in addition to debug log level it would prob. be good to have a warning log level as well

we have quite a few warnings (which some ppl might wish to have silenced) but prob. should be on by default and then we have quite a few places in the code where it would be worthwhile to have debug output that should only be turned on at the bequest of a dev

**Comment by fabioDMFerreira** [comment]
There are two libraries we can use:
* https://github.com/sirupsen/logrus
* https://github.com/uber-go/zap

We can also create our own logging module.

**Comment by eyberg** [comment]
I wasn't really looking for anything extensive - just a way to separate warnings from errors from debug output
