### ISSUE TITLE
ops run startup time

### ISSUE THREAD

**Issue by prologic** [nanovms/ops#410]
What is the difference between `ops run` and running the resulting image with `qemu-system-x86_64`? Why is `ops run` taking an extra ~1.5s per call even when you tell it not to do any rebuilding with `-s`? For example:

```
james@Jamess-MacBook-Pro
Fri Nov 01 13:52:42
~/tmp/nanovms/hello
 1
$ time ops run -d -s -x -v main
booting /Users/james/.ops/images/main.img ...
qemu-system-x86_64 -drive file=/Users/james/.ops/images/main.img,format=raw,if=none,id=hd0 -device virtio-blk,drive=hd0 -device virtio-net,netdev=n0 -netdev user,id=n0 -accel hvf -cpu host -nodefaults -no-reboot -device isa-debug-exit -m 2G -display none -serial stdio
assigned: 10.0.2.15
Hello World!
exit status 1

real	0m1.686s
user	0m0.121s
sys	0m0.149s

james@Jamess-MacBook-Pro
Fri Nov 01 13:52:46
~/tmp/nanovms/hello
 0
$ time qemu-system-x86_64 -drive file=/Users/james/.ops/images/main.img,format=raw,if=none,id=hd0 -device virtio-blk,drive=hd0 -device virtio-net,netdev=n0 -netdev user,id=n0 -accel hvf -cpu host -nodefaults -no-reboot -device isa-debug-exit -m 2G -display none -serial stdio
assigned: 10.0.2.15
Hello World!

real	0m0.171s
user	0m0.062s
sys	0m0.113s
```

Curious where the time is being spent and if we can optionally skip / optimize some of this?

**Comment by eyberg** [comment]
be aware the '-d' turns on debugging (and prob. ignores -s) - for a simple hello world in c I get around 600ms w/ or w/out -s - if you're looking to do the faster boot times - it'd prob. need to bypass ops and interact more directly w/the hypervisor of choice - there's def. room for a diff. tool/framework wrt that - we have open tkts for firecracker integration but no one has expressed enough interest to work on it

https://github.com/nanovms/ops/issues/77
https://github.com/nanovms/nanos/issues/483

**Comment by eyberg** [comment]
i'm going to close this tkt now since we have initial firecracker integration now working - i think this obviates any slowness by using ops to orchestrate qemu
