### ISSUE TITLE
example fail with nodejs 12.13.0

### ISSUE THREAD

**Issue by iwater** [nanovms/ops#435]
<img width="547" alt="屏幕快照 2019-11-28 下午5 22 45" src="https://user-images.githubusercontent.com/108937/69793646-d79fd700-1203-11ea-99e4-de298a1f3caf.png">

```
cat ex.js 
console.log("Hello World!");
```

that works with nodejs 11.5.0

**Comment by eyberg** [comment]
hey @iwater - i believe you are running into this issue - https://github.com/nanovms/ops/issues/403

there are 2 ways around it:

1) run with hardware acceleration (-x)

or 

2) upgrade qemu

what version of qemu are you running?

```
 qemu-system-x86_64 --version
```

we added a homebrew recipe to install the latest qemu on osx https://github.com/nanovms/ops/pull/418/files but it looks like you are on linux? if so you can download && build from here -> 
https://www.qemu.org/download/#source

we have a few tkts to ensure warnings are popped if we detect it in the future

https://github.com/nanovms/ops/issues/407

**Comment by iwater** [comment]
QEMU emulator version 4.1.1 @ Ubuntu 16.04.6 LTS
-x fail as above

**Comment by eyberg** [comment]
'-x' should work if you have privileges - maybe try w/sudo?

the version of qemu you have is known to have a problem with the TCG (tiny code generator) - upgrading to latest 4.2.0 fixes that but '-x' w/sudo should work

**Comment by iwater** [comment]
yeah, sudo with -x or qemu-4.2.0-rc3 works as expected
