### ISSUE TITLE
Wrong check for /dev/kvm permissions

### ISSUE THREAD

**Issue by nirs** [nanovms/ops#440]
Using --accel fails on Fedora 30, complaining about user not in "kvm" group:

```
./ops run --accel -v hi
booting /home/nsoffer/.ops/images/hi.img ...
You specified hardware acceleration but you don't have rights.
Try adding yourself to the kvm group: `sudo adduser $user kvm`
You'll need to re login for this to take affect.
```

But /dev/kvm is accessible:
```
$ ls -lh /dev/kvm
crw-rw-rw-. 1 root kvm 10, 232 Dec 16 21:46 /dev/kvm
```

So the same command succeeds outside of ops:

```
$ $ qemu-system-x86_64 -drive file=/home/nsoffer/.ops/images/hi.img,format=raw,if=none,id=hd0 -device virtio-blk,drive=hd0 -device virtio-net,netdev=n0 -netdev user,id=n0 -nodefaults -no-reboot -device isa-debug-exit -m 2G -display none -serial stdio -enable-kvm -cpu host
assigned: 10.0.2.15
yo!
```

A better way to handle this would be to use:
````
-machine accel=kvm:tcg
````
So in the worst case there is a fallback to emulation, but the command does not fail.

Or use access() to check the permissions:

```
>>> os.access("/dev/kvm", os.R_OK | os.W_OK)
True
```

**Comment by eyberg** [comment]
thanks for the report, agreed this is a better method - didn't know about that fallback option

**Comment by jevgeniShupilov00** [comment]
On Ubuntu 20.04 vm-ware, I'm getting a general protection fault issue.
```
cpu: 0
 interrupt: 000000000000000d (General protection fault)
     frame: ffff800001460000
error code: 0000000000000000
```
Is it impossible to run ops on vmware? 
When runs qemu in outside of ops, it works for me

**Comment by eyberg** [comment]
@jevgeniShupilov00 you won't be able to turn on kvm in vmware w/out nested virtualization turned on - tbh i have no clue if that is supported as it's not really something that we would support, this task kinda requires access to a real linux box

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/629
