### ISSUE TITLE
"ops list" command does not exist

### ISSUE THREAD

**Issue by CraigCottingham** [nanovms/ops#442]
The `ops` documentation at https://nanovms.gitbook.io/ops/basic_usage#load-vs-run says to run `ops list` to get a list of available packages.

The output of `ops --help` includes

>   load        load and run a package from ['ops list']

However, `list` isn't one of the commands shown in `ops --help`, and running `ops list` nets

```
Error: unknown command "list" for "ops"
Run 'ops --help' for usage.
```

**Comment by eyberg** [comment]
thanks!

old docs -- it's ```ops pkg list``` now

https://github.com/nanovms/ops-documentation/issues/71

feel free to open a pr there

**Comment by CraigCottingham** [comment]
PR created: https://github.com/nanovms/ops-documentation/pull/72
