### ISSUE TITLE
gcloud default image lifecycle should mimic aws

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#450]
right now you can repeatedly hit the deploy button aws and since it's tagged and sorted by created_at it's smart enough to use the latest image that one pushed

gcloud is currently not set up like that - you have to delete the image first then create a new one which sucks for rollbacks/canaries/blue/green/etc. && in general is an extra step that is not necessary

**Comment by fabioDMFerreira** [comment]
`ops deploy` automatically replaces the old image
