### ISSUE TITLE
ops should dbl quote all property/value strings in manifest

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#454]
'#' is a reserved character (as well as '(', ')', '[', ']', ':', '|' ) in mkfs manifests (for comments) - need to just double-quote everything (and escape? existing quotes)

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/tree/quoteManifest exists, however, as noted I think this should all be encoded - maybe turning mkfs itself into a library or something (although afaik that's tightly coupled to tfs internals right now..)

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/484

**Comment by francescolavra** [comment]
This can be closed, ops no longer uses the mkfs binary to create images and so doesn't have to create a manifest file anymore.
