### ISSUE TITLE
ops instance create should take <image_name> as argument not flag

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#464]
it's required and it makes more sense (instance start does the same although w/instance_name

**Comment by eyberg** [comment]
I think you just fixed this @fabioDMFerreira ?

**Comment by fabioDMFerreira** [comment]
We're using the first argument to set a custom name to the instance. For example, the next command creates an instance with the name `app`.
```sh
ops instance create app -i web-server
```

If we do not specify the argument ops uses image name with the unix time as the instance name. For example, the next command creates an instance with the name format `web-server-1617281161`
```sh
ops instance create -i web-server
```

**Comment by fabioDMFerreira** [comment]
We could create a flag to specify the instance name and use the argument for the image name instead. The existing `ops instance` commands (delete, stop, start and logs) use the instance name as the first argument though.

**Comment by kalyanGK1** [comment]
Hi guys,

I'm getting below error while creating instance

cmd:- 

ops instance create server -c config.json -t aws -z ap-south-1 -i server-image --port 8080 -f t2.small

error:-

Created security group sg-0c0862f7ed50f6eb4 with VPC vpc-0437e86c.
Could not create instance
%!(EXTRA *awserr.requestError=Unsupported: Your requested instance type (t2.small) is not supported in your requested Availability Zone (ap-south-1c). Please retry your request by not specifying an Availability Zone or choosing ap-south-1a, ap-south-1b.
        status code: 400, request id: d7ca9e1a-c7fe-417a-adc0-f7fec9dbcc67)Unsupported: Your requested instance type (t2.small) is not supported in your requested Availability Zone (ap-south-1c). Please retry your request by not specifying an Availability Zone or choosing ap-south-1a, ap-south-1b.
        status code: 400, request id: d7ca9e1a-c7fe-417a-adc0-f7fec9dbcc67

**Comment by eyberg** [comment]
@kalyanGK1 you are specifying it right but the error message you are seeing means that aws prob want's a zone selection as well - did you try the suggestion of using ap-south-1a or ap-south-1b? 

you can see which instances are avail for which region/zone with this command ->

```
aws ec2 describe-instance-type-offerings --location-type availability-zone  --filters Name=instance-type,Values=t2.small --region ap-south-1
```

also in the future can you open a new issue as this doesn't seem related to this issue
