### ISSUE TITLE
add DO deploy target

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#468]
https://github.com/nanovms/nanos/issues/614

i thought we were blocked on a text vga driver but that looks like it got added a while back ago - so prob. is very deployable

**Comment by eyberg** [comment]
just manually tried this as well and it works just fine - they have snapshots but can directly upload images as well so we should use that instead

**Comment by eyberg** [comment]
https://github.com/nanovms/ops-documentation/issues/82

**Comment by eyberg** [comment]
have https://github.com/nanovms/ops/tree/digitalocean open but the spaces api seems to have trouble w/pre-signed urls (both theirs and others) (public urls seem fine)

**Comment by eyberg** [comment]
from the horse's mouth -> https://blog.digitalocean.com/custom-images/

"When uploading via URL, make sure that the URL ends in a file name, such as www.digitalocean.com/image.raw as opposed to a masked URL such as www.digitalocean.com/image.raw?example as we check the file name before uploading." <-- afaict this effectively rules out private images for now unless done manually

**Comment by eyberg** [comment]
i did write their support and they acknowledged that it is a problem and asked for me to add to their uservoice

https://ideas.digitalocean.com/ideas/CPX-I-11

as mentioned in this comment screen-scraping is not out of the question to upload to their private bucket - "prod-byoi" - in the portal they create a pre-signed upload url, then stuff it into this bucket for import; we could conceivably take that route but let's see if they can make this trivial change first

**Comment by fabioDMFerreira** [comment]
The issue with creating images with a signed URL is not solved yet.

In #894 we set a policy to allow the image to be imported from spaces and then we delete the image file in spaces.
