### ISSUE TITLE
consider stuffing ops/nanos versions into env vars

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#480]
right now if 'trace' is set in the nanos manifest you'll get the git version of nanos (although this currently turns on other tracing mechanisms as well)

we could also infer at build-time what nanos/ops versions are being used and stuff those into env vars

**Comment by jevgeniShupilov00** [comment]
I have made a changes for this ticket. Please allow me to update changes on this repository. I have no any permission to write changes into this repository.

**Comment by EduardGaifutdinov** [comment]
Ready to do it.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/637
