### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by dantodor** [nanovms/ops#496]
Hello!
I'm not sure that this is the right place to ask, so please excuse me if I'm wrong and please direct me to the right place :)

I'm trying to run the simple http server from the doc. Ubuntu 18.
When build and run via ops, first I get a warning:
`qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]`
Then it bombs out.
I'm getting back this:
`signal 23 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag`

I can paste the full stack trace if needed... Any hints on what I'm doing wrong ?
Thanks!

**Comment by eyberg** [comment]
1) you can ignore the first line

2) the second line - this looks like you are running a go 1.14 program? there was a change from go 1.13 to 1.14 but was fixed here https://github.com/nanovms/nanos/commit/1171dea3ea30619eb1f7264ecd03b27074074901

to run this you can use the 'nightly' build of nanos via ```ops run -n``` - lmk if that fixes it for you

**Comment by dantodor** [comment]
Yes, it works with nightly. Thanks a lot for your help!
