### ISSUE TITLE
ops image create should be able to consume from ~/.ops/images rather than forcing a pkg or the elf in cwd

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#502]
this has been brought up a few times

right now there is an assumption that images are built on-demand - this works for quite a few purposes - you either pass it a package name or your binary, however there is a need in some cases to copy the image around and then deploy it w/out having access to the original binary/pkg/build env

packages aren't actually disk images - they are templates to build disk images from

```ops load``` && ```ops image``` create disk images on the fly

support for running pre-made images exists when running locally via:

```
ops instance create -i myimage -t onprem
```

but we are currently missing support for public cloud deploys

what is needed is a way for

```
ops image create
```

to be passed a locally stored image (found in ~/.ops/images) and use that instead of the mandatory pkg/binary for public cloud deploys

cc @mildmelon && @Dmitry-N-Medvedev

**Comment by eyberg** [comment]
i thought about this and I think the appropriate thing to do here (at least for now) is more of an 'ops image sync' where we simply have the ability to transfer an existing disk image to a particular cloud provider - no mutation - that should be relatively straight-forward to do and won't add to the flag confusion that already exists, create implies that you can manipulate the image w/new data which if you are going to do that then just use image create as-is, that does require access to the original binary/pkg though

**Comment by eyberg** [comment]
@mildmelon && @Dmitry-N-Medvedev i think #645 gets you the deploys but if something is missing let us know and we can take another look

**Comment by mildmelon** [comment]
@eyberg Looks great, seems like that PR covers this issue. I'll close my previous PR.
