### ISSUE TITLE
empty dirs not being created w/in a pkg (but ok if just using ops run)

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#504]
i haven't quite confirmed this but it seems that when an empty directory exists w/in a package (eg: /tmp) it doesn't get created when running ```ops load``` but if you specify an empty directory for config.json w/```ops run``` it does

**Comment by eyberg** [comment]
possibly related to https://github.com/nanovms/ops/issues/441

**Comment by eyberg** [comment]
maybe related to https://github.com/nanovms/nanos/commit/99536f0becd1d194400194002e45676e702fd880

**Comment by francescolavra** [comment]
I don't think it's related to that Nanos issue, since that only affects programs running on top of Nanos.
Most likely this has to do with ops generating a flawed manifest file.

**Comment by arknable** [comment]
I can confirm that empty directory inside package folder is not created in the image, but if I put any file inside that empty folder, it will be created.
