### ISSUE TITLE
build a node 14.1.0 pkg

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#506]
https://github.com/nanovms/ops-examples/issues/40

**Comment by Dmitry-N-Medvedev** [comment]
since the latest node gets a lot of updates ( it is version 14.2.0 right now ) it would be handy if a new package for the most current node version gets built almost as soon as the new version is released.

I have a docker task for this. should I publish it somewhere?

**Comment by eyberg** [comment]
agreed, we have plans to make the main pkg repo a lot better but it's been low priority and right now it's mostly manual work, also some pkgs could be built automatically - others can't - if you have interest in contributing to publicly available packages we'd need to hit up a few tkts like https://github.com/nanovms/ops/issues/345 first

i guess on this note until we hash all that out - I'm definitely not opposed to listing community packages somewhere in a wiki or even in the readme of this repo, i think the more people contributing the better

**Comment by eyberg** [comment]
I built 14.2.0 instead
