### ISSUE TITLE
not specifying manifest via cli flag '-m' w/ops run seems to override what is in config.json

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#512]
config should take precedence when  '-m' is empty

**Comment by Regan-Koopmans** [comment]
Hi @eyberg , just want to confirm that I understand the requirement correctly. Given that I have a config file as such:

```json
{
    "Files":["hello"],
    "Args":["hello"],
    "RunConfig": {
        "Memory": "1G"
    }
}
```

When I run `ops run -v -c config.json hello` this yields:

```
qemu-system-x86_64 -machine q35 ... -m 1G ...
```

As we would expect. Is there a specific configuration variable that you tested with?

**Comment by eyberg** [comment]
yeh i prob should've included an example, not sure what it was off the top of my head

**Comment by eyberg** [comment]
fixed via https://github.com/nanovms/ops/pull/674
