### ISSUE TITLE
No hypervisor found on $PATH on Ubuntu 20.04.

### ISSUE THREAD

**Issue by charlesmorris5** [nanovms/ops#525]
I'm experiencing this issue on Ubuntu 20.04.
1. Installed qemu with [sudo apt install qemu] qemu version (1:4.2-3ubuntu6.1)
2. Installed ops with [curl https://ops.city/get.sh -sSfL | sh] ops version (0.1.10), nanos version (0.1.25)
Following the "getting started" guide results in "No hypervisor found on $PATH" error
I did note that my profile does not have a .bash_profile; it does have .bashrc
I also noted that additional installations of ops with curl add additional [#OPS config] entries in .bashrc; it looks like it's trying to update the path in the correct file for Ubuntu 20.20.

_Originally posted by @charlesmorris5 in https://github.com/nanovms/ops/issues/133#issuecomment-639696971_

**Comment by eyberg** [comment]
I think ubuntu 20.04 qemu pkg is ```sudo apt-get install qemu-system-x86```

**Comment by charlesmorris5** [comment]
I see, it looks like qemu doesn't install qemu-system-x86_64.
Fixed with [sudo apt install qemu-system-x86_64].
I reran the go "Hello World" and it's good to go.
Thank you!!!

**Comment by shravanshetty1** [comment]
Should probably check dependencies in the install script - encountered the same error
