### ISSUE TITLE
add hyper-v support

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#547]
we have initial hyper-v support @ https://github.com/nanovms/nanos/pull/1210

apparently azure has a modified version of this and utilizes at least one diff. driver (storvsc) so we'll separate them as two different target platforms

i think we should prob. just default to hyper-v if platform is detected as windows espc. since hardware accel w/qemu on windows requires haxm

**Comment by mkhon** [comment]
@eyberg we should configure storvsc everywhere (Azure, bare Hyper-V)

**Comment by eyberg** [comment]
go lib to interact w/local hyper-v:

https://godoc.org/gopkg.in/mitchellh/packer.v0/common/powershell/hyperv
https://github.com/myaNote/HyperVWebViewer/blob/master/hyperVWebViewer.go

**Comment by am11** [comment]
Could you give some pointers how the VM was created during testing?
In Windows 10 PC, I tried:

```sh
# from elevated PowerShell or CMD instance, enter some WSL2 distro
$ wsl -d ubuntu-20.04

# compile some code for myApp
$ gcc -xc -o myApp - << EOF
#include <stdio.h>
int main(void)
{
  printf("Hello from nanos!\n");
  return 0;
}
EOF

$ ops version
Ops version: 0.1.19
Nanos version: 0.1.31

# create image targeting Hyper-V
$ ops build -t hyper-v myApp
Bootable image file:/home/am11/.ops/images/myApp.img
# looks like it's missing a line like:
# Disk Image eXtended file: /home/am11/.ops/vhdx-images/myApp.vhdx

# because it was also generated as part of the previous command (took some time to realize it's there)
$ file ~/.ops/vhdx-images/myApp.vhdx
/home/am11/.ops/vhdx-images/myApp.vhdx: Microsoft Disk Image eXtended, by QEMU v4.2.1, sequence 0x133544ae, NO Log Signature; region, 2 entries, id BAT, at 0x200000, Required 0, id Metadata, at 0x300000, Required 0
```


when I created a VM in Hyper-V out of this `myApp.vhdx` (new VM > select myApp.vhdx as hard drive), it refused to boot:

![image](https://user-images.githubusercontent.com/3840695/109402576-94c93380-795f-11eb-968a-231ed3845ec8.png)

**Comment by eyberg** [comment]
cc @fabioDMFerreira

I can't chk right now but maybe fabio can chk monday

generally speaking you'll want to use 'ops instance create' when creating the vm - the first command just creates the disk image - typically there are other settings and such that have to be done as well

I noticed we don't have any of this in the docs yet so I added an issue for that ->

https://github.com/nanovms/ops-documentation/issues/170

**Comment by fabioDMFerreira** [comment]
@am11 your steps seem fine.  You should be able to launch the virtual machine in Hyper-v if you are creating it from the image generated by ops. Anyway, I recommend using the next ops command to create the virtual machine.

```
$ ops instance create -t hyper-v -i MyApp
```

Soon the hyper-v documentation will be updated (https://github.com/nanovms/ops-documentation/pull/171).

**Comment by fabioDMFerreira** [comment]
And, yes we need to update the image path after creating the image. Thanks for pointing that ;)

**Comment by am11** [comment]
Thanks! The manually created VM was Generation 2 (which uses SCSI Controller) and ops-instance-create creates older Generation 1 (which uses IDE Controller). Nanos VM work with the IDE controller but for some reason, not the SCSI.

BTW, I had to rename my network connection from `Wi-Fi` (default on my PC) to `WiFi`. I think we can simplify this filter https://github.com/nanovms/ops/blob/cf4f8c5cc5079d9ebba0b59614257518dd55a4d4/hyperv/hyperv_api.go#L292-L295 as:
```diff
- $names = @('Ethernet','WiFi','Lan')
- $adapters = foreach ($name in $names) {
-   Get-NetAdapter -Physical -Name $name -ErrorAction SilentlyContinue | where status -eq 'Up'
- }
+ $adapters = Get-NetAdapter -Physical -ErrorAction SilentlyContinue | where status -eq 'Up'
```

**Comment by eyberg** [comment]
we can definitely look at adding scsi there as it'll be much faster - we have scsi on kvm and other platforms - as for the go/poweshell stuff - that's ok too - happy to accept any prs

**Comment by am11** [comment]
For some reason, I can't see `printf`'d string from C application in the Hyper-V's console, but adding some delay suggests that 'it is actually running the code'. 🙂

```sh
$ gcc -xc -o myApp - << EOF
#include <stdio.h>
#include <unistd.h>

int main(void)
{
  printf("Hello from nanos!\n"); // <-- never gets printed in the console
  sleep(15); // 15 seconds delay before VM shuts down
  return 0;
}
EOF

$ ops build -t hyper-v myApp
$ ops instance create myApp1 -i myApp -t hyper-v
```

then I popped out the Hyper-V console and noticed that for exactly 15 seconds, the caret flickered then the screen shutdown.
(however, the `hi.js` example node.js app from the readme, showed the `Server running at http://127.0.0.1:8083/` string just fine)

**Comment by francescolavra** [comment]
@am11 printf output not being shown on the console is most likely due to it being buffered by glibc. To disable this buffering, you can call `setbuf(stdout, NULL)` in your C program.

**Comment by am11** [comment]
`setbuf` did the trick 👍
