### ISSUE TITLE
add openstack (nova/swift) support

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#559]
https://github.com/nanovms/nanos/issues/336

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/issues/1225

**Comment by eyberg** [comment]
https://github.com/nanovms/nanos/pull/1277 enables for older hardware

**Comment by eyberg** [comment]
it's not really done but i merged the first bit of support for this in https://github.com/nanovms/ops/pull/627

**Comment by eyberg** [comment]
I think creatInstance still needs to be fleshed out - you can upload an image through ops to swift and manually creating an instance through horizon, I think @mkhon had mentioned to *not* attach a volume but I think that's how I'm creating them on vexxhost

**Comment by mkhon** [comment]
@eyberg not attaching a volume was the hint for your private OpenStack installation which does not have proper cinder configuration. On a properly configured OpenStack you can use any volumes (both locally allocated and network).

**Comment by eyberg** [comment]
base support is now in for creating images && instances, closing this one
