### ISSUE TITLE
Java unikernel does not acquire stdin

### ISSUE THREAD

**Issue by Regan-Koopmans** [nanovms/ops#567]
This might be a qemu configuration issue, but a standard Java application cannot read from `System.in`. When using a `Scanner` this results in a `NoSuchElementException`, and a `BufferedReader` simply emits null. 

Has anyone managed to get basic input working for Java applications?

For reference, I have been using this dummy Java application for testing:

```java
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

class Hello {

	public static void main(String[] args) throws Exception {
		try {
			System.out.println("\n\nSuccessfully booted into operating system.");
			System.out.println("Press any key to boot down.");
			System.out.flush();
			BufferedReader reader =
			new BufferedReader(new InputStreamReader(System.in));
			String line;
			while((line = reader.readLine())==null) {

			}
			System.out.println(line);
		} catch (Exception e) {
			System.out.println(e);
			Thread.sleep(10000);
		}
	}
}
```

**Comment by eyberg** [comment]
we don't support interactive functionality lik this; you'd want to either pass in whatever input you want in your args array or read from the network or a file or something but no interactive stuff is supported
