### ISSUE TITLE
azure deployments seem to never finish the 'deploy' cycle even though they work

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#569]
I think it's cause it forces the ssh keys or l/p to be injected which obv. isn't happening, idk how big of a deal it is or if msft will give a crap - just something to note for right now

**Comment by eyberg** [comment]
I think this was fixed @fabioDMFerreira && @francescolavra w/ the cloud_init klib? as long as that is being loaded on demand for azure && support in we can close?

**Comment by francescolavra** [comment]
Yes, the cloud_init klib is being loaded for azure (#801), we can close.
