### ISSUE TITLE
AWS t3 and t3a instance type doesn't appear to boot up/work with nano kernel

### ISSUE THREAD

**Issue by bobhenkel** [nanovms/ops#575]
I did a little digging and the T3 family of EC2 runs on Nitro HyperVisor https://aws.amazon.com/ec2/nitro/.  It probably makes sense this doesn't work as it's not xen or kvm.  Is this something that is possible to add support for in the future?

Here are my initial findings before I realized that correlation of the instances not booting correctly had to do with them being on a nitro HyperVisor.

- t2 nano (Intel Xeon) launches just fine I can curl my app REST endpoint before the 2 health checks are even completed in the AWS web console.
- t2 micro works just fine too.
- t3 nano (T3 instances feature either the 1st or 2nd generation Intel Xeon Platinum 8000 series processor (Skylake-SP or Cascade Lake)). When I try and launch the same AMI that I did with the t2 the VM launches but I can never curl my REST endpoint and the 2 status checks AWS does on all instances says initializing for 15 to 30 minutes after which 1 of the status checks passes but I still can't curl the instance.
- t3a nano (AMD EPYC 7000 series processor) Same behavior as t3

**Comment by eyberg** [comment]
we're missing (at least) the ena driver for t3 instances

https://github.com/nanovms/nanos/issues/1233

we plan on adding that in the near future though - I believe there might be another driver we are missing as well to support those instances

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/pull/1365 adds support for running Nanos on AWS instances based on the Nitro hypervisor. Tested on t3, t3a, c4, c5, c5a, c5d and c5n instances.
Note: in order to create an AMI compatible with these instances, Ops needs to patched so that the `EnaSupport` attribute of the `ec2.RegisterImageInput` object passed to `ec2.RegisterImage()` is `true` (https://github.com/nanovms/ops/blob/master/lepton/aws_image.go#L121).

**Comment by eyberg** [comment]
@fabioDMFerreira unclear to me if EnaSupport should be toggled all the time or just for these instances but that should be the only thing left here to close this out

**Comment by fabioDMFerreira** [comment]
@eyberg t2.micro instances work with EnaSupport enabled. Leaving it toggled for now.

**Comment by fabioDMFerreira** [comment]
@francescolavra can't initialize a t2 instance with `EnaSupport` enabled or disabled.

**Comment by francescolavra** [comment]
https://github.com/nanovms/nanos/pull/1383 solves the issue with t2 instances. An image can run on a t2 instance regardless of whether `EnaSupport` is enabled or disabled.
