### ISSUE TITLE
prefer accel over not

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#593]
I think the default should be to have ops always running w/accel on and nag users that can't/won't instead

- [x] warn user if accel is set by ops but we can't actually use it (eg: no virt extensions because they are in a vm or no permission are set) see https://github.com/nanovms/ops/issues/440

- [x] if accel *can't* be set because it's in a vm it should tell the user to turn off accel and maybe explain why

- [x] pro-actively try to install ops https://github.com/nanovms/ops/blob/master/install.sh with the correct perms

as put into the attached pr I believe the reason why this has not been set as default is because the vast majority of users probably will not have these defaults set and will have a bad first time experience

**Comment by emikhalev** [comment]
Is the issue resolved? Or is there are any additional work?

**Comment by eyberg** [comment]
yes - thank you!
