### ISSUE TITLE
add size column to volume list

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#608]
there are human readable functions in helpers.go

**Comment by ahmedaabouzied** [comment]
Doesn't this depend on the pull request #598  by @ronaudinho? I think it's a matter of just printing the `vol.Size()` alongside the other values in this line [here](https://github.com/nanovms/ops/pull/598/commits/4489704ab12e72e5a7f0fc6be005cd560046f2c4#diff-ee760cf9fbb59e36c2a326f6e95ba918R94).

Forgive me guys if this sounds stupid. I'm still figuring my way around the codebase

**Comment by eyberg** [comment]
just merged that, feel free to hit this up, you're correct it is easy/simple

**Comment by ahmedaabouzied** [comment]
@eyberg, I believe there is a breaking bug with that pull request you merged. Please check issue #613 for more info.
