### ISSUE TITLE
extract the rest of mkfs operations into it's own file

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#609]

**Comment by fabioDMFerreira** [comment]
@eyberg I saw some operations referring to mkfs in `lepton/volume.go` and `lepton/image.go`.

Probably, it makes sense to create an MKFS struct which wraps the command execution and stores mkfs location in os.

Let me know which are your thoughts about this approach.

**Comment by eyberg** [comment]
yes i'm in favor of this - just keep in mind that mkfs is used for a few different things so be aware of the abstractions; i think the long term goal here would be to have a go native mkfs but that entails sorting out TFS internals and definitely not something i'd suggest to do anytime soon

**Comment by fabioDMFerreira** [comment]
Ok. I pick this one.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/651
