### ISSUE TITLE
Wrong host path value when loading a package returning an error

### ISSUE THREAD

**Issue by ahmedaabouzied** [nanovms/ops#613]
## Description
The instructions mentioned in the README file stopped working after merging the pull request #598. 

## Steps to reproduce
Follow the basic usage example mentioned in the README file after building the executable file with the latest commit on master branch as follows:
1. Pull the latest commit then build from source.
```bash
git pull origin master
make deps
make build
```
2. Create a `hi.js` file with the following contents 
```js
var http = require('http');
http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/plain'});
    res.end('Hello World\n');
}).listen(8083, "0.0.0.0");
console.log('Server running at http://127.0.0.1:8083/');
```
3. Run this script in ops (the executable built from source) with the load command
```bash
./ops load node_v11.5.0 -p 8083 -f -n -a hi.js
```

It will return an error similar to this 
```bash
warning: overwriting existing file /node_v11.5.0/node hostpath old: /home/ahmedaabouzied/.ops/.staging/node_v11.5.0/node new: node_v11.5.0/node
please check your manifest for the missing file: stat node_v11.5.0/node: no such file or directory
```
**Before merging #598, running the same command with the same values worked normally. To verify that follow the following steps**
1. Reset the head to the commit before merging.
```bash
git reset --hard 5c64d11
```
2. Build ops executable again by running `make build`.
3. Run the `hi.js` script again in the built ops executable and it should run normally.
```bash
./ops load node_v11.5.0 -p 8083 -f -n -a hi.js
```

**Comment by ahmedaabouzied** [comment]
I ran ops in dlv debugger both after merging #598 and before the merge and I found the following results that I suspect is causing the problem.

Before the merge, after loading the package and while extracting it the `hostPath` value passed to the method `AddFile()` [here](https://github.com/nanovms/ops/blob/7ebc83eb03ea86222438f6d36a8fff85f666b7f2/lepton/manifest.go#L266) for the node executable `/node_v11.5.0/node` was in absolute path format.
```bash 
(dlv) print hostpath
"/home/ahmedaabouzied/.ops/.staging/node_v11.5.0/node"
(dlv) print filepath
"/node_v11.5.0/node"
```

After the merge this `hostPath` value was not in absolute path format.
```bash
(dlv) print filepath
"/node_v11.5.0/node"
(dlv) print hostpath
"node_v11.5.0/node"
```

I believe passing the right value as the `hostPath` to the `AddFile()`  method got messed up in the the last merge.

**Comment by ahmedaabouzied** [comment]
@eyberg, we don't have unit or integration tests that could have detected that right?

**Comment by eyberg** [comment]
ugh, yeh i'm not sure why that would be over-writing the file either, no reason for it too..

test would def. be nice

**Comment by eyberg** [comment]
actually the ci fail from nanos did catch this -> 

https://app.circleci.com/pipelines/github/nanovms/nanos/662/workflows/1fa9873a-76a6-4a86-8969-68e1cc0834ae/jobs/4960

**Comment by ahmedaabouzied** [comment]
I think this fixes the issue. Let's close it then
