### ISSUE TITLE
How do I use package to build image 

### ISSUE THREAD

**Issue by podman2020** [nanovms/ops#652]
How do I use package ex . tomcat_9.0.19 and build image , create instance in vsphere?

The package example is showing just ops load tomcat_9.0.19 -p 8080

**Comment by francescolavra** [comment]
@podman2020 the `ops image create` command can take a `-p <package>` option: see for example https://nanovms.gitbook.io/ops/google_cloud, where a Google Cloud image is created starting from the node_v14.2.0 package (the same logic applies for creating images with any other cloud provider, including vsphere).

**Comment by podman2020** [comment]
Thank you, it works .
If I pull the pkg locally, how can I specify the location not pull again during image create?

**Comment by eyberg** [comment]
it won't re-pull the same package after downloading it first unless you delete it; a package isn't actually a disk image - it's just a tarball with an expected filesystem layout

ops does however re-build the image each time on the fly with 'ops load' and 'ops run' - you can pass a '-i' to specify a new image name if you desire (other than the default of the package name) and that will save the image

if you just want to re-run it locally you can use 'ops instance create' to avoid re-building but if you're pushing the cloud every single deploy a new image is created regardless, hth

**Comment by podman2020** [comment]
> @podman2020 not sure I understood your question correctly, but you are using the `-l` Ops flag to load a local package, right?
> If so, are you looking for a way to avoid re-creating the .img file and re-use a previously created file? I'm afraid Ops doesn't support that right now, it always creates the .img file whenever you create an image.

Okay thanks
