### ISSUE TITLE
Add method GetInstance to Provider interface

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops#656]
This method implementation has to be included in other cloud providers structs (gcloud, onprem, aws, digital ocean, vultr, vsphere, openstack, azure)

**Comment by fabioDMFerreira** [comment]
The next providers implementations are missing:
* digital ocean
* onprem
* vultr

**Comment by arknable** [comment]
@fabioDMFerreira There is `GetInstanceByID` method in `master` branch, what kind of `GetInstance` method are you requesting ?

**Comment by fabioDMFerreira** [comment]
The `GetInstance` should return an instance with the name passed by the argument. Heads up that some cloud providers may already have this method. If there are methods doing what is requested in this issue replace the name to uniformize. 

If you add the method to the `Provider` interface in https://github.com/nanovms/ops/blob/master/lepton/provider.go, you may see compilation errors that will help you find the providers where are missing the `GetInstance` method.
