### ISSUE TITLE
determine vpc preference order

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#671]
options include:

* rely on default
* create a new vpc
* add option to specify vpc

if your aws acct is over 7 years old you might not have a default - right now the code is just grabbing the very first one it finds, there's a pr to change that to grab the first default or fail

**Comment by fabioDMFerreira** [comment]
@eyberg I verified we aren't supporting the creation of a vpc in AWS, although we can select one by specifying the name of an existing one in a configuration file.

On Azure, we're creating the vpc with the name specified if it does not exist. I think it makes sense to do the same thing for aws.
https://github.com/nanovms/ops/blob/master/lepton/azure_instance.go#L63

**Comment by eyberg** [comment]
yep, go for it
