### ISSUE TITLE
ops image list fails on invalid region

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#672]
same problem as https://github.com/nanovms/ops/issues/389

**Comment by chaitanya-baraskar** [comment]
once you accept #389 this will be quick fix as I will be able to use utils.

**Comment by chaitanya-baraskar** [comment]
There's no panic in code any more and CLI is giving sufficient infromation right now. This issue is resolved.

**Comment by eyberg** [comment]
I believe you're referring to 389 ?

this one looks like it still needs an error msg along the lines of "Invalid Region"

```
➜  ~ ops image list -t aws -z asdf
RequestError: send request failed
caused by: Post "https://ec2.asdf.amazonaws.com/": dial tcp: lookup ec2.asdf.amazonaws.com: no such host
➜  ~ ops image list -t aws -z us-west-2
+------+----+--------+---------+
| NAME | ID | STATUS | CREATED |
+------+----+--------+---------+
```
