### ISSUE TITLE
gcloud volume attach throws error if auth is not correctly set

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#682]
```
➜  g2 ops volume attach g2-image-1602164790 mnt mnt -t gcp
2020/10/08 09:59:07 googleapi: Error 400: Invalid resource field value in the request., invalidParameter
```

should complain about missing projectID or missing GOOGLE_CREDENTIALS - whatever it is

**Comment by fabioDMFerreira** [comment]
Ops is currently checking google credentials and whether projectID and zone are specified
https://github.com/nanovms/ops/blob/master/lepton/gcp.go#L146
