### ISSUE TITLE
Add instance tagging

### ISSUE THREAD

**Issue by chaitanya-baraskar** [nanovms/ops#704]
Right now OPS fetches all instances . Add instance tagging so only ops related instances will be shown from cloud providers.

**Comment by eyberg** [comment]
@chaitanya-baraskar i'm in favor of this but it would be good to look at the top provider list and ensure we can do this on every single one or if not find out what substitute the proper method should be for the ones we can't - can you enumerate those first? (aws, gcloud, openstack, azure, vsphere)

**Comment by chaitanya-baraskar** [comment]
sure... AWS, GCP and Azure already provides this functionality. I will do some research openstack and vsphere.

**Comment by chaitanya-baraskar** [comment]
@eyberg tagging functionality is provided by vsphere as well and for openstack we can add instance metadata. I think we can achieve this functionality for major providers.

**Comment by eyberg** [comment]
ok cool - go for it

**Comment by fabioDMFerreira** [comment]
couldn't find any documentation or configuration allowing to tag instances and images in vsphere
