### ISSUE TITLE
[Question] Can nanos be configured to never crash the host machine?

### ISSUE THREAD

**Issue by shravanshetty1** [nanovms/ops#712]
I would like to know if there is anyway to ensure security of the host machine while hosting potentially malicious nanos virtual machines. The host machine should never crash or be compromised no matter what the nanos virtual machine does - is this possible if configured correctly?

Just curious, thanks!

**Comment by eyberg** [comment]
it's not really a configuration setting - just room for vulnerabilities - there are vm escapes but they are extremely rare - just to point out the severity/rarity of them though - that's kinda like asking how easy is it to crash/compromise the host in aws (xen) or gcloud (kvm) - cause that's what in affect you would actually be doing if deployed there

**Comment by eyberg** [comment]
as for recovering from crashes whether they be in kernel or user we actually do have a very interesting setting that I personally put on all cloud deploys - https://nanovms.gitbook.io/ops/configuration#reboot-on-exit - it essentially will reboot when a crash occurs in the guest - there are definitely cases where you might not want this turned on (eg: db connection fail) but it can be useful for many other purposes
