### ISSUE TITLE
Replace fmt prints by logger prints

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops#764]
#400

**Comment by arknable** [comment]
@eyberg I will check this.

**Comment by arknable** [comment]
@fabioDMFerreira @eyberg any specific reason why error messages are [optional to be displayed](https://github.com/nanovms/ops/blob/master/lepton/provider.go#L150) ?

**Comment by arknable** [comment]
@eyberg I see there are calls to `panic` function, should I replace them with `log.Panic` ?

**Comment by fabioDMFerreira** [comment]
Yes, there's a reason. We want to display a clean error message and provide error details only when a user explicitly adds debug flags like `show-debug` or `show-error`.

I think we should avoid using `panic` and handle all the errors in the commands handlers. There's an issue to remove them (https://github.com/nanovms/ops/issues/344).

**Comment by arknable** [comment]
@fabioDMFerreira ok thanks.
