### ISSUE TITLE
local package should complain if given an invalid elf

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#789]
we have elf validity checks for ops run but I accidently copied a mach-o for a local pkg and notice we don't do a check there so you get a nasty recursive trace

**Comment by arknable** [comment]
@eyberg I will check this.

**Comment by arknable** [comment]
Tried to reproduce using mac os node binary
```
en1: assigned 10.0.2.15
signal 11 received by tid 1, errno 0, code 1
   fault address 0x818085
   core dump (unimplemented)
exit status 255

```

**Comment by arknable** [comment]
Following is the message output if the package's executable is invalid in linux:
```
package node_v14.2.0 has invalid executable
```

**Comment by eyberg** [comment]
yeh - to clarify it would be good to complain if 'ops run' is given a mach-o as well
