### ISSUE TITLE
should be able to set azure instance size via config

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#791]

**Comment by eyberg** [comment]
it's currently hard-coded to https://github.com/nanovms/ops/blob/master/lepton/azure.go#L514

**Comment by fabioDMFerreira** [comment]
List of possible virtual machine sizes:

https://godoc.org/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2020-06-01/compute#VirtualMachineSizeTypes

The configuration variable to specify the size is `CloudConfig.Flavor`.

**Comment by fabioDMFerreira** [comment]
The allowed virtual machines sizes are displayed if the user specifies an invalid size.
