### ISSUE TITLE
Include tls and radar klibs if telemetry is enabled

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops#802]
As mentioned in https://github.com/nanovms/nanos/pull/1325, the telemetry is enabled if `RADAR_KEY` environment key is specified.

Klibs `tls` and `radar` must be included in images manifests, so reports can be sent to telemetry service.

**Comment by eyberg** [comment]
yeh - I think this is fine - if a user has set such an env var we'll auto-include those klibs
