### ISSUE TITLE
for onprem (local) target && local linux allow user to specify non-user-mode via taps

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#836]
feeding off this old issue https://github.com/nanovms/ops/issues/177

if platform == linux:
* ask user to give perms during install if platform is linux
* ops should give explicit instructions for non-root user to allow creation of tap devices via setcap if not set
* allow instance create for onprem target to create && destroy taps on demand

**Comment by fabioDMFerreira** [comment]
Additionally, I identified the next steps to accomplish this feature

1. Create a bridge network if it doesn't exist
2. Create a TAP with a name specified if it doesn't exist already
3. Add TAP interface to bridge network

Also, the next command flags must be specified: `tapname`, `ipaddr`, `gateway`, `netmask` and `bridged`.

**Comment by fabioDMFerreira** [comment]
In which cases we allow the taps to be destroyed?

**Comment by eyberg** [comment]
if we're talking about 'ops run' then it probably make sense to take them down whenever it's killed either by run to completion or via a signal that we can catch from ctrl-c - for the purposes of this ticket I think we're looking at 'ops run' first and could provide similar support for 'ops instance stop' for onprem in the future

**Comment by eyberg** [comment]
I think we can close this one for now
