### ISSUE TITLE
how to deploy image on to Bare Metal

### ISSUE THREAD

**Issue by podman2020** [nanovms/ops#841]
How to deploy image on to Bare Metal  i.e physical host?
How do we connect to physical machine to deploy?
Does it need pxe setup or something?
appreciate any helpful tips.

**Comment by eyberg** [comment]
@podman2020 we only support deploying to a hypervisor - so kvm/xen would be some choice to consider here - ops now defaults to kvm if ran manually - we don't have any plans to support "flashing" a device - hth

**Comment by am11** [comment]
Looks like with @francescolavra's TSC calibration change (after nanos v0.1.32, unreleased atm), the bare metal may work with (non-UEFI) "legacy" BIOS.

I flashed my SD card using [etcher](https://github.com/balena-io/etcher) with ops generated raw image (e.g. `~/.ops/images/myApp.img` file). The qemu has booted the raw drive on Windows:
```pwsh
#!/usr/bin/env pwsh
C:\> Get-WmiObject Win32_DiskDrive | Where Caption -eq 'SDHC Card'

Partitions : 2
DeviceID   : \\.\PHYSICALDRIVE1
Model      : SDHC Card
Size       : 30951728640
Caption    : SDHC Card

$ &"\Program Files\qemu\qemu-system-x86_64.exe" -L "\Program Files\qemu" `
    -drive file=\\.\PhysicalDrive1,format=raw,media=disk -m 512 --no-reboot
```
With nanos v0.1.32, it failed to boot, but with master branch, it booted and ran successfully.

I wasn't able to test on device, as all systems I have access to do not have "legacy" option available in BIOS. So I will wait for UEFI support. If you have options to switch to legacy BIOS, you can give it a try. 🙂

**Comment by eyberg** [comment]
@am11 we have no plans for true bare metal (eg: booting in non-virtualized environment) - that would conflict with the architecture design

**Comment by am11** [comment]
@eyberg, just for my own understanding, is it because nanos doesn't provide support for vast range of device drivers or the bootloader and kernel can't survive on baremetal?
