### ISSUE TITLE
unable to open filesystem: (result:tfs magic mismatch)

### ISSUE THREAD

**Issue by arunprasadmudaliar** [nanovms/ops#854]
Hi,
I have a simple go program to run go commands from inside the program. So I decided to include the go directory in the image built by ops. For that I used the below config.json
{
            "Dirs": ["/usr/local/go/"]
}

The image is getting built and I am able to launch the instance without issues. However , when I check the logs of that instance it shows the error as below:
unable to open filesystem: (result:tfs magic mismatch)

I  expected it to show either a go related error or the output of go version command (run  by the program).  Can you please guide me here?

Note: I am running this on Windows Subsystem for Linux (Ubuntu).

**Comment by francescolavra** [comment]
Regarding the tfs magic mismatch, I suspect @arunprasadmudaliar is hitting a bug in Nanos whose fix has been merged yesterday (in https://github.com/nanovms/nanos/pull/1366). So if you create the image with the nightly build of the kernel (i.e. add the `-n` command line option to ops) it should work (or at least the created instance should boot).

**Comment by arunprasadmudaliar** [comment]
@eyberg Thanks. No, I haven't built Nanos from source. 

I understood your explanation given in point no.1 .  

Basically,  I am trying to build a FaaS platform in go and was exploring nanos to see if I can spin up nanos to execute the functions. According the current design, a simplified flow should look like below:
 
1. User uploads a func.go.  'service a' processes the file, converts it into a nanos *.img using ops and uploads it to minio.
2. Whenever the user wants to exe the func,  'service b' downloads the *.img and spins up a nanos vm, exe's the func and sends back the result to 'service a'.  (excluding other details to keep it simple)

As part of the .img build process (no. 1) I wanted to spin up a nanos vm that has 'go' env setup and the ELF (which is  a go program) could execute 'go build ' from inside the code. I thought I could use the  'Dirs' or 'MapDirs' configurations to build nanos along with required 'go' env. Though I was able to build the image (mapped with /usr/local/go/ directory) and start the instance (onprem) , but when I check the instance logs  I see the above error. 

This is where I am stuck right now :( . 

The go code that is supposed to run a go build command:
package main

```
import (
        "os/exec"
        "fmt"
)

func main(){
        op, err := exec.Command("/usr/local/go/bin/go","version").CombinedOutput()

        if err!=nil{
                fmt.Println(op)
                fmt.Println(err)
        }

        fmt.Println(string(op))

}
```
```
config.json:
{
            "MapDirs": {"/usr/local/go/*": "/usr/local/go" }
}
```

```
root@DESKTOP-66PAAKH:/home/arun/buildagent# ops instance create -i goagent -t onprem --show-debug
booting goagent ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false

Anyway, we will try to enable hardware acceleration
root@DESKTOP-66PAAKH:/home/arun/buildagent# Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory
qemu-system-x86_64: Back to tcg accelerator
```

Instance logs:
```
root@DESKTOP-66PAAKH:/home/arun/trinity# ops instance list
+------+---------+---------+----------------+-------------+------+
| PID  |  NAME   | STATUS  |    CREATED     | PRIVATE IPS | PORT |
+------+---------+---------+----------------+-------------+------+
| 6046 | goagent | Running | 32 seconds ago | 127.0.0.1   |      |
+------+---------+---------+----------------+-------------+------+
root@DESKTOP-66PAAKH:/home/arun/trinity# ops instance logs goagent
unable to open filesystem: (result:tfs magic mismatch)
```

Since I am doing all these on a WSL enabled Win 10, I was wondering if the filesystem error is due to that?

**Comment by arunprasadmudaliar** [comment]
@francescolavra Thanks. I will do that and update the results.

**Comment by arunprasadmudaliar** [comment]
Sorry, I thought about it again and it looks like a bad design from my end. Please close this.

**Comment by eyberg** [comment]
@arunprasadmudaliar - anything running os.Exec is not going to be supported at all as that entails running other programs

* it sounds like you are trying to build a serverless framework? it'd be one thing if the end-user uploads an actual elf file (being their compiled program) but if you are expecting to do the compilation step inside nanos that's not going to be something that would work out as most build environments run not just one program but many many different programs

* as for the error msg - if you are running ops inside WSL2 - you are already inside a vm and should probably just tack on ```--accel=false```

**Comment by eyberg** [comment]
actually the more i'm looking at your usecase - most of what you want to do is not something that would be done inside nanos - as the running of the vms themselves would be done outside as well by the hypervisor or cloud of choice - this isn't a bad thing - it's just pointing at the fact that you are under a layer which is fine

**Comment by arunprasadmudaliar** [comment]
> @arunprasadmudaliar - anything running os.Exec is not going to be supported at all as that entails running other programs
> 
> * it sounds like you are trying to build a serverless framework? it'd be one thing if the end-user uploads an actual elf file (being their compiled program) but if you are expecting to do the compilation step inside nanos that's not going to be something that would work out as most build environments run not just one program but many many different programs
> * as for the error msg - if you are running ops inside WSL2 - you are already inside a vm and should probably just tack on `--accel=false`

Thank you! 
Yes you are correct about the user uploading the ELF directly and I had similar thoughts. But at a later point I felt that user should be able to write the code using an UI and if that is the case, I would still have to handle the ELF generation.

**Comment by arunprasadmudaliar** [comment]
> actually the more i'm looking at your usecase - most of what you want to do is not something that would be done inside nanos - as the running of the vms themselves would be done outside as well by the hypervisor or cloud of choice - this isn't a bad thing - it's just pointing at the fact that you are under a layer which is fine

As per the prototype, nanos vms will be used as ephemeral vms with the sole task to execute the funcs and report back the status.
Some time later  I thought may be I should use a separate service, a nanosvm (not ephemeral) that does the build and push of ELF to minio. But now its clear to me that this would be a bad design. Since most of the time I work with containers, I assumed about the go env and using os.Exec() to accomplish this. After you pointed out , I realized that it wouldn't be possible from an Unikernel.

As of now, I will stick to my initial plan of using nanos for running my workloads while the core service itself will be running on a standard OS.

Thanks for taking time to provide your inputs!
