### ISSUE TITLE
ops load needs same bridging support as ops run

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#859]
* missing tap flag (honestly we could self-manage these too - i don't see a strong use-case for not doing so, but that can be addressed in a diff tkt)
* missing ip-address flag

**Comment by fabioDMFerreira** [comment]
I see a lot of similarities between these 2 commands. We should reuse the same piece of code in both commands and allow load command to use a package image.

I'll investigate further to check if this is straight forward.

**Comment by eyberg** [comment]
yes - I think down the road there is opportunity to merge several of these together - it's been brought up before - https://github.com/nanovms/ops/issues/459 - the main reason to have 'load' was we wanted the capability to instantly get a hello world built/running in one command for packages (eg: node as reflected on ops.city example)
