### ISSUE TITLE
eval upcloud integration

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#877]
this is an euro based DO/vultr like cloud - looks like since I looked at it last they added an import storage api method which should allow us to easily operate similar to do/vultr

https://github.com/nanovms/nanos/issues/781

**Comment by fabioDMFerreira** [comment]
As we can import raw images to Upcloud and use them as templates to launch instances we shouldn't have problems integrating with them.

See a simple workflow below to create images and instances
1. Create empty storage (https://developers.upcloud.com/1.3/9-storages/#create-storage)
2. Import a nanos image to empty storage (https://developers.upcloud.com/1.3/9-storages/#create-import)
3. Create a template from storage (https://developers.upcloud.com/1.3/9-storages/#templatize-storage)
4. Use the template created to launch instances (https://developers.upcloud.com/1.3/8-servers/#creating-from-a-template)
