### ISSUE TITLE
Issues with args propagation

### ISSUE THREAD

**Issue by am11** [nanovms/ops#942]
1. from readme example, if we add `"Args":["one","two","three"]` to config.json, the app receives `two` and `three` but not `one`
2. if we pass args via command line: `ops run -a one -a two -a three ./myapp`, the app does not receive any arguments.
    * only with `ops pkg load ... -a one -a two -a three`, the app receive all three args. but that is not a viable solution for ELF apps..

**Comment by am11** [comment]
workaround is to use json config with dummy at position 1: `"Args":["dummy","one","two","three"]`

**Comment by eyberg** [comment]
this was recently changed, however, neither of those problems should be occurring and I couldn't quickly reproduce them either..

1) when args is specified manually it can always override
2) this would be straight up broke but i'm unable to repro?

```
➜  t ops run -c config.json t
booting /Users/eyberg/.ops/images/t.img ...
en1: assigned 10.0.2.15
[1 2 3]exit status 1
➜  t ops run t -a 1 -a 2 -a 3
booting /Users/eyberg/.ops/images/t.img ...
en1: assigned 10.0.2.15
[1 2 3]exit status 1
➜  t cat main.go
package main

import (
        "fmt"
        "os"
)

func main() {
        fmt.Printf("%+v", os.Args)
}
➜  t cat config.json
{
  "Args": ["1", "2", "3"]
}
```

is this only w/.net or ?

**Comment by am11** [comment]
With current master of ops, I tested self-contained node.js:

```sh
# compile nanovms/ops master
$ cd ~/ops; make build; cd ..
# write a simple js
$ cat > test1.js <<< 'console.log("args: ", process.argv)'
# compile to ELF executable using 'nexe' (to install `sudo npm i -g nexe`)
$ nexe test1.js
# write ops config
$ cat > config.js <<< '{"Args": ["one","two","three"]}'
# run binary with ops
$ ~/ops/ops run ./test1 -c config.json
booting /home/am11/.ops/images/test1.img ...
You specified hardware acceleration, but it is not supported
Are you running inside a vm? If so disable accel with --accel=false

en1: assigned 10.0.2.15
args:  [ '/test1', '/test1.js', 'two', 'three' ]
exit status 1
```
same result with self-contained .net app that `"one"` is missing.

**Comment by am11** [comment]
Another example with plain C:

```sh
# compile a simple app
$ gcc -xc - -oapp.exe <<EOF
#include<stdio.h>
int main(int argc, char *argv[])
{
    for(int i = 0; i < argc; i++)
    {
        printf("%s\n",argv[i]);
    }
    return 0;
}
EOF

# run on host
$ app.exe 1 2 3
./app.exe
1
2
3

# run with ops with command-line args
$ ops run -a 1 -a 2 -a 3 ./app.exe
please check your manifest for the missing file: stat 1: no such file or directory

# write config.json
$ cat > config.json <<< '{ "Args": ["1", "2", "3"] }'

# run with ops with config.json
$ ops run ./app.exe -c config.json
please check your manifest for the missing file: stat 1: no such file or directory
```

**Comment by eyberg** [comment]
wells that's clearly wrong - when passing via '-a' it should never be overwriting the first argument of program name, cc @fabioDMFerreira

**Comment by am11** [comment]
btw, if we run the go example without ops, it prints something like `[/tmp/go-build385619497/b001/exe/t 1 2 3]`. ops 0.1.19 in your example printed `[1 2 3]` (and eats zeroth arg: `/path/to/t`).

#947 is one way to fix it; problem with merge container, we are doing 'override merge' for all config fields, what we need for Args is 'append merge'.. all examples reported here (incl. fork and dotnet) report same args with and without ops.
