### ISSUE TITLE
No default IP assigned in hyper-v

### ISSUE THREAD

**Issue by am11** [nanovms/ops#944]
When we run with qemu (e.g. `ops run myapp`), the first line shows up the default IP address added by nanos:

![image](https://user-images.githubusercontent.com/3840695/110471382-c02cea80-80e4-11eb-89e8-a552221bb891.png)

deploying to hyper-v, however, does not assign a default IP address:
![image](https://user-images.githubusercontent.com/3840695/110471572-f10d1f80-80e4-11eb-9e4b-07dc1400d14a.png)

there are *two* 0.0.0.0 and a 127.0.0.1 in hyper-v instance when all interfaces are [queried programmatically](https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.getallnetworkinterfaces); compared to qemu instance, which has 10.0.2.15 and 127.0.0.1 out of the box.

ps: btw, going by [this docs section](https://nanovms.gitbook.io/ops/configuration#runconfig.ip_addr), manually adding `"RunConfig": { "IPAddr": "10.0.2.30"}` to config.json has no effect on qemu or hyper-v instances..

**Comment by francescolavra** [comment]
This might be another issue, but I recently ran into a situation where my Nanos instance (which was previously working perfectly fine) started to fail acquiring the IP address. The network interface of the VM was connected to the hyper-v default switch (i.e. the default setting when creating a new VM). Starting and stopping the hyper-v VM manager Windows service did not help, nor did re-creating the instance from scratch. I could only get it to work again after restarting Windows. I noticed the issue after resuming Windows from hibernation, but I can't say whether hibernation was what triggered the problem.

**Comment by am11** [comment]
Unfortunately, restarting didn't remedy situation on my pc.
tried with simple dotnet console app (https://github.com/nanovms/ops-examples/tree/master/dotnet) with this code:
```c#
using System;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Threading.Tasks;

class Program
{
    static Task Main()
    {
        foreach (NetworkInterface netInterface in NetworkInterface.GetAllNetworkInterfaces())
        {
            Console.WriteLine("Name: {0}, Description: {1}, Addresses: [{2}]",
                netInterface.Name,
                netInterface.Description,
                string.Join(", ",
                    netInterface.GetIPProperties().UnicastAddresses.Select(info => info.Address)));
        }

        Console.WriteLine("Shutdown in 15 sec..");
        return Task.Delay(TimeSpan.FromSeconds(15));
    }
}
```
qemu:

![image](https://user-images.githubusercontent.com/3840695/110502575-ff1e6880-8103-11eb-9d80-722c93d00d98.png)

hyperv:

![image](https://user-images.githubusercontent.com/3840695/110502253-b5358280-8103-11eb-8248-24969f0ed908.png)

**Comment by francescolavra** [comment]
Are you deploying to hyperv via Ops?
It looks like you have two network interfaces attached to your VM. Currently Nanos enables its internal DHCP client only on the first network interface, which in your setup doesn't seem to be connected to a host-side network with a running DHCP server.

**Comment by am11** [comment]
Yup, i'm using ops-build and ops-instance-create:

```sh
$ ops build publish/console1 -c config.json -t hyper-v
$ ops instance instance1 -i console1 -c config.json -t hyper-v
```
it creates a VM with two adapters like this:
![image](https://user-images.githubusercontent.com/3840695/110512885-4e699680-810e-11eb-96c2-92c0752c8c03.png)
if i stop the VM, remove the first network interface (`Not Connected` one) and start VM, the assignment message appear after few seconds (before the app has already ran..):
![image](https://user-images.githubusercontent.com/3840695/110513241-aef8d380-810e-11eb-97f9-3e9ec3f7d8a1.png)

and the MVC app, despite the delay assignment, responds in host's browser
![image](https://user-images.githubusercontent.com/3840695/110513832-570e9c80-810f-11eb-8c06-f99ad5669b9d.png)
(the last warning can be ignored; as the new/unmodified aspnetcore mvc app has this `app.UseHttpsRedirection();` line in Startup.cs, which can be removed/commented out for local development..)

so there are two issues:
1. VM being created by ops-instance-create has two network adapters.
2. race condition between address assignment and app run.
    * maybe this one is not important for real app, but would be good to defer app run until it is assigned?

**Comment by am11** [comment]
aside: seems like these functions in hyperv api are unused https://github.com/am11/ops/commit/d157edac421a094235bf0f58cbc30b510ce9e2a5.

**Comment by am11** [comment]
> so there are two issues:
> 
>     1. VM being created by ops-instance-create has two network adapters.
> 
>     2. race condition between address assignment and app run.
>        
>        * maybe this one is not important for real app, but would be good to defer app run until it is assigned?

#946 fixes 1.

**Comment by am11** [comment]
for 2. it would probably require us to make DHCP callback blocking https://github.com/nanovms/nanos/blob/b2c1eec936e1935aa33498c8a88fa3ad2b59fa49/src/net/net.c#L253 (not sure if we want that? maybe make it optional?)

**Comment by fabioDMFerreira** [comment]
Reading IP address from configuration doesn't take effect (https://github.com/nanovms/ops/issues/950).

You can set it through the command flag `--ip-address`  while it's being fixed.
```
$ ops run <elf> --ip-address <ip_address>
```

**Comment by fabioDMFerreira** [comment]
Actually, we can use the IP address from the configuration file, but we have to specify the gateway and the netmask too.

**Comment by am11** [comment]
@fabioDMFerreira, i have tried IPAddr with tip of the current master 134ea46, but apparently it still assigns the IP address from DHCP
![image](https://user-images.githubusercontent.com/3840695/110699373-75e85e00-81f7-11eb-80fe-a00dc4717f54.png)
was this expected?

**Comment by fabioDMFerreira** [comment]
@am11 Could you check whether the IP address is correctly set if the DHCP server is turned off?

**Comment by am11** [comment]
@fabioDMFerreira, any ideas how to turn it off? :)

**Comment by fabioDMFerreira** [comment]
Maybe it's easier to connect to a different network adapter.

Worth to check this, so we can spot whether DHCP is overriding the IP address.

**Comment by am11** [comment]
afaict, the ip is assigned by guest os (nanos) in hyper-v and apparently we are hitting dhcp rather than static address set in `RunConfig.IPAddress`.

btw, it would be nice to have a way to obtain diagnostics from nanos; how it resolved address, to better troubleshoot such issues.

**Comment by am11** [comment]
@fabioDMFerreira, were you able to get desired IP address with `ops instance create -t hyper-v` command? https://github.com/nanovms/ops/issues/944#issuecomment-794219668
I have tested it in different machines but the result is same. Either `-c config.json` is not respected by `ops instance create -t hyper-v ...` or something wrong with hyper-v provider.

**Comment by francescolavra** [comment]
@am11 `ops instance create` does not create a new image, it only runs an already existing image; since IP configuration is set when an image is created (and not on instance creation), any IP config supplied to `ops instance create` is not honored.
If an image is run with `ops run --trace`, it shows a few lines starting with `NET: static IP config:` when a static IP configuration is specified (and doesn't show anything when there is no static config). The internal DHCP client is started only if there is no static config, so if an adapter is assigned an address different from the one set in the configuration, it means the kernel is not being given a static config.

**Comment by am11** [comment]
@francescolavra, I built the image with ops-build then used ops-instance-create. the issue is that if we have only add `IPAddress`, the default netmask and gateway is not set correctly, and therefore it resorts to DHCP. But it works, if we specify netmask and gateway. i.e. it will assign `192.168.1.75`:
```json
{
  "RunConfig": {
    "IPAddress": "192.168.1.75",
    "NetMask": "255.255.255.0",
    "Gateway": "192.168.1.1"
  }
}
```

what i understand from #951 was that it should work without needing to specify NetMask and Gateway?

> any IP config supplied to `ops instance create` is not honored.

UX-wise; since the entire `-c config.json` is disregarded by `ops instance create`, would it make sense if we remove this option from this command's help and error out rather than accepting and silently ignoring it?

**Comment by francescolavra** [comment]
> the entire `-c config.json` is disregarded by `ops instance create`

This is not necessarily true, there are settings that affect how the hypervisor runs the VM (notably, TCP/UDP port forwarding) and as such are appropriate for `ops instance create`.

**Comment by am11** [comment]
This is pretty much understood/resolved. We now set default gateway in nanos based on the given NetMask, when both the IPAddress and NetMask are provided by user config. When only the IPAddress is provided and NetMask is missing, it defaults NetMask to 255.255.255.0 (and then resolves gateway IP, if it was missing).

> there are settings that affect how the hypervisor runs

Ah, makes sense now. 👍

I’m secretly wishing to also wire up `—trace` for hyperv, so we can capture stdout/stderr from the VM on file system instead of / in addition to ETW.. which may also help in future writing integration tests for various ops commands and asserting on live logs from the VM. 🙂
