### ISSUE TITLE
GCP Instance won't boot

### ISSUE THREAD

**Issue by Littlelies** [nanovms/ops#945]
Ops version: 0.1.19
Nanos version: 0.1.32
Reproduced on Linux and MacOS
Last time it worked, it was on Nanos version: 0.1.30 & Ops version: 0.1.15 in January.

Image created using:
```
package main

import "fmt"

func main() {
    fmt.Println("Hello World!")
}
```
and steps described in https://nanovms.gitbook.io/ops/google_cloud

Logs on GCP Serial:
```
Serial port 1 (console) output for hello-1615303411
SeaBIOS (version 1.8.2-google)
Total RAM Size = 0x000000006cc00000 = 1740 MiB
CPUs found: 1     Max CPUs supported: 1
found virtio-scsi at 0:3
virtio-scsi vendor='Google' product='PersistentDisk' rev='1' type=0 removable=0
virtio-scsi blksize=512 sectors=2097152 = 1024 MiB
drive 0x000f24a0: PCHS=0/0/0 translation=lba LCHS=1024/32/63 s=2097152
Sending Seabios boot VM event.
Booting from Hard Disk 0...
```

**Comment by Littlelies** [comment]
It looks like it is stuck on DHCP. As a temporary workaround, I replaced ~/.ops with an old backup (ops 0.1.15) and it is working again (Maybe the issue is in common.tar.gz?)

**Comment by eyberg** [comment]
confirming latest ops doesn't seem to be a problem and 1b136b49b19d5af9b45992f8365e2977e77fe9f6 (0.1.31) seems fine

**Comment by sanderssj** [comment]
The virtio devices were being set up with the wrong offset into the PCI device configuration, so the virtio scsi device was reading the wrong configuration information about how many scsi targets were available (getting 0) and the disk was never discovered.
