### ISSUE TITLE
`ops-instance-create -i` has different behavior across targets

### ISSUE THREAD

**Issue by am11** [nanovms/ops#958]
For example:

```sh
# compile a simple app
$ gcc -xc - -oapp.exe <<EOF
#include<stdio.h>
int main()
{
    printf("Hello World!\n");
    return 0;
}
EOF

# build image for two providers
$ ops build app.exe -t hyper-v
Bootable image file:/home/am11/.ops/vhdx-images/app.vhdx
$ ops build app.exe -t onprem
Bootable image file:/home/am11/.ops/images/app.img
```

`ops instance create -t hyper-v` requires just the image name without extension, otherwise errors out:
> <code>ops instance create instance1_app -i <kbd>app</kbd> -t hyper-v</code>

`ops instance create -t onprem` requires image name with extension, otherwise errors out:
> <code>ops instance create instance1_app -i <kbd>app.img</kbd>-t onprem</code>

**Comment by fabioDMFerreira** [comment]
Yes, we need to make this consistent.

It should accept the names of the images without extension. We've to make sure the images lists don't display the extension as well, so we don't induce anyone in error.

**Comment by am11** [comment]
We could simplify it so only names without extension are acceptable for all targets, otherwise error out.
Also, we can preemptively error out if image doesn't exist (currently we forward the abs. path to target without checking if it actually exist).

**Comment by fabioDMFerreira** [comment]
heads up Ops uses the same images directory to build the artifacts to send to the cloud. These artifacts don't have extension. Having the extension or not it's how Ops distinguish these artifacts from the images built manually.

Prob. we should use a different directory to cache these images, or we could simply remove the artifacts after uploading it to the cloud. The second solution is preferable.

**Comment by am11** [comment]
right, maybe by de-duplicating the code which is dealing with names/paths (passed to instance creation command) from all targets, it will naturally bring about uniformity.

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/464

**Comment by fabioDMFerreira** [comment]
Launching an instance in on-prem doesn't require the image name to have the extension. This was solved down the road.
