### ISSUE TITLE
Instance logs command should read configuration file

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops#959]
Currently, we have to add projectID and zone flags to access the instance logs. Reading these properties from a configuration file makes the command easier to use.

**Comment by eyberg** [comment]
this would be great to have in the .opsrc file as well - ppl don't really change clouds/zones that much

**Comment by fabioDMFerreira** [comment]
We broke the .opsrc while refactoring cmd package. This issue is also fixed in #963
