### ISSUE TITLE
SSH terminated while setting up network

### ISSUE THREAD

**Issue by cbarraford** [nanovms/ops#97]
I built a digitial ocean droplet to setup Ops and give it a go. When i was setting up the network (`sudo ops net setup`), it ran for a little while and then disconnect my ssh connection and now I can't ssh back into my droplet. It seems setting up the network breaks ssh??

```
[root@nanovms-ops ops]$ sudo ./ops net setup
Timeout, server 165.227.174.121 not responding.
```

**Comment by eyberg** [comment]
docs were added for this - in general most users shouldn't be screwing w/their own networking instead  opting for their preferred cloud provider instead
