### ISSUE TITLE
terraform integration

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#991]
i'm not exactly sure how this would fit in considering a lot of terraform operations when it comes to applications/instances are more focused on configuration *after* base ami creation whereas ops does config *before* creation

I think config interposition is one ask here, https://github.com/nanovms/ops/issues/417 along with just the ability to continue using existing tooling to make the exp seamless

**Comment by eyberg** [comment]
it's a bit awkward but I could see us creating the ami via a provider; the deploy obv can be done in 'tf apply' but a question is if image creation would have to be done in the plan step because of validations that prob exist (or whether that could be turned off?)

https://medium.com/spaceapetech/creating-a-terraform-provider-part-1-ed12884e06d7
https://github.com/spaceapegames/terraform-provider-example/tree/master/api

**Comment by fabioDMFerreira** [comment]
I agree. It would be useful to create a provider that manages the Nanos images locally. This way we could trigger the deployment just with one command (`tf apply`).

The next configuration allows us to quickly deploy an image we have in our machine. The image path is specified inside the block `google_storage_bucket_object.walk_server_raw_disk`.
```
provider "google" {
  project = ""
  region  = ""
  zone    = ""
}

resource "google_storage_bucket" "images_bucket" {
  name          = "terraform-images"
  location      = "us"
  force_destroy = true
}

resource "google_storage_bucket_object" "walk_server_raw_disk" {
  name   = "walk-server.tar.gz"
  source = "/home/xyz/.ops/images/walk-server.tar.gz"
  bucket = google_storage_bucket.images_bucket.name
}

resource "google_compute_image" "walk_server_image" {
  name = "walk-server-img"

  raw_disk {
    source = google_storage_bucket_object.walk_server_raw_disk.self_link
  }

  labels = {
    "createdby" = "ops"
  }
}

resource "google_compute_instance" "walk_server_instance" {
  name         = "walk-server"
  machine_type = "f1-micro"

  boot_disk {
    initialize_params {
      image = google_compute_image.walk_server_image.self_link
    }
  }

  labels = {
    "createdby" = "ops"
  }

  network_interface {
    # A default network is created for all GCP projects
    network = "default"
    access_config {
    }
  }
}
```

The above requires us to use ops first to create the image locally. To facilitate this we could create a terraform plugin that would interact with ops to create images. After registering the terraform plugin we would only need to add a block like the next to the terraform configuration.
```
resource "ops_image" "walk-server-nanos-image" {
  elf = "./walk-server"
  target_cloud = "gcp"
  config = "./config.json"
}
```

**Comment by fabioDMFerreira** [comment]
The terraform instegration is in https://github.com/nanovms/terraform-provider-ops.
