### ISSUE TITLE
Support static ip configuration on cloud providers

### ISSUE THREAD

**Issue by fabioDMFerreira** [nanovms/ops#997]

**Comment by eyberg** [comment]
this was added for azure - https://github.com/nanovms/ops/blob/master/azure/azure_network.go#L257  - i'm not sure which cloud providers this is missing on?

**Comment by eyberg** [comment]
this was added the other week to aws as well https://github.com/nanovms/ops/pull/1283 - so not sure if that just means gcp is the only other one?
